public class Desktop {
    static String brand ;
    static String model ;
    static String processor ;
    static int ramSize ;
    static int storageCapacity ;
    static String storageType ;
    static String os ;
    static boolean hasGraphicsCard ;
    static String powerSupply ;
    static String cabinetType ;
    static int usbPorts ;
    static boolean hasWifi ;
    static boolean hasBluetooth ;
    static boolean hasWebcam ;
    static String motherboardModel ;
    static boolean isSSD ;
    static String monitorBrand ;
    static int screenSize ;
    static boolean isTouchScreen ;
    static String keyboardType ;

    public static void main(String[] args) {
        System.out.println("Desktop Details:");
        System.out.println("Brand: " + brand);
        System.out.println("Model: " + model);
        System.out.println("Processor: " + processor);
        System.out.println("RAM Size: " + ramSize + " GB");
        System.out.println("Storage Capacity: " + storageCapacity + " GB");
        System.out.println("Storage Type: " + storageType);
        System.out.println("Operating System: " + os);
        System.out.println("Has Graphics Card: " + hasGraphicsCard);
        System.out.println("Power Supply: " + powerSupply);
        System.out.println("Cabinet Type: " + cabinetType);
        System.out.println("USB Ports: " + usbPorts);
        System.out.println("Has WiFi: " + hasWifi);
        System.out.println("Has Bluetooth: " + hasBluetooth);
        System.out.println("Has Webcam: " + hasWebcam);
        System.out.println("Motherboard Model: " + motherboardModel);
        System.out.println("Is SSD: " + isSSD);
        System.out.println("Monitor Brand: " + monitorBrand);
        System.out.println("Screen Size: " + screenSize + " inches");
        System.out.println("Is Touch Screen: " + isTouchScreen);
        System.out.println("Keyboard Type: " + keyboardType);

      String brand = "Dell";
      String model = "OptiPlex 7090";
      String processor = "Intel Core i7";
      int ramSize = 16;
      int storageCapacity = 1024;
      String storageType = "SSD";
      String os = "Windows 11 Pro";
      boolean hasGraphicsCard = true;
      String powerSupply = "500W";
      String cabinetType = "Mid Tower";
      int usbPorts = 6;
      boolean hasWifi = true;
      boolean hasBluetooth = true;
      boolean hasWebcam = false;
      String motherboardModel = "Intel B560";
      boolean isSSD = true;
      String monitorBrand = "Dell UltraSharp";
      int screenSize = 24;
      boolean isTouchScreen = false;
      String keyboardType = "Mechanical";

        System.out.println("Desktop Details:");
        System.out.println("Brand: " + brand);
        System.out.println("Model: " + model);
        System.out.println("Processor: " + processor);
        System.out.println("RAM Size: " + ramSize + " GB");
        System.out.println("Storage Capacity: " + storageCapacity + " GB");
        System.out.println("Storage Type: " + storageType);
        System.out.println("Operating System: " + os);
        System.out.println("Has Graphics Card: " + hasGraphicsCard);
        System.out.println("Power Supply: " + powerSupply);
        System.out.println("Cabinet Type: " + cabinetType);
        System.out.println("USB Ports: " + usbPorts);
        System.out.println("Has WiFi: " + hasWifi);
        System.out.println("Has Bluetooth: " + hasBluetooth);
        System.out.println("Has Webcam: " + hasWebcam);
        System.out.println("Motherboard Model: " + motherboardModel);
        System.out.println("Is SSD: " + isSSD);
        System.out.println("Monitor Brand: " + monitorBrand);
        System.out.println("Screen Size: " + screenSize + " inches");
        System.out.println("Is Touch Screen: " + isTouchScreen);
        System.out.println("Keyboard Type: " + keyboardType);
    }
}
