public class PoliceStation {
    static String name ;
    static String location ;
    static String jurisdiction ;
    static int officersCount ;
    static int vehiclesAvailable ;
    static boolean hasCCTV ;
    static String emergencyContact ;
    static String inspectorName ;
    static int casesSolved ;
    static int pendingCases ;
    static int numberOfCells ;
    static String buildingType ;
    static boolean womenHelpDesk ;
    static String stationCode ;
    static boolean is24hrService ;
    static String establishedYear ;
    static boolean hasDogSquad ;
    static int computers ;
    static int armsStored ;
    static String email ;

    public static void main(String[] args) {
        System.out.println("Police Station Details:");
        System.out.println("Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("Jurisdiction: " + jurisdiction);
        System.out.println("Officers Count: " + officersCount);
        System.out.println("Vehicles Available: " + vehiclesAvailable);
        System.out.println("Has CCTV: " + hasCCTV);
        System.out.println("Emergency Contact: " + emergencyContact);
        System.out.println("Inspector Name: " + inspectorName);
        System.out.println("Cases Solved: " + casesSolved);
        System.out.println("Pending Cases: " + pendingCases);
        System.out.println("Number Of Cells: " + numberOfCells);
        System.out.println("Building Type: " + buildingType);
        System.out.println("Women Help Desk: " + womenHelpDesk);
        System.out.println("Station Code: " + stationCode);
        System.out.println("24hr Service: " + is24hrService);
        System.out.println("Established Year: " + establishedYear);
        System.out.println("Has Dog Squad: " + hasDogSquad);
        System.out.println("Computers: " + computers);
        System.out.println("Arms Stored: " + armsStored);
        System.out.println("Email: " + email);

       String name = "Central Police Station";
       String location = "Main Street, Sector 5";
       String jurisdiction = "Zone A";
       int officersCount = 50;
       int vehiclesAvailable = 6;
       boolean hasCCTV = true;
       String emergencyContact = "100";
       String inspectorName = "Suresh Kumar";
       int casesSolved = 220;
       int pendingCases = 12;
       int numberOfCells = 5;
       String buildingType = "Government";
       boolean womenHelpDesk = true;
       String stationCode = "CPS1023";
       boolean is24hrService = true;
       String establishedYear = "1975";
       boolean hasDogSquad = true;
       int computers = 15;
       int armsStored = 80;
       String email = "centralps@police.gov";

        System.out.println("Police Station Details:");
        System.out.println("Name: " + name);
        System.out.println("Location: " + location);
        System.out.println("Jurisdiction: " + jurisdiction);
        System.out.println("Officers Count: " + officersCount);
        System.out.println("Vehicles Available: " + vehiclesAvailable);
        System.out.println("Has CCTV: " + hasCCTV);
        System.out.println("Emergency Contact: " + emergencyContact);
        System.out.println("Inspector Name: " + inspectorName);
        System.out.println("Cases Solved: " + casesSolved);
        System.out.println("Pending Cases: " + pendingCases);
        System.out.println("Number Of Cells: " + numberOfCells);
        System.out.println("Building Type: " + buildingType);
        System.out.println("Women Help Desk: " + womenHelpDesk);
        System.out.println("Station Code: " + stationCode);
        System.out.println("24hr Service: " + is24hrService);
        System.out.println("Established Year: " + establishedYear);
        System.out.println("Has Dog Squad: " + hasDogSquad);
        System.out.println("Computers: " + computers);
        System.out.println("Arms Stored: " + armsStored);
        System.out.println("Email: " + email);
    }
}
