class AmusementParkRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        AmusementPark park1 = new AmusementPark();
        park1.name = "Wonderla";
        park1.location = "Bangalore";
        park1.noOfRides = 60;
        park1.entryFee = 1250.0f;
        park1.hasWaterPark = true;
        park1.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park1.name);
        System.out.println("LOCATION : " + park1.location);
        System.out.println("NO OF RIDES : " + park1.noOfRides);
        System.out.println("ENTRY FEE : " + park1.entryFee);
        System.out.println("HAS WATER PARK : " + park1.hasWaterPark);
        System.out.println("BEST SEASON : " + park1.bestSeasonToVisit);

        AmusementPark park2 = new AmusementPark();
        park2.name = "Imagica";
        park2.location = "Mumbai";
        park2.noOfRides = 45;
        park2.entryFee = 1500.0f;
        park2.hasWaterPark = true;
        park2.bestSeasonToVisit = "Monsoon";
        System.out.println("NAME : " + park2.name);
        System.out.println("LOCATION : " + park2.location);
        System.out.println("NO OF RIDES : " + park2.noOfRides);
        System.out.println("ENTRY FEE : " + park2.entryFee);
        System.out.println("HAS WATER PARK : " + park2.hasWaterPark);
        System.out.println("BEST SEASON : " + park2.bestSeasonToVisit);

        AmusementPark park3 = new AmusementPark();
        park3.name = "Essel World";
        park3.location = "Mumbai";
        park3.noOfRides = 30;
        park3.entryFee = 900.0f;
        park3.hasWaterPark = true;
        park3.bestSeasonToVisit = "Summer";
        System.out.println("NAME : " + park3.name);
        System.out.println("LOCATION : " + park3.location);
        System.out.println("NO OF RIDES : " + park3.noOfRides);
        System.out.println("ENTRY FEE : " + park3.entryFee);
        System.out.println("HAS WATER PARK : " + park3.hasWaterPark);
        System.out.println("BEST SEASON : " + park3.bestSeasonToVisit);

        AmusementPark park4 = new AmusementPark();
        park4.name = "Nicco Park";
        park4.location = "Kolkata";
        park4.noOfRides = 25;
        park4.entryFee = 800.0f;
        park4.hasWaterPark = false;
        park4.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park4.name);
        System.out.println("LOCATION : " + park4.location);
        System.out.println("NO OF RIDES : " + park4.noOfRides);
        System.out.println("ENTRY FEE : " + park4.entryFee);
        System.out.println("HAS WATER PARK : " + park4.hasWaterPark);
        System.out.println("BEST SEASON : " + park4.bestSeasonToVisit);

        AmusementPark park5 = new AmusementPark();
        park5.name = "Ramoji Film City";
        park5.location = "Hyderabad";
        park5.noOfRides = 20;
        park5.entryFee = 1000.0f;
        park5.hasWaterPark = true;
        park5.bestSeasonToVisit = "Spring";
        System.out.println("NAME : " + park5.name);
        System.out.println("LOCATION : " + park5.location);
        System.out.println("NO OF RIDES : " + park5.noOfRides);
        System.out.println("ENTRY FEE : " + park5.entryFee);
        System.out.println("HAS WATER PARK : " + park5.hasWaterPark);
        System.out.println("BEST SEASON : " + park5.bestSeasonToVisit);

        AmusementPark park6 = new AmusementPark();
        park6.name = "Kingdom of Dreams";
        park6.location = "Gurgaon";
        park6.noOfRides = 15;
        park6.entryFee = 850.0f;
        park6.hasWaterPark = false;
        park6.bestSeasonToVisit = "Autumn";
        System.out.println("NAME : " + park6.name);
        System.out.println("LOCATION : " + park6.location);
        System.out.println("NO OF RIDES : " + park6.noOfRides);
        System.out.println("ENTRY FEE : " + park6.entryFee);
        System.out.println("HAS WATER PARK : " + park6.hasWaterPark);
        System.out.println("BEST SEASON : " + park6.bestSeasonToVisit);

        AmusementPark park7 = new AmusementPark();
        park7.name = "Adventure Island";
        park7.location = "Delhi";
        park7.noOfRides = 35;
        park7.entryFee = 950.0f;
        park7.hasWaterPark = true;
        park7.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park7.name);
        System.out.println("LOCATION : " + park7.location);
        System.out.println("NO OF RIDES : " + park7.noOfRides);
        System.out.println("ENTRY FEE : " + park7.entryFee);
        System.out.println("HAS WATER PARK : " + park7.hasWaterPark);
        System.out.println("BEST SEASON : " + park7.bestSeasonToVisit);

        AmusementPark park8 = new AmusementPark();
        park8.name = "Appu Ghar";
        park8.location = "Pune";
        park8.noOfRides = 28;
        park8.entryFee = 700.0f;
        park8.hasWaterPark = false;
        park8.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park8.name);
        System.out.println("LOCATION : " + park8.location);
        System.out.println("NO OF RIDES : " + park8.noOfRides);
        System.out.println("ENTRY FEE : " + park8.entryFee);
        System.out.println("HAS WATER PARK : " + park8.hasWaterPark);
        System.out.println("BEST SEASON : " + park8.bestSeasonToVisit);

        AmusementPark park9 = new AmusementPark();
        park9.name = "Funtasia Island";
        park9.location = "Patna";
        park9.noOfRides = 22;
        park9.entryFee = 600.0f;
        park9.hasWaterPark = true;
        park9.bestSeasonToVisit = "Summer";
        System.out.println("NAME : " + park9.name);
        System.out.println("LOCATION : " + park9.location);
        System.out.println("NO OF RIDES : " + park9.noOfRides);
        System.out.println("ENTRY FEE : " + park9.entryFee);
        System.out.println("HAS WATER PARK : " + park9.hasWaterPark);
        System.out.println("BEST SEASON : " + park9.bestSeasonToVisit);

        AmusementPark park10 = new AmusementPark();
        park10.name = "Ocean Park";
        park10.location = "Hyderabad";
        park10.noOfRides = 40;
        park10.entryFee = 1100.0f;
        park10.hasWaterPark = true;
        park10.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park10.name);
        System.out.println("LOCATION : " + park10.location);
        System.out.println("NO OF RIDES : " + park10.noOfRides);
        System.out.println("ENTRY FEE : " + park10.entryFee);
        System.out.println("HAS WATER PARK : " + park10.hasWaterPark);
        System.out.println("BEST SEASON : " + park10.bestSeasonToVisit);

        AmusementPark park11 = new AmusementPark();
        park11.name = "Snow Kingdom";
        park11.location = "Chennai";
        park11.noOfRides = 10;
        park11.entryFee = 500.0f;
        park11.hasWaterPark = false;
        park11.bestSeasonToVisit = "Summer";
        System.out.println("NAME : " + park11.name);
        System.out.println("LOCATION : " + park11.location);
        System.out.println("NO OF RIDES : " + park11.noOfRides);
        System.out.println("ENTRY FEE : " + park11.entryFee);
        System.out.println("HAS WATER PARK : " + park11.hasWaterPark);
        System.out.println("BEST SEASON : " + park11.bestSeasonToVisit);

        AmusementPark park12 = new AmusementPark();
        park12.name = "GRS Fantasy Park";
        park12.location = "Mysore";
        park12.noOfRides = 32;
        park12.entryFee = 950.0f;
        park12.hasWaterPark = true;
        park12.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park12.name);
        System.out.println("LOCATION : " + park12.location);
        System.out.println("NO OF RIDES : " + park12.noOfRides);
        System.out.println("ENTRY FEE : " + park12.entryFee);
        System.out.println("HAS WATER PARK : " + park12.hasWaterPark);
        System.out.println("BEST SEASON : " + park12.bestSeasonToVisit);

        AmusementPark park13 = new AmusementPark();
        park13.name = "Queens Land";
        park13.location = "Chennai";
        park13.noOfRides = 50;
        park13.entryFee = 1400.0f;
        park13.hasWaterPark = true;
        park13.bestSeasonToVisit = "Autumn";
        System.out.println("NAME : " + park13.name);
        System.out.println("LOCATION : " + park13.location);
        System.out.println("NO OF RIDES : " + park13.noOfRides);
        System.out.println("ENTRY FEE : " + park13.entryFee);
        System.out.println("HAS WATER PARK : " + park13.hasWaterPark);
        System.out.println("BEST SEASON : " + park13.bestSeasonToVisit);

        AmusementPark park14 = new AmusementPark();
        park14.name = "Worlds of Wonder";
        park14.location = "Noida";
        park14.noOfRides = 42;
        park14.entryFee = 1350.0f;
        park14.hasWaterPark = true;
        park14.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park14.name);
        System.out.println("LOCATION : " + park14.location);
        System.out.println("NO OF RIDES : " + park14.noOfRides);
        System.out.println("ENTRY FEE : " + park14.entryFee);
        System.out.println("HAS WATER PARK : " + park14.hasWaterPark);
        System.out.println("BEST SEASON : " + park14.bestSeasonToVisit);

        AmusementPark park15 = new AmusementPark();
        park15.name = "Dream World";
        park15.location = "Thrissur";
        park15.noOfRides = 38;
        park15.entryFee = 1200.0f;
        park15.hasWaterPark = true;
        park15.bestSeasonToVisit = "Spring";
        System.out.println("NAME : " + park15.name);
        System.out.println("LOCATION : " + park15.location);
        System.out.println("NO OF RIDES : " + park15.noOfRides);
        System.out.println("ENTRY FEE : " + park15.entryFee);
        System.out.println("HAS WATER PARK : " + park15.hasWaterPark);
        System.out.println("BEST SEASON : " + park15.bestSeasonToVisit);

        AmusementPark park16 = new AmusementPark();
        park16.name = "Fantasy Park";
        park16.location = "Palakkad";
        park16.noOfRides = 18;
        park16.entryFee = 650.0f;
        park16.hasWaterPark = true;
        park16.bestSeasonToVisit = "Summer";
        System.out.println("NAME : " + park16.name);
        System.out.println("LOCATION : " + park16.location);
        System.out.println("NO OF RIDES : " + park16.noOfRides);
        System.out.println("ENTRY FEE : " + park16.entryFee);
        System.out.println("HAS WATER PARK : " + park16.hasWaterPark);
        System.out.println("BEST SEASON : " + park16.bestSeasonToVisit);

        AmusementPark park17 = new AmusementPark();
        park17.name = "Ocean Kingdom";
        park17.location = "Kerala";
        park17.noOfRides = 29;
        park17.entryFee = 950.0f;
        park17.hasWaterPark = true;
        park17.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park17.name);
        System.out.println("LOCATION : " + park17.location);
        System.out.println("NO OF RIDES : " + park17.noOfRides);
        System.out.println("ENTRY FEE : " + park17.entryFee);
        System.out.println("HAS WATER PARK : " + park17.hasWaterPark);
        System.out.println("BEST SEASON : " + park17.bestSeasonToVisit);

        AmusementPark park18 = new AmusementPark();
        park18.name = "Happy Valley";
        park18.location = "Goa";
        park18.noOfRides = 20;
        park18.entryFee = 750.0f;
        park18.hasWaterPark = false;
        park18.bestSeasonToVisit = "Monsoon";
        System.out.println("NAME : " + park18.name);
        System.out.println("LOCATION : " + park18.location);
        System.out.println("NO OF RIDES : " + park18.noOfRides);
        System.out.println("ENTRY FEE : " + park18.entryFee);
        System.out.println("HAS WATER PARK : " + park18.hasWaterPark);
        System.out.println("BEST SEASON : " + park18.bestSeasonToVisit);

        AmusementPark park19 = new AmusementPark();
        park19.name = "Fun City";
        park19.location = "Delhi";
        park19.noOfRides = 12;
        park19.entryFee = 500.0f;
        park19.hasWaterPark = false;
        park19.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park19.name);
        System.out.println("LOCATION : " + park19.location);
        System.out.println("NO OF RIDES : " + park19.noOfRides);
        System.out.println("ENTRY FEE : " + park19.entryFee);
        System.out.println("HAS WATER PARK : " + park19.hasWaterPark);
        System.out.println("BEST SEASON : " + park19.bestSeasonToVisit);

        AmusementPark park20 = new AmusementPark();
        park20.name = "Fun World";
        park20.location = "Bangalore";
        park20.noOfRides = 26;
        park20.entryFee = 900.0f;
        park20.hasWaterPark = true;
        park20.bestSeasonToVisit = "Winter";
        System.out.println("NAME : " + park20.name);
        System.out.println("LOCATION : " + park20.location);
        System.out.println("NO OF RIDES : " + park20.noOfRides);
        System.out.println("ENTRY FEE : " + park20.entryFee);
        System.out.println("HAS WATER PARK : " + park20.hasWaterPark);
        System.out.println("BEST SEASON : " + park20.bestSeasonToVisit);

        System.out.println("MAIN ENDED");
    }
}
