class BillRunner{

public static void main(String billing[]){
	
	System.out.println("MAIN STAERTED");
 	Bill firstBill = new Bill();
        firstBill.billId = 1;
        firstBill.planType = "monthly plan";
        firstBill.billAmountWithTax = 399.99;
        firstBill.billIssueDate = "26/05/2003";
        firstBill.paymentMethod = "netbanking";
        firstBill.billDueDate = "06/06/2003";
        firstBill.isTaxInclusive = true;
        firstBill.isBillPaid = false;
        firstBill.isBillOverDue = true;
        System.out.println("the bill id is " + firstBill.billId);
        System.out.println("the plan type is " + firstBill.planType);
        System.out.println("the billAmount With Tax is " + firstBill.billAmountWithTax);
        System.out.println("the issue date is " + firstBill.billIssueDate);
        System.out.println("the paymentMethod is " + firstBill.paymentMethod);
        System.out.println("the due date is " + firstBill.billDueDate);
        System.out.println("is tax included " + firstBill.isTaxInclusive);
        System.out.println("is bill paid " + firstBill.isBillPaid);
        System.out.println("is bill over due " + firstBill.isBillOverDue);
        System.out.println("");

        Bill secondBill = new Bill();
        secondBill.billId = 2;
        secondBill.planType = "yearly plan";
        secondBill.billAmountWithTax = 4999.99;
        secondBill.billIssueDate = "12/07/2004";
        secondBill.paymentMethod = "credit card";
        secondBill.billDueDate = "22/07/2004";
        secondBill.isTaxInclusive = true;
        secondBill.isBillPaid = true;
        secondBill.isBillOverDue = false;
        System.out.println("the bill id is " + secondBill.billId);
        System.out.println("the plan type is " + secondBill.planType);
        System.out.println("the billAmount With Tax is " + secondBill.billAmountWithTax);
        System.out.println("the issue date is " + secondBill.billIssueDate);
        System.out.println("the paymentMethod is " + secondBill.paymentMethod);
        System.out.println("the due date is " + secondBill.billDueDate);
        System.out.println("is tax included " + secondBill.isTaxInclusive);
        System.out.println("is bill paid " + secondBill.isBillPaid);
        System.out.println("is bill over due " + secondBill.isBillOverDue);
        System.out.println("");

        Bill thirdBill = new Bill();
        thirdBill.billId = 3;
        thirdBill.planType = "quarterly plan";
        thirdBill.billAmountWithTax = 1299.50;
        thirdBill.billIssueDate = "10/03/2005";
        thirdBill.paymentMethod = "UPI";
        thirdBill.billDueDate = "20/03/2005";
        thirdBill.isTaxInclusive = true;
        thirdBill.isBillPaid = false;
        thirdBill.isBillOverDue = false;
        System.out.println("the bill id is " + thirdBill.billId);
        System.out.println("the plan type is " + thirdBill.planType);
        System.out.println("the billAmount With Tax is " + thirdBill.billAmountWithTax);
        System.out.println("the issue date is " + thirdBill.billIssueDate);
        System.out.println("the paymentMethod is " + thirdBill.paymentMethod);
        System.out.println("the due date is " + thirdBill.billDueDate);
        System.out.println("is tax included " + thirdBill.isTaxInclusive);
        System.out.println("is bill paid " + thirdBill.isBillPaid);
        System.out.println("is bill over due " + thirdBill.isBillOverDue);
        System.out.println("");

        Bill fourthBill = new Bill();
        fourthBill.billId = 4;
        fourthBill.planType = "monthly plan";
        fourthBill.billAmountWithTax = 499.00;
        fourthBill.billIssueDate = "15/08/2006";
        fourthBill.paymentMethod = "debit card";
        fourthBill.billDueDate = "25/08/2006";
        fourthBill.isTaxInclusive = true;
        fourthBill.isBillPaid = true;
        fourthBill.isBillOverDue = false;
        System.out.println("the bill id is " + fourthBill.billId);
        System.out.println("the plan type is " + fourthBill.planType);
        System.out.println("the billAmount With Tax is " + fourthBill.billAmountWithTax);
        System.out.println("the issue date is " + fourthBill.billIssueDate);
        System.out.println("the paymentMethod is " + fourthBill.paymentMethod);
        System.out.println("the due date is " + fourthBill.billDueDate);
        System.out.println("is tax included " + fourthBill.isTaxInclusive);
        System.out.println("is bill paid " + fourthBill.isBillPaid);
        System.out.println("is bill over due " + fourthBill.isBillOverDue);
        System.out.println("");

        Bill fifthBill = new Bill();
        fifthBill.billId = 5;
        fifthBill.planType = "half-yearly plan";
        fifthBill.billAmountWithTax = 2399.75;
        fifthBill.billIssueDate = "02/11/2007";
        fifthBill.paymentMethod = "cash";
        fifthBill.billDueDate = "12/11/2007";
        fifthBill.isTaxInclusive = false;
        fifthBill.isBillPaid = true;
        fifthBill.isBillOverDue = false;
        System.out.println("the bill id is " + fifthBill.billId);
        System.out.println("the plan type is " + fifthBill.planType);
        System.out.println("the billAmount With Tax is " + fifthBill.billAmountWithTax);
        System.out.println("the issue date is " + fifthBill.billIssueDate);
        System.out.println("the paymentMethod is " + fifthBill.paymentMethod);
        System.out.println("the due date is " + fifthBill.billDueDate);
        System.out.println("is tax included " + fifthBill.isTaxInclusive);
        System.out.println("is bill paid " + fifthBill.isBillPaid);
        System.out.println("is bill over due " + fifthBill.isBillOverDue);
        System.out.println("");

        Bill sixthBill = new Bill();
        sixthBill.billId = 6;
        sixthBill.planType = "monthly plan";
        sixthBill.billAmountWithTax = 399.00;
        sixthBill.billIssueDate = "01/01/2008";
        sixthBill.paymentMethod = "netbanking";
        sixthBill.billDueDate = "11/01/2008";
        sixthBill.isTaxInclusive = true;
        sixthBill.isBillPaid = false;
        sixthBill.isBillOverDue = true;
        System.out.println("the bill id is " + sixthBill.billId);
        System.out.println("the plan type is " + sixthBill.planType);
        System.out.println("the billAmount With Tax is " + sixthBill.billAmountWithTax);
        System.out.println("the issue date is " + sixthBill.billIssueDate);
        System.out.println("the paymentMethod is " + sixthBill.paymentMethod);
        System.out.println("the due date is " + sixthBill.billDueDate);
        System.out.println("is tax included " + sixthBill.isTaxInclusive);
        System.out.println("is bill paid " + sixthBill.isBillPaid);
        System.out.println("is bill over due " + sixthBill.isBillOverDue);
        System.out.println("");

        Bill seventhBill = new Bill();
        seventhBill.billId = 7;
        seventhBill.planType = "quarterly plan";
        seventhBill.billAmountWithTax = 1299.99;
        seventhBill.billIssueDate = "20/02/2009";
        seventhBill.paymentMethod = "UPI";
        seventhBill.billDueDate = "01/03/2009";
        seventhBill.isTaxInclusive = true;
        seventhBill.isBillPaid = true;
        seventhBill.isBillOverDue = false;
        System.out.println("the bill id is " + seventhBill.billId);
        System.out.println("the plan type is " + seventhBill.planType);
        System.out.println("the billAmount With Tax is " + seventhBill.billAmountWithTax);
        System.out.println("the issue date is " + seventhBill.billIssueDate);
        System.out.println("the paymentMethod is " + seventhBill.paymentMethod);
        System.out.println("the due date is " + seventhBill.billDueDate);
        System.out.println("is tax included " + seventhBill.isTaxInclusive);
        System.out.println("is bill paid " + seventhBill.isBillPaid);
        System.out.println("is bill over due " + seventhBill.isBillOverDue);
        System.out.println("");

        Bill eighthBill = new Bill();
        eighthBill.billId = 8;
        eighthBill.planType = "yearly plan";
        eighthBill.billAmountWithTax = 4799.49;
        eighthBill.billIssueDate = "25/05/2010";
        eighthBill.paymentMethod = "debit card";
        eighthBill.billDueDate = "04/06/2010";
        eighthBill.isTaxInclusive = false;
        eighthBill.isBillPaid = false;
        eighthBill.isBillOverDue = true;
        System.out.println("the bill id is " + eighthBill.billId);
        System.out.println("the plan type is " + eighthBill.planType);
        System.out.println("the billAmount With Tax is " + eighthBill.billAmountWithTax);
        System.out.println("the issue date is " + eighthBill.billIssueDate);
        System.out.println("the paymentMethod is " + eighthBill.paymentMethod);
        System.out.println("the due date is " + eighthBill.billDueDate);
        System.out.println("is tax included " + eighthBill.isTaxInclusive);
        System.out.println("is bill paid " + eighthBill.isBillPaid);
        System.out.println("is bill over due " + eighthBill.isBillOverDue);
        System.out.println("");
        Bill ninthBill = new Bill();
        ninthBill.billId = 9;
        ninthBill.planType = "monthly plan";
        ninthBill.billAmountWithTax = 420.00;
        ninthBill.billIssueDate = "09/09/2011";
        ninthBill.paymentMethod = "credit card";
        ninthBill.billDueDate = "19/09/2011";
        ninthBill.isTaxInclusive = true;
        ninthBill.isBillPaid = true;
        ninthBill.isBillOverDue = false;
        System.out.println("the bill id is " + ninthBill.billId);
        System.out.println("the plan type is " + ninthBill.planType);
        System.out.println("the billAmount With Tax is " + ninthBill.billAmountWithTax);
        System.out.println("the issue date is " + ninthBill.billIssueDate);
        System.out.println("the paymentMethod is " + ninthBill.paymentMethod);
        System.out.println("the due date is " + ninthBill.billDueDate);
        System.out.println("is tax included " + ninthBill.isTaxInclusive);
        System.out.println("is bill paid " + ninthBill.isBillPaid);
        System.out.println("is bill over due " + ninthBill.isBillOverDue);
        System.out.println("");

        Bill tenthBill = new Bill();
        tenthBill.billId = 10;
        tenthBill.planType = "half-yearly plan";
        tenthBill.billAmountWithTax = 2499.75;
        tenthBill.billIssueDate = "12/12/2012";
        tenthBill.paymentMethod = "UPI";
        tenthBill.billDueDate = "22/12/2012";
        tenthBill.isTaxInclusive = true;
        tenthBill.isBillPaid = false;
        tenthBill.isBillOverDue = true;
        System.out.println("the bill id is " + tenthBill.billId);
        System.out.println("the plan type is " + tenthBill.planType);
        System.out.println("the billAmount With Tax is " + tenthBill.billAmountWithTax);
        System.out.println("the issue date is " + tenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + tenthBill.paymentMethod);
        System.out.println("the due date is " + tenthBill.billDueDate);
        System.out.println("is tax included " + tenthBill.isTaxInclusive);
        System.out.println("is bill paid " + tenthBill.isBillPaid);
        System.out.println("is bill over due " + tenthBill.isBillOverDue);
        System.out.println("");

        Bill eleventhBill = new Bill();
        eleventhBill.billId = 11;
        eleventhBill.planType = "yearly plan";
        eleventhBill.billAmountWithTax = 5999.00;
        eleventhBill.billIssueDate = "15/01/2013";
        eleventhBill.paymentMethod = "netbanking";
        eleventhBill.billDueDate = "25/01/2013";
        eleventhBill.isTaxInclusive = true;
        eleventhBill.isBillPaid = true;
        eleventhBill.isBillOverDue = false;
        System.out.println("the bill id is " + eleventhBill.billId);
        System.out.println("the plan type is " + eleventhBill.planType);
        System.out.println("the billAmount With Tax is " + eleventhBill.billAmountWithTax);
        System.out.println("the issue date is " + eleventhBill.billIssueDate);
        System.out.println("the paymentMethod is " + eleventhBill.paymentMethod);
        System.out.println("the due date is " + eleventhBill.billDueDate);
        System.out.println("is tax included " + eleventhBill.isTaxInclusive);
        System.out.println("is bill paid " + eleventhBill.isBillPaid);
        System.out.println("is bill over due " + eleventhBill.isBillOverDue);
        System.out.println("");

        Bill twelfthBill = new Bill();
        twelfthBill.billId = 12;
        twelfthBill.planType = "monthly plan";
        twelfthBill.billAmountWithTax = 450.00;
        twelfthBill.billIssueDate = "10/02/2014";
        twelfthBill.paymentMethod = "cash";
        twelfthBill.billDueDate = "20/02/2014";
        twelfthBill.isTaxInclusive = false;
        twelfthBill.isBillPaid = true;
        twelfthBill.isBillOverDue = false;
        System.out.println("the bill id is " + twelfthBill.billId);
        System.out.println("the plan type is " + twelfthBill.planType);
        System.out.println("the billAmount With Tax is " + twelfthBill.billAmountWithTax);
        System.out.println("the issue date is " + twelfthBill.billIssueDate);
        System.out.println("the paymentMethod is " + twelfthBill.paymentMethod);
        System.out.println("the due date is " + twelfthBill.billDueDate);
        System.out.println("is tax included " + twelfthBill.isTaxInclusive);
        System.out.println("is bill paid " + twelfthBill.isBillPaid);
        System.out.println("is bill over due " + twelfthBill.isBillOverDue);
        System.out.println("");

        Bill thirteenthBill = new Bill();
        thirteenthBill.billId = 13;
        thirteenthBill.planType = "quarterly plan";
        thirteenthBill.billAmountWithTax = 1350.00;
        thirteenthBill.billIssueDate = "05/03/2015";
        thirteenthBill.paymentMethod = "UPI";
        thirteenthBill.billDueDate = "15/03/2015";
        thirteenthBill.isTaxInclusive = true;
        thirteenthBill.isBillPaid = false;
        thirteenthBill.isBillOverDue = true;
        System.out.println("the bill id is " + thirteenthBill.billId);
        System.out.println("the plan type is " + thirteenthBill.planType);
        System.out.println("the billAmount With Tax is " + thirteenthBill.billAmountWithTax);
        System.out.println("the issue date is " + thirteenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + thirteenthBill.paymentMethod);
        System.out.println("the due date is " + thirteenthBill.billDueDate);
        System.out.println("is tax included " + thirteenthBill.isTaxInclusive);
        System.out.println("is bill paid " + thirteenthBill.isBillPaid);
        System.out.println("is bill over due " + thirteenthBill.isBillOverDue);
        System.out.println("");

        Bill fourteenthBill = new Bill();
        fourteenthBill.billId = 14;
        fourteenthBill.planType = "monthly plan";
        fourteenthBill.billAmountWithTax = 410.00;
        fourteenthBill.billIssueDate = "18/06/2016";
        fourteenthBill.paymentMethod = "debit card";
        fourteenthBill.billDueDate = "28/06/2016";
        fourteenthBill.isTaxInclusive = true;
        fourteenthBill.isBillPaid = true;
        fourteenthBill.isBillOverDue = false;
        System.out.println("the bill id is " + fourteenthBill.billId);
        System.out.println("the plan type is " + fourteenthBill.planType);
        System.out.println("the billAmount With Tax is " + fourteenthBill.billAmountWithTax);
        System.out.println("the issue date is " + fourteenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + fourteenthBill.paymentMethod);
        System.out.println("the due date is " + fourteenthBill.billDueDate);
        System.out.println("is tax included " + fourteenthBill.isTaxInclusive);
        System.out.println("is bill paid " + fourteenthBill.isBillPaid);
        System.out.println("is bill over due " + fourteenthBill.isBillOverDue);
        System.out.println("");

        Bill fifteenthBill = new Bill();
        fifteenthBill.billId = 15;
        fifteenthBill.planType = "half-yearly plan";
        fifteenthBill.billAmountWithTax = 2599.99;
        fifteenthBill.billIssueDate = "02/09/2017";
        fifteenthBill.paymentMethod = "credit card";
        fifteenthBill.billDueDate = "12/09/2017";
        fifteenthBill.isTaxInclusive = true;
        fifteenthBill.isBillPaid = false;
        fifteenthBill.isBillOverDue = true;
        System.out.println("the bill id is " + fifteenthBill.billId);
        System.out.println("the plan type is " + fifteenthBill.planType);
        System.out.println("the billAmount With Tax is " + fifteenthBill.billAmountWithTax);
        System.out.println("the issue date is " + fifteenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + fifteenthBill.paymentMethod);
        System.out.println("the due date is " + fifteenthBill.billDueDate);
        System.out.println("is tax included " + fifteenthBill.isTaxInclusive);
        System.out.println("is bill paid " + fifteenthBill.isBillPaid);
        System.out.println("is bill over due " + fifteenthBill.isBillOverDue);
        System.out.println("");

        Bill sixteenthBill = new Bill();
        sixteenthBill.billId = 16;
        sixteenthBill.planType = "monthly plan";
        sixteenthBill.billAmountWithTax = 430.50;
        sixteenthBill.billIssueDate = "10/10/2018";
        sixteenthBill.paymentMethod = "netbanking";
        sixteenthBill.billDueDate = "20/10/2018";
        sixteenthBill.isTaxInclusive = true;
        sixteenthBill.isBillPaid = true;
        sixteenthBill.isBillOverDue = false;
        System.out.println("the bill id is " + sixteenthBill.billId);
        System.out.println("the plan type is " + sixteenthBill.planType);
        System.out.println("the billAmount With Tax is " + sixteenthBill.billAmountWithTax);
        System.out.println("the issue date is " + sixteenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + sixteenthBill.paymentMethod);
        System.out.println("the due date is " + sixteenthBill.billDueDate);
        System.out.println("is tax included " + sixteenthBill.isTaxInclusive);
        System.out.println("is bill paid " + sixteenthBill.isBillPaid);
        System.out.println("is bill over due " + sixteenthBill.isBillOverDue);
        System.out.println("");

        Bill seventeenthBill = new Bill();
        seventeenthBill.billId = 17;
        seventeenthBill.planType = "yearly plan";
        seventeenthBill.billAmountWithTax = 6099.99;
        seventeenthBill.billIssueDate = "12/12/2019";
        seventeenthBill.paymentMethod = "UPI";
        seventeenthBill.billDueDate = "22/12/2019";
        seventeenthBill.isTaxInclusive = true;
        seventeenthBill.isBillPaid = false;
        seventeenthBill.isBillOverDue = true;
        System.out.println("the bill id is " + seventeenthBill.billId);
        System.out.println("the plan type is " + seventeenthBill.planType);
        System.out.println("the billAmount With Tax is " + seventeenthBill.billAmountWithTax);
        System.out.println("the issue date is " + seventeenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + seventeenthBill.paymentMethod);
        System.out.println("the due date is " + seventeenthBill.billDueDate);
        System.out.println("is tax included " + seventeenthBill.isTaxInclusive);
        System.out.println("is bill paid " + seventeenthBill.isBillPaid);
        System.out.println("is bill over due " + seventeenthBill.isBillOverDue);
        System.out.println("");

        Bill eighteenthBill = new Bill();
        eighteenthBill.billId = 18;
        eighteenthBill.planType = "quarterly plan";
        eighteenthBill.billAmountWithTax = 1450.00;
        eighteenthBill.billIssueDate = "15/03/2020";
        eighteenthBill.paymentMethod = "cash";
        eighteenthBill.billDueDate = "25/03/2020";
        eighteenthBill.isTaxInclusive = false;
        eighteenthBill.isBillPaid = true;
        eighteenthBill.isBillOverDue = false;
        System.out.println("the bill id is " + eighteenthBill.billId);
        System.out.println("the plan type is " + eighteenthBill.planType);
        System.out.println("the billAmount With Tax is " + eighteenthBill.billAmountWithTax);
        System.out.println("the issue date is " + eighteenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + eighteenthBill.paymentMethod);
        System.out.println("the due date is " + eighteenthBill.billDueDate);
        System.out.println("is tax included " + eighteenthBill.isTaxInclusive);
        System.out.println("is bill paid " + eighteenthBill.isBillPaid);
        System.out.println("is bill over due " + eighteenthBill.isBillOverDue);
        System.out.println("");

        Bill nineteenthBill = new Bill();
        nineteenthBill.billId = 19;
        nineteenthBill.planType = "monthly plan";
        nineteenthBill.billAmountWithTax = 470.00;
        nineteenthBill.billIssueDate = "20/06/2021";
        nineteenthBill.paymentMethod = "debit card";
        nineteenthBill.billDueDate = "30/06/2021";
        nineteenthBill.isTaxInclusive = true;
        nineteenthBill.isBillPaid = false;
        nineteenthBill.isBillOverDue = true;
        System.out.println("the bill id is " + nineteenthBill.billId);
        System.out.println("the plan type is " + nineteenthBill.planType);
        System.out.println("the billAmount With Tax is " + nineteenthBill.billAmountWithTax);
        System.out.println("the issue date is " + nineteenthBill.billIssueDate);
        System.out.println("the paymentMethod is " + nineteenthBill.paymentMethod);
        System.out.println("the due date is " + nineteenthBill.billDueDate);
        System.out.println("is tax included " + nineteenthBill.isTaxInclusive);
        System.out.println("is bill paid " + nineteenthBill.isBillPaid);
        System.out.println("is bill over due " + nineteenthBill.isBillOverDue);
        System.out.println("");

        Bill twentiethBill = new Bill();
        twentiethBill.billId = 20;
        twentiethBill.planType = "half-yearly plan";
        twentiethBill.billAmountWithTax = 2799.99;
        twentiethBill.billIssueDate = "10/11/2022";
        twentiethBill.paymentMethod = "credit card";
        twentiethBill.billDueDate = "20/11/2022";
        twentiethBill.isTaxInclusive = true;
        twentiethBill.isBillPaid = true;
        twentiethBill.isBillOverDue = false;
        System.out.println("the bill id is " + twentiethBill.billId);
        System.out.println("the plan type is " + twentiethBill.planType);
        System.out.println("the billAmount With Tax is " + twentiethBill.billAmountWithTax);
        System.out.println("the issue date is " + twentiethBill.billIssueDate);
        System.out.println("the paymentMethod is " + twentiethBill.paymentMethod);
        System.out.println("the due date is " + twentiethBill.billDueDate);
        System.out.println("is tax included " + twentiethBill.isTaxInclusive);
        System.out.println("is bill paid " + twentiethBill.isBillPaid);
        System.out.println("is bill over due " + twentiethBill.isBillOverDue);
        System.out.println("");
	System.out.println("MAIN ENDED");
	}
}