class BladeRunner {

    public static void main(String knife[]) {
        System.out.println("MAIN STARTED");

        Blade blade1 = new Blade();
        blade1.type = "Chef's Knife";
        blade1.material = "Stainless Steel";
        blade1.brand = "Victorinox";
        blade1.price = 1999.99f;
        blade1.length = 8;
        blade1.handleMaterial = "Wood";
        System.out.println("TYPE : " + blade1.type);
        System.out.println("MATERIAL : " + blade1.material);
        System.out.println("BRAND : " + blade1.brand);
        System.out.println("PRICE : " + blade1.price);
        System.out.println("LENGTH : " + blade1.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade1.handleMaterial);
	System.out.println(" ");

        Blade blade2 = new Blade();
        blade2.type = "Utility Knife";
        blade2.material = "Carbon Steel";
        blade2.brand = "Wüsthof";
        blade2.price = 1599.50f;
        blade2.length = 6;
        blade2.handleMaterial = "Plastic";
        System.out.println("TYPE : " + blade2.type);
        System.out.println("MATERIAL : " + blade2.material);
        System.out.println("BRAND : " + blade2.brand);
        System.out.println("PRICE : " + blade2.price);
        System.out.println("LENGTH : " + blade2.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade2.handleMaterial);
	System.out.println(" ");

        Blade blade3 = new Blade();
        blade3.type = "Paring Knife";
        blade3.material = "Damascus Steel";
        blade3.brand = "Shun";
        blade3.price = 2999.00f;
        blade3.length = 4;
        blade3.handleMaterial = "Pakkawood";
        System.out.println("TYPE : " + blade3.type);
        System.out.println("MATERIAL : " + blade3.material);
        System.out.println("BRAND : " + blade3.brand);
        System.out.println("PRICE : " + blade3.price);
        System.out.println("LENGTH : " + blade3.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade3.handleMaterial);
	System.out.println(" ");

        Blade blade4 = new Blade();
        blade4.type = "Bread Knife";
        blade4.material = "Stainless Steel";
        blade4.brand = "Henckels";
        blade4.price = 2299.75f;
        blade4.length = 9;
        blade4.handleMaterial = "Resin";
        System.out.println("TYPE : " + blade4.type);
        System.out.println("MATERIAL : " + blade4.material);
        System.out.println("BRAND : " + blade4.brand);
        System.out.println("PRICE : " + blade4.price);
        System.out.println("LENGTH : " + blade4.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade4.handleMaterial);
	System.out.println(" ");

        Blade blade5 = new Blade();
        blade5.type = "Boning Knife";
        blade5.material = "High Carbon Steel";
        blade5.brand = "Global";
        blade5.price = 2799.25f;
        blade5.length = 6;
        blade5.handleMaterial = "Metal";
        System.out.println("TYPE : " + blade5.type);
        System.out.println("MATERIAL : " + blade5.material);
        System.out.println("BRAND : " + blade5.brand);
        System.out.println("PRICE : " + blade5.price);
        System.out.println("LENGTH : " + blade5.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade5.handleMaterial);
	System.out.println(" ");

        Blade blade6 = new Blade();
        blade6.type = "Santoku Knife";
        blade6.material = "Japanese Steel";
        blade6.brand = "Kai";
        blade6.price = 3499.00f;
        blade6.length = 7;
        blade6.handleMaterial = "Pakkawood";
        System.out.println("TYPE : " + blade6.type);
        System.out.println("MATERIAL : " + blade6.material);
        System.out.println("BRAND : " + blade6.brand);
        System.out.println("PRICE : " + blade6.price);
        System.out.println("LENGTH : " + blade6.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade6.handleMaterial);
	System.out.println(" ");

        Blade blade7 = new Blade();
        blade7.type = "Fillet Knife";
        blade7.material = "Stainless Steel";
        blade7.brand = "Mercer";
        blade7.price = 1799.90f;
        blade7.length = 7;
        blade7.handleMaterial = "Plastic";
        System.out.println("TYPE : " + blade7.type);
        System.out.println("MATERIAL : " + blade7.material);
        System.out.println("BRAND : " + blade7.brand);
        System.out.println("PRICE : " + blade7.price);
        System.out.println("LENGTH : " + blade7.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade7.handleMaterial);
	System.out.println(" ");

        Blade blade8 = new Blade();
        blade8.type = "Carving Knife";
        blade8.material = "Carbon Steel";
        blade8.brand = "Messermeister";
        blade8.price = 3199.99f;
        blade8.length = 10;
        blade8.handleMaterial = "Wood";
        System.out.println("TYPE : " + blade8.type);
        System.out.println("MATERIAL : " + blade8.material);
        System.out.println("BRAND : " + blade8.brand);
        System.out.println("PRICE : " + blade8.price);
        System.out.println("LENGTH : " + blade8.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade8.handleMaterial);
	System.out.println(" ");

        Blade blade9 = new Blade();
        blade9.type = "Steak Knife";
        blade9.material = "Stainless Steel";
        blade9.brand = "Zwilling";
        blade9.price = 2499.49f;
        blade9.length = 5;
        blade9.handleMaterial = "Resin";
        System.out.println("TYPE : " + blade9.type);
        System.out.println("MATERIAL : " + blade9.material);
        System.out.println("BRAND : " + blade9.brand);
        System.out.println("PRICE : " + blade9.price);
        System.out.println("LENGTH : " + blade9.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade9.handleMaterial);
	System.out.println(" ");

        Blade blade10 = new Blade();
        blade10.type = "Cleaver";
        blade10.material = "High Carbon Steel";
        blade10.brand = "Dexter Russell";
        blade10.price = 3999.79f;
        blade10.length = 7;
        blade10.handleMaterial = "Wood";
        System.out.println("TYPE : " + blade10.type);
        System.out.println("MATERIAL : " + blade10.material);
        System.out.println("BRAND : " + blade10.brand);
        System.out.println("PRICE : " + blade10.price);
        System.out.println("LENGTH : " + blade10.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade10.handleMaterial);
	System.out.println(" ");

        Blade blade11 = new Blade();
        blade11.type = "Nakiri";
        blade11.material = "Japanese Steel";
        blade11.brand = "Tojiro";
        blade11.price = 4599.00f;
        blade11.length = 6;
        blade11.handleMaterial = "Pakkawood";
        System.out.println("TYPE : " + blade11.type);
        System.out.println("MATERIAL : " + blade11.material);
        System.out.println("BRAND : " + blade11.brand);
        System.out.println("PRICE : " + blade11.price);
        System.out.println("LENGTH : " + blade11.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade11.handleMaterial);
	System.out.println(" ");

        Blade blade12 = new Blade();
        blade12.type = "Slicing Knife";
        blade12.material = "Stainless Steel";
        blade12.brand = "F. Dick";
        blade12.price = 2899.45f;
        blade12.length = 12;
        blade12.handleMaterial = "Plastic";
        System.out.println("TYPE : " + blade12.type);
        System.out.println("MATERIAL : " + blade12.material);
        System.out.println("BRAND : " + blade12.brand);
        System.out.println("PRICE : " + blade12.price);
        System.out.println("LENGTH : " + blade12.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade12.handleMaterial);
	System.out.println(" ");

        Blade blade13 = new Blade();
        blade13.type = "Butcher Knife";
        blade13.material = "Carbon Steel";
        blade13.brand = "Old Hickory";
        blade13.price = 2399.99f;
        blade13.length = 8;
        blade13.handleMaterial = "Wood";
        System.out.println("TYPE : " + blade13.type);
        System.out.println("MATERIAL : " + blade13.material);
        System.out.println("BRAND : " + blade13.brand);
        System.out.println("PRICE : " + blade13.price);
        System.out.println("LENGTH : " + blade13.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade13.handleMaterial);
	System.out.println(" ");

        Blade blade14 = new Blade();
        blade14.type = "Deba";
        blade14.material = "Japanese Steel";
        blade14.brand = "Yoshihiro";
        blade14.price = 5999.10f;
        blade14.length = 7;
        blade14.handleMaterial = "Wood";
        System.out.println("TYPE : " + blade14.type);
        System.out.println("MATERIAL : " + blade14.material);
        System.out.println("BRAND : " + blade14.brand);
        System.out.println("PRICE : " + blade14.price);
        System.out.println("LENGTH : " + blade14.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade14.handleMaterial);
	System.out.println(" ");

        Blade blade15 = new Blade();
        blade15.type = "Hunting Knife";
        blade15.material = "Stainless Steel";
        blade15.brand = "Buck Knives";
        blade15.price = 3699.20f;
        blade15.length = 5;
        blade15.handleMaterial = "Micarta";
        System.out.println("TYPE : " + blade15.type);
        System.out.println("MATERIAL : " + blade15.material);
        System.out.println("BRAND : " + blade15.brand);
        System.out.println("PRICE : " + blade15.price);
        System.out.println("LENGTH : " + blade15.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade15.handleMaterial);
	System.out.println(" ");

        Blade blade16 = new Blade();
        blade16.type = "Survival Knife";
        blade16.material = "High Carbon Steel";
        blade16.brand = "Gerber";
        blade16.price = 4999.30f;
        blade16.length = 6;
        blade16.handleMaterial = "Rubber";
        System.out.println("TYPE : " + blade16.type);
        System.out.println("MATERIAL : " + blade16.material);
        System.out.println("BRAND : " + blade16.brand);
        System.out.println("PRICE : " + blade16.price);
        System.out.println("LENGTH : " + blade16.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade16.handleMaterial);
	System.out.println(" ");

        Blade blade17 = new Blade();
        blade17.type = "Pocket Knife";
        blade17.material = "Stainless Steel";
        blade17.brand = "Victorinox";
        blade17.price = 2199.99f;
        blade17.length = 4;
        blade17.handleMaterial = "Plastic";
        System.out.println("TYPE : " + blade17.type);
        System.out.println("MATERIAL : " + blade17.material);
        System.out.println("BRAND : " + blade17.brand);
        System.out.println("PRICE : " + blade17.price);
        System.out.println("LENGTH : " + blade17.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade17.handleMaterial);
	System.out.println(" ");

        Blade blade18 = new Blade();
        blade18.type = "Throwing Knife";
        blade18.material = "Carbon Steel";
        blade18.brand = "SOG";
        blade18.price = 2699.00f;
        blade18.length = 7;
        blade18.handleMaterial = "Steel";
        System.out.println("TYPE : " + blade18.type);
        System.out.println("MATERIAL : " + blade18.material);
        System.out.println("BRAND : " + blade18.brand);
        System.out.println("PRICE : " + blade18.price);
        System.out.println("LENGTH : " + blade18.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade18.handleMaterial);
	System.out.println(" ");

        Blade blade19 = new Blade();
        blade19.type = "Combat Knife";
        blade19.material = "High Carbon Steel";
        blade19.brand = "Ka-Bar";
        blade19.price = 5999.60f;
        blade19.length = 7;
        blade19.handleMaterial = "Leather";
        System.out.println("TYPE : " + blade19.type);
        System.out.println("MATERIAL : " + blade19.material);
        System.out.println("BRAND : " + blade19.brand);
        System.out.println("PRICE : " + blade19.price);
        System.out.println("LENGTH : " + blade19.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade19.handleMaterial);
	System.out.println(" ");

        Blade blade20 = new Blade();
        blade20.type = "Machete";
        blade20.material = "Carbon Steel";
        blade20.brand = "Cold Steel";
        blade20.price = 6499.40f;
        blade20.length = 18;
        blade20.handleMaterial = "Plastic";
        System.out.println("TYPE : " + blade20.type);
        System.out.println("MATERIAL : " + blade20.material);
        System.out.println("BRAND : " + blade20.brand);
        System.out.println("PRICE : " + blade20.price);
        System.out.println("LENGTH : " + blade20.length + " inches");
        System.out.println("HANDLE MATERIAL : " + blade20.handleMaterial);
	System.out.println(" ");

        System.out.println("MAIN ENDED");
    }
}
