class BlazerRunner {

    public static void main(String jacket[]) {
        System.out.println("MAIN STARTED");

        Blazer blazer1 = new Blazer();
        blazer1.color = "NAVY BLUE";
        blazer1.fabric = "HOPSACK";
        blazer1.style = "Single-breasted";
        blazer1.price = 7999.99f;
        blazer1.noOfButtons = 3;
        blazer1.size = "XL";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer1.color);
        System.out.println("FABRIC : " + blazer1.fabric);
        System.out.println("STYLE : " + blazer1.style);
        System.out.println("PRICE : " + blazer1.price);
        System.out.println("NO OF BUTTONS : " + blazer1.noOfButtons);
        System.out.println("SIZE : " + blazer1.size);

        Blazer blazer2 = new Blazer();
        blazer2.color = "BLACK";
        blazer2.fabric = "WOOL";
        blazer2.style = "Double-breasted";
        blazer2.price = 8999.50f;
        blazer2.noOfButtons = 4;
        blazer2.size = "L";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer2.color);
        System.out.println("FABRIC : " + blazer2.fabric);
        System.out.println("STYLE : " + blazer2.style);
        System.out.println("PRICE : " + blazer2.price);
        System.out.println("NO OF BUTTONS : " + blazer2.noOfButtons);
        System.out.println("SIZE : " + blazer2.size);

        Blazer blazer3 = new Blazer();
        blazer3.color = "GREY";
        blazer3.fabric = "TWEED";
        blazer3.style = "Single-breasted";
        blazer3.price = 7599.00f;
        blazer3.noOfButtons = 2;
        blazer3.size = "M";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer3.color);
        System.out.println("FABRIC : " + blazer3.fabric);
        System.out.println("STYLE : " + blazer3.style);
        System.out.println("PRICE : " + blazer3.price);
        System.out.println("NO OF BUTTONS : " + blazer3.noOfButtons);
        System.out.println("SIZE : " + blazer3.size);

        Blazer blazer4 = new Blazer();
        blazer4.color = "BROWN";
        blazer4.fabric = "COTTON";
        blazer4.style = "Single-breasted";
        blazer4.price = 6999.25f;
        blazer4.noOfButtons = 3;
        blazer4.size = "S";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer4.color);
        System.out.println("FABRIC : " + blazer4.fabric);
        System.out.println("STYLE : " + blazer4.style);
        System.out.println("PRICE : " + blazer4.price);
        System.out.println("NO OF BUTTONS : " + blazer4.noOfButtons);
        System.out.println("SIZE : " + blazer4.size);

        Blazer blazer5 = new Blazer();
        blazer5.color = "WHITE";
        blazer5.fabric = "LINEN";
        blazer5.style = "Single-breasted";
        blazer5.price = 8499.75f;
        blazer5.noOfButtons = 2;
        blazer5.size = "L";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer5.color);
        System.out.println("FABRIC : " + blazer5.fabric);
        System.out.println("STYLE : " + blazer5.style);
        System.out.println("PRICE : " + blazer5.price);
        System.out.println("NO OF BUTTONS : " + blazer5.noOfButtons);
        System.out.println("SIZE : " + blazer5.size);

        Blazer blazer6 = new Blazer();
        blazer6.color = "OLIVE GREEN";
        blazer6.fabric = "WOOL BLEND";
        blazer6.style = "Double-breasted";
        blazer6.price = 9999.00f;
        blazer6.noOfButtons = 4;
        blazer6.size = "XL";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer6.color);
        System.out.println("FABRIC : " + blazer6.fabric);
        System.out.println("STYLE : " + blazer6.style);
        System.out.println("PRICE : " + blazer6.price);
        System.out.println("NO OF BUTTONS : " + blazer6.noOfButtons);
        System.out.println("SIZE : " + blazer6.size);

        Blazer blazer7 = new Blazer();
        blazer7.color = "BEIGE";
        blazer7.fabric = "LINEN BLEND";
        blazer7.style = "Single-breasted";
        blazer7.price = 6799.90f;
        blazer7.noOfButtons = 3;
        blazer7.size = "M";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer7.color);
        System.out.println("FABRIC : " + blazer7.fabric);
        System.out.println("STYLE : " + blazer7.style);
        System.out.println("PRICE : " + blazer7.price);
        System.out.println("NO OF BUTTONS : " + blazer7.noOfButtons);
        System.out.println("SIZE : " + blazer7.size);

        Blazer blazer8 = new Blazer();
        blazer8.color = "MAROON";
        blazer8.fabric = "VELVET";
        blazer8.style = "Single-breasted";
        blazer8.price = 12999.99f;
        blazer8.noOfButtons = 2;
        blazer8.size = "L";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer8.color);
        System.out.println("FABRIC : " + blazer8.fabric);
        System.out.println("STYLE : " + blazer8.style);
        System.out.println("PRICE : " + blazer8.price);
        System.out.println("NO OF BUTTONS : " + blazer8.noOfButtons);
        System.out.println("SIZE : " + blazer8.size);

        Blazer blazer9 = new Blazer();
        blazer9.color = "DARK GREY";
        blazer9.fabric = "WOOL";
        blazer9.style = "Double-breasted";
        blazer9.price = 8799.49f;
        blazer9.noOfButtons = 4;
        blazer9.size = "XL";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer9.color);
        System.out.println("FABRIC : " + blazer9.fabric);
        System.out.println("STYLE : " + blazer9.style);
        System.out.println("PRICE : " + blazer9.price);
        System.out.println("NO OF BUTTONS : " + blazer9.noOfButtons);
        System.out.println("SIZE : " + blazer9.size);

        Blazer blazer10 = new Blazer();
        blazer10.color = "LIGHT GREY";
        blazer10.fabric = "COTTON";
        blazer10.style = "Single-breasted";
        blazer10.price = 7599.79f;
        blazer10.noOfButtons = 2;
        blazer10.size = "S";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer10.color);
        System.out.println("FABRIC : " + blazer10.fabric);
        System.out.println("STYLE : " + blazer10.style);
        System.out.println("PRICE : " + blazer10.price);
        System.out.println("NO OF BUTTONS : " + blazer10.noOfButtons);
        System.out.println("SIZE : " + blazer10.size);

        Blazer blazer11 = new Blazer();
        blazer11.color = "CHARCOAL";
        blazer11.fabric = "WOOL";
        blazer11.style = "Double-breasted";
        blazer11.price = 9499.00f;
        blazer11.noOfButtons = 3;
        blazer11.size = "M";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer11.color);
        System.out.println("FABRIC : " + blazer11.fabric);
        System.out.println("STYLE : " + blazer11.style);
        System.out.println("PRICE : " + blazer11.price);
        System.out.println("NO OF BUTTONS : " + blazer11.noOfButtons);
        System.out.println("SIZE : " + blazer11.size);

        Blazer blazer12 = new Blazer();
        blazer12.color = "TEAL BLUE";
        blazer12.fabric = "LINEN";
        blazer12.style = "Single-breasted";
        blazer12.price = 8399.45f;
        blazer12.noOfButtons = 2;
        blazer12.size = "XL";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer12.color);
        System.out.println("FABRIC : " + blazer12.fabric);
        System.out.println("STYLE : " + blazer12.style);
        System.out.println("PRICE : " + blazer12.price);
        System.out.println("NO OF BUTTONS : " + blazer12.noOfButtons);
        System.out.println("SIZE : " + blazer12.size);

        Blazer blazer13 = new Blazer();
        blazer13.color = "DARK BROWN";
        blazer13.fabric = "TWEED";
        blazer13.style = "Single-breasted";
        blazer13.price = 7299.99f;
        blazer13.noOfButtons = 2;
        blazer13.size = "L";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer13.color);
        System.out.println("FABRIC : " + blazer13.fabric);
        System.out.println("STYLE : " + blazer13.style);
        System.out.println("PRICE : " + blazer13.price);
        System.out.println("NO OF BUTTONS : " + blazer13.noOfButtons);
        System.out.println("SIZE : " + blazer13.size);

        Blazer blazer14 = new Blazer();
        blazer14.color = "KHAKI";
        blazer14.fabric = "COTTON BLEND";
        blazer14.style = "Single-breasted";
        blazer14.price = 6799.10f;
        blazer14.noOfButtons = 3;
        blazer14.size = "M";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer14.color);
        System.out.println("FABRIC : " + blazer14.fabric);
        System.out.println("STYLE : " + blazer14.style);
        System.out.println("PRICE : " + blazer14.price);
        System.out.println("NO OF BUTTONS : " + blazer14.noOfButtons);
        System.out.println("SIZE : " + blazer14.size);

        Blazer blazer15 = new Blazer();
        blazer15.color = "CREAM";
        blazer15.fabric = "LINEN";
        blazer15.style = "Single-breasted";
        blazer15.price = 8499.20f;
        blazer15.noOfButtons = 2;
        blazer15.size = "S";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer15.color);
        System.out.println("FABRIC : " + blazer15.fabric);
        System.out.println("STYLE : " + blazer15.style);
        System.out.println("PRICE : " + blazer15.price);
        System.out.println("NO OF BUTTONS : " + blazer15.noOfButtons);
        System.out.println("SIZE : " + blazer15.size);

        Blazer blazer16 = new Blazer();
        blazer16.color = "BURGUNDY";
        blazer16.fabric = "WOOL";
        blazer16.style = "Double-breasted";
        blazer16.price = 9599.30f;
        blazer16.noOfButtons = 4;
        blazer16.size = "L";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer16.color);
        System.out.println("FABRIC : " + blazer16.fabric);
        System.out.println("STYLE : " + blazer16.style);
        System.out.println("PRICE : " + blazer16.price);
        System.out.println("NO OF BUTTONS : " + blazer16.noOfButtons);
        System.out.println("SIZE : " + blazer16.size);

        Blazer blazer17 = new Blazer();
        blazer17.color = "DARK NAVY";
        blazer17.fabric = "WOOL";
        blazer17.style = "Single-breasted";
        blazer17.price = 8999.99f;
        blazer17.noOfButtons = 3;
        blazer17.size = "XL";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer17.color);
        System.out.println("FABRIC : " + blazer17.fabric);
        System.out.println("STYLE : " + blazer17.style);
        System.out.println("PRICE : " + blazer17.price);
        System.out.println("NO OF BUTTONS : " + blazer17.noOfButtons);
        System.out.println("SIZE : " + blazer17.size);

        Blazer blazer18 = new Blazer();
        blazer18.color = "FOREST GREEN";
        blazer18.fabric = "LINEN";
        blazer18.style = "Single-breasted";
        blazer18.price = 7899.00f;
        blazer18.noOfButtons = 2;
        blazer18.size = "M";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer18.color);
        System.out.println("FABRIC : " + blazer18.fabric);
        System.out.println("STYLE : " + blazer18.style);
        System.out.println("PRICE : " + blazer18.price);
        System.out.println("NO OF BUTTONS : " + blazer18.noOfButtons);
        System.out.println("SIZE : " + blazer18.size);

        Blazer blazer19 = new Blazer();
        blazer19.color = "ROYAL BLUE";
        blazer19.fabric = "COTTON";
        blazer19.style = "Single-breasted";
        blazer19.price = 7199.60f;
        blazer19.noOfButtons = 2;
        blazer19.size = "S";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer19.color);
        System.out.println("FABRIC : " + blazer19.fabric);
        System.out.println("STYLE : " + blazer19.style);
        System.out.println("PRICE : " + blazer19.price);
        System.out.println("NO OF BUTTONS : " + blazer19.noOfButtons);
        System.out.println("SIZE : " + blazer19.size);

        Blazer blazer20 = new Blazer();
        blazer20.color = "STEEL GREY";
        blazer20.fabric = "WOOL BLEND";
        blazer20.style = "Double-breasted";
        blazer20.price = 9699.40f;
        blazer20.noOfButtons = 4;
        blazer20.size = "XL";
	System.out.println(" ");
        System.out.println("COLOR : " + blazer20.color);
        System.out.println("FABRIC : " + blazer20.fabric);
        System.out.println("STYLE : " + blazer20.style);
        System.out.println("PRICE : " + blazer20.price);
        System.out.println("NO OF BUTTONS : " + blazer20.noOfButtons);
        System.out.println("SIZE : " + blazer20.size);

        System.out.println("MAIN ENDED");
    }
}
