class CoinsRunner {

    public static void main(String coin[]) {
        System.out.println("MAIN STARTED");

        Coins coin1 = new Coins();
        coin1.name = "Indian 1 Rupee";
        coin1.country = "India";
        coin1.material = "Stainless Steel";
        coin1.value = 1.0f;
        coin1.year = 2022;
        coin1.weight = 4.85f;
        System.out.println("NAME : " + coin1.name);
        System.out.println("COUNTRY : " + coin1.country);
        System.out.println("MATERIAL : " + coin1.material);
        System.out.println("VALUE : " + coin1.value);
        System.out.println("YEAR : " + coin1.year);
        System.out.println("WEIGHT : " + coin1.weight + " g");

        Coins coin2 = new Coins();
        coin2.name = "Indian 2 Rupees";
        coin2.country = "India";
        coin2.material = "Stainless Steel";
        coin2.value = 2.0f;
        coin2.year = 2020;
        coin2.weight = 4.5f;
        System.out.println("NAME : " + coin2.name);
        System.out.println("COUNTRY : " + coin2.country);
        System.out.println("MATERIAL : " + coin2.material);
        System.out.println("VALUE : " + coin2.value);
        System.out.println("YEAR : " + coin2.year);
        System.out.println("WEIGHT : " + coin2.weight + " g");

        Coins coin3 = new Coins();
        coin3.name = "Indian 5 Rupees";
        coin3.country = "India";
        coin3.material = "Nickel Brass";
        coin3.value = 5.0f;
        coin3.year = 2018;
        coin3.weight = 6.0f;
        System.out.println("NAME : " + coin3.name);
        System.out.println("COUNTRY : " + coin3.country);
        System.out.println("MATERIAL : " + coin3.material);
        System.out.println("VALUE : " + coin3.value);
        System.out.println("YEAR : " + coin3.year);
        System.out.println("WEIGHT : " + coin3.weight + " g");

        Coins coin4 = new Coins();
        coin4.name = "Indian 10 Rupees";
        coin4.country = "India";
        coin4.material = "Bimetallic";
        coin4.value = 10.0f;
        coin4.year = 2021;
        coin4.weight = 7.7f;
        System.out.println("NAME : " + coin4.name);
        System.out.println("COUNTRY : " + coin4.country);
        System.out.println("MATERIAL : " + coin4.material);
        System.out.println("VALUE : " + coin4.value);
        System.out.println("YEAR : " + coin4.year);
        System.out.println("WEIGHT : " + coin4.weight + " g");

        Coins coin5 = new Coins();
        coin5.name = "US Penny";
        coin5.country = "USA";
        coin5.material = "Copper Plated Zinc";
        coin5.value = 0.01f;
        coin5.year = 2019;
        coin5.weight = 2.5f;
        System.out.println("NAME : " + coin5.name);
        System.out.println("COUNTRY : " + coin5.country);
        System.out.println("MATERIAL : " + coin5.material);
        System.out.println("VALUE : " + coin5.value);
        System.out.println("YEAR : " + coin5.year);
        System.out.println("WEIGHT : " + coin5.weight + " g");

        Coins coin6 = new Coins();
        coin6.name = "US Nickel";
        coin6.country = "USA";
        coin6.material = "Cupro-Nickel";
        coin6.value = 0.05f;
        coin6.year = 2018;
        coin6.weight = 5.0f;
        System.out.println("NAME : " + coin6.name);
        System.out.println("COUNTRY : " + coin6.country);
        System.out.println("MATERIAL : " + coin6.material);
        System.out.println("VALUE : " + coin6.value);
        System.out.println("YEAR : " + coin6.year);
        System.out.println("WEIGHT : " + coin6.weight + " g");

        Coins coin7 = new Coins();
        coin7.name = "US Dime";
        coin7.country = "USA";
        coin7.material = "Cupro-Nickel";
        coin7.value = 0.10f;
        coin7.year = 2022;
        coin7.weight = 2.27f;
        System.out.println("NAME : " + coin7.name);
        System.out.println("COUNTRY : " + coin7.country);
        System.out.println("MATERIAL : " + coin7.material);
        System.out.println("VALUE : " + coin7.value);
        System.out.println("YEAR : " + coin7.year);
        System.out.println("WEIGHT : " + coin7.weight + " g");

        Coins coin8 = new Coins();
        coin8.name = "US Quarter";
        coin8.country = "USA";
        coin8.material = "Cupro-Nickel";
        coin8.value = 0.25f;
        coin8.year = 2017;
        coin8.weight = 5.67f;
        System.out.println("NAME : " + coin8.name);
        System.out.println("COUNTRY : " + coin8.country);
        System.out.println("MATERIAL : " + coin8.material);
        System.out.println("VALUE : " + coin8.value);
        System.out.println("YEAR : " + coin8.year);
        System.out.println("WEIGHT : " + coin8.weight + " g");

        Coins coin9 = new Coins();
        coin9.name = "US Half Dollar";
        coin9.country = "USA";
        coin9.material = "Cupro-Nickel";
        coin9.value = 0.50f;
        coin9.year = 2015;
        coin9.weight = 11.34f;
        System.out.println("NAME : " + coin9.name);
        System.out.println("COUNTRY : " + coin9.country);
        System.out.println("MATERIAL : " + coin9.material);
        System.out.println("VALUE : " + coin9.value);
        System.out.println("YEAR : " + coin9.year);
        System.out.println("WEIGHT : " + coin9.weight + " g");

        Coins coin10 = new Coins();
        coin10.name = "US Dollar Coin";
        coin10.country = "USA";
        coin10.material = "Manganese-Brass";
        coin10.value = 1.0f;
        coin10.year = 2019;
        coin10.weight = 8.1f;
        System.out.println("NAME : " + coin10.name);
        System.out.println("COUNTRY : " + coin10.country);
        System.out.println("MATERIAL : " + coin10.material);
        System.out.println("VALUE : " + coin10.value);
        System.out.println("YEAR : " + coin10.year);
        System.out.println("WEIGHT : " + coin10.weight + " g");

        Coins coin11 = new Coins();
        coin11.name = "Euro 1 Cent";
        coin11.country = "European Union";
        coin11.material = "Copper Plated Steel";
        coin11.value = 0.01f;
        coin11.year = 2021;
        coin11.weight = 2.3f;
        System.out.println("NAME : " + coin11.name);
        System.out.println("COUNTRY : " + coin11.country);
        System.out.println("MATERIAL : " + coin11.material);
        System.out.println("VALUE : " + coin11.value);
        System.out.println("YEAR : " + coin11.year);
        System.out.println("WEIGHT : " + coin11.weight + " g");

        Coins coin12 = new Coins();
        coin12.name = "Euro 2 Cent";
        coin12.country = "European Union";
        coin12.material = "Copper Plated Steel";
        coin12.value = 0.02f;
        coin12.year = 2016;
        coin12.weight = 3.06f;
        System.out.println("NAME : " + coin12.name);
        System.out.println("COUNTRY : " + coin12.country);
        System.out.println("MATERIAL : " + coin12.material);
        System.out.println("VALUE : " + coin12.value);
        System.out.println("YEAR : " + coin12.year);
        System.out.println("WEIGHT : " + coin12.weight + " g");

        Coins coin13 = new Coins();
        coin13.name = "Euro 5 Cent";
        coin13.country = "European Union";
        coin13.material = "Copper Plated Steel";
        coin13.value = 0.05f;
        coin13.year = 2017;
        coin13.weight = 3.92f;
        System.out.println("NAME : " + coin13.name);
        System.out.println("COUNTRY : " + coin13.country);
        System.out.println("MATERIAL : " + coin13.material);
        System.out.println("VALUE : " + coin13.value);
        System.out.println("YEAR : " + coin13.year);
        System.out.println("WEIGHT : " + coin13.weight + " g");

        Coins coin14 = new Coins();
        coin14.name = "Euro 10 Cent";
        coin14.country = "European Union";
        coin14.material = "Nordic Gold";
        coin14.value = 0.10f;
        coin14.year = 2019;
        coin14.weight = 4.1f;
        System.out.println("NAME : " + coin14.name);
        System.out.println("COUNTRY : " + coin14.country);
        System.out.println("MATERIAL : " + coin14.material);
        System.out.println("VALUE : " + coin14.value);
        System.out.println("YEAR : " + coin14.year);
        System.out.println("WEIGHT : " + coin14.weight + " g");

        Coins coin15 = new Coins();
        coin15.name = "Euro 20 Cent";
        coin15.country = "European Union";
        coin15.material = "Nordic Gold";
        coin15.value = 0.20f;
        coin15.year = 2020;
        coin15.weight = 5.74f;
        System.out.println("NAME : " + coin15.name);
        System.out.println("COUNTRY : " + coin15.country);
        System.out.println("MATERIAL : " + coin15.material);
        System.out.println("VALUE : " + coin15.value);
        System.out.println("YEAR : " + coin15.year);
        System.out.println("WEIGHT : " + coin15.weight + " g");

        Coins coin16 = new Coins();
        coin16.name = "Euro 50 Cent";
        coin16.country = "European Union";
        coin16.material = "Nordic Gold";
        coin16.value = 0.50f;
        coin16.year = 2018;
        coin16.weight = 7.8f;
        System.out.println("NAME : " + coin16.name);
        System.out.println("COUNTRY : " + coin16.country);
        System.out.println("MATERIAL : " + coin16.material);
        System.out.println("VALUE : " + coin16.value);
        System.out.println("YEAR : " + coin16.year);
        System.out.println("WEIGHT : " + coin16.weight + " g");

        Coins coin17 = new Coins();
        coin17.name = "Euro 1";
        coin17.country = "European Union";
        coin17.material = "Bimetallic";
        coin17.value = 1.0f;
        coin17.year = 2021;
        coin17.weight = 7.5f;
        System.out.println("NAME : " + coin17.name);
        System.out.println("COUNTRY : " + coin17.country);
        System.out.println("MATERIAL : " + coin17.material);
        System.out.println("VALUE : " + coin17.value);
        System.out.println("YEAR : " + coin17.year);
        System.out.println("WEIGHT : " + coin17.weight + " g");

        Coins coin18 = new Coins();
        coin18.name = "Euro 2";
        coin18.country = "European Union";
        coin18.material = "Bimetallic";
        coin18.value = 2.0f;
        coin18.year = 2016;
        coin18.weight = 8.5f;
        System.out.println("NAME : " + coin18.name);
        System.out.println("COUNTRY : " + coin18.country);
        System.out.println("MATERIAL : " + coin18.material);
        System.out.println("VALUE : " + coin18.value);
        System.out.println("YEAR : " + coin18.year);
        System.out.println("WEIGHT : " + coin18.weight + " g");

        Coins coin19 = new Coins();
        coin19.name = "British 1 Pound";
        coin19.country = "UK";
        coin19.material = "Nickel-Brass";
        coin19.value = 1.0f;
        coin19.year = 2020;
        coin19.weight = 8.75f;
        System.out.println("NAME : " + coin19.name);
        System.out.println("COUNTRY : " + coin19.country);
        System.out.println("MATERIAL : " + coin19.material);
        System.out.println("VALUE : " + coin19.value);
        System.out.println("YEAR : " + coin19.year);
        System.out.println("WEIGHT : " + coin19.weight + " g");

        Coins coin20 = new Coins();
        coin20.name = "British 2 Pounds";
        coin20.country = "UK";
        coin20.material = "Bimetallic";
        coin20.value = 2.0f;
        coin20.year = 2018;
        coin20.weight = 12.0f;
        System.out.println("NAME : " + coin20.name);
        System.out.println("COUNTRY : " + coin20.country);
        System.out.println("MATERIAL : " + coin20.material);
        System.out.println("VALUE : " + coin20.value);
        System.out.println("YEAR : " + coin20.year);
        System.out.println("WEIGHT : " + coin20.weight + " g");

        System.out.println("MAIN ENDED");
    }
}
