class CourtCaseRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        CourtCase case1 = new CourtCase();
        case1.caseNumber = "CIV1234";
        case1.caseType = "Civil";
        case1.courtName = "Supreme Court";
        case1.judgeName = "Justice A. Verma";
        case1.plaintiff = "John Doe";
        case1.defendant = "XYZ Pvt Ltd";
        case1.isResolved = false;
        System.out.println("CASE NUMBER : " + case1.caseNumber);
        System.out.println("CASE TYPE : " + case1.caseType);
        System.out.println("COURT NAME : " + case1.courtName);
        System.out.println("JUDGE NAME : " + case1.judgeName);
        System.out.println("PLAINTIFF : " + case1.plaintiff);
        System.out.println("DEFENDANT : " + case1.defendant);
        System.out.println("IS RESOLVED : " + case1.isResolved);

        CourtCase case2 = new CourtCase();
        case2.caseNumber = "CRM5678";
        case2.caseType = "Criminal";
        case2.courtName = "High Court";
        case2.judgeName = "Justice R. Mehta";
        case2.plaintiff = "State of Karnataka";
        case2.defendant = "ABC Industries";
        case2.isResolved = true;
        System.out.println("CASE NUMBER : " + case2.caseNumber);
        System.out.println("CASE TYPE : " + case2.caseType);
        System.out.println("COURT NAME : " + case2.courtName);
        System.out.println("JUDGE NAME : " + case2.judgeName);
        System.out.println("PLAINTIFF : " + case2.plaintiff);
        System.out.println("DEFENDANT : " + case2.defendant);
        System.out.println("IS RESOLVED : " + case2.isResolved);

        CourtCase case3 = new CourtCase();
        case3.caseNumber = "FAM9012";
        case3.caseType = "Family";
        case3.courtName = "Family Court";
        case3.judgeName = "Justice K. Menon";
        case3.plaintiff = "Alice";
        case3.defendant = "Bob";
        case3.isResolved = false;
        System.out.println("CASE NUMBER : " + case3.caseNumber);
        System.out.println("CASE TYPE : " + case3.caseType);
        System.out.println("COURT NAME : " + case3.courtName);
        System.out.println("JUDGE NAME : " + case3.judgeName);
        System.out.println("PLAINTIFF : " + case3.plaintiff);
        System.out.println("DEFENDANT : " + case3.defendant);
        System.out.println("IS RESOLVED : " + case3.isResolved);

        CourtCase case4 = new CourtCase();
        case4.caseNumber = "LAB3456";
        case4.caseType = "Labor";
        case4.courtName = "District Court";
        case4.judgeName = "Justice N. Rao";
        case4.plaintiff = "Workers Union";
        case4.defendant = "LMN Textiles";
        case4.isResolved = true;
        System.out.println("CASE NUMBER : " + case4.caseNumber);
        System.out.println("CASE TYPE : " + case4.caseType);
        System.out.println("COURT NAME : " + case4.courtName);
        System.out.println("JUDGE NAME : " + case4.judgeName);
        System.out.println("PLAINTIFF : " + case4.plaintiff);
        System.out.println("DEFENDANT : " + case4.defendant);
        System.out.println("IS RESOLVED : " + case4.isResolved);

        CourtCase case5 = new CourtCase();
        case5.caseNumber = "TAX1122";
        case5.caseType = "Tax";
        case5.courtName = "Income Tax Tribunal";
        case5.judgeName = "Justice D. Kapoor";
        case5.plaintiff = "Tax Department";
        case5.defendant = "JKL Corporation";
        case5.isResolved = false;
        System.out.println("CASE NUMBER : " + case5.caseNumber);
        System.out.println("CASE TYPE : " + case5.caseType);
        System.out.println("COURT NAME : " + case5.courtName);
        System.out.println("JUDGE NAME : " + case5.judgeName);
        System.out.println("PLAINTIFF : " + case5.plaintiff);
        System.out.println("DEFENDANT : " + case5.defendant);
        System.out.println("IS RESOLVED : " + case5.isResolved);

        CourtCase case6 = new CourtCase();
        case6.caseNumber = "ENV5566";
        case6.caseType = "Environmental";
        case6.courtName = "Green Tribunal";
        case6.judgeName = "Justice S. Nair";
        case6.plaintiff = "Environment NGO";
        case6.defendant = "ABC Chemicals";
        case6.isResolved = false;
        System.out.println("CASE NUMBER : " + case6.caseNumber);
        System.out.println("CASE TYPE : " + case6.caseType);
        System.out.println("COURT NAME : " + case6.courtName);
        System.out.println("JUDGE NAME : " + case6.judgeName);
        System.out.println("PLAINTIFF : " + case6.plaintiff);
        System.out.println("DEFENDANT : " + case6.defendant);
        System.out.println("IS RESOLVED : " + case6.isResolved);

        CourtCase case7 = new CourtCase();
        case7.caseNumber = "PROP7788";
        case7.caseType = "Property";
        case7.courtName = "City Civil Court";
        case7.judgeName = "Justice R. Singh";
        case7.plaintiff = "David";
        case7.defendant = "Ethan";
        case7.isResolved = true;
        System.out.println("CASE NUMBER : " + case7.caseNumber);
        System.out.println("CASE TYPE : " + case7.caseType);
        System.out.println("COURT NAME : " + case7.courtName);
        System.out.println("JUDGE NAME : " + case7.judgeName);
        System.out.println("PLAINTIFF : " + case7.plaintiff);
        System.out.println("DEFENDANT : " + case7.defendant);
        System.out.println("IS RESOLVED : " + case7.isResolved);

        CourtCase case8 = new CourtCase();
        case8.caseNumber = "IP9988";
        case8.caseType = "Intellectual Property";
        case8.courtName = "High Court";
        case8.judgeName = "Justice K. Prasad";
        case8.plaintiff = "Tech Innovations";
        case8.defendant = "MegaSoft";
        case8.isResolved = false;
        System.out.println("CASE NUMBER : " + case8.caseNumber);
        System.out.println("CASE TYPE : " + case8.caseType);
        System.out.println("COURT NAME : " + case8.courtName);
        System.out.println("JUDGE NAME : " + case8.judgeName);
        System.out.println("PLAINTIFF : " + case8.plaintiff);
        System.out.println("DEFENDANT : " + case8.defendant);
        System.out.println("IS RESOLVED : " + case8.isResolved);

        CourtCase case9 = new CourtCase();
        case9.caseNumber = "TRADE567";
        case9.caseType = "Trade";
        case9.courtName = "Commercial Court";
        case9.judgeName = "Justice V. Iyer";
        case9.plaintiff = "XYZ Traders";
        case9.defendant = "ABC Importers";
        case9.isResolved = true;
        System.out.println("CASE NUMBER : " + case9.caseNumber);
        System.out.println("CASE TYPE : " + case9.caseType);
        System.out.println("COURT NAME : " + case9.courtName);
        System.out.println("JUDGE NAME : " + case9.judgeName);
        System.out.println("PLAINTIFF : " + case9.plaintiff);
        System.out.println("DEFENDANT : " + case9.defendant);
        System.out.println("IS RESOLVED : " + case9.isResolved);

        CourtCase case10 = new CourtCase();
        case10.caseNumber = "CIV450";
        case10.caseType = "Civil";
        case10.courtName = "Supreme Court";
        case10.judgeName = "Justice A. Malhotra";
        case10.plaintiff = "Ravi";
        case10.defendant = "Sumit";
        case10.isResolved = false;
        System.out.println("CASE NUMBER : " + case10.caseNumber);
        System.out.println("CASE TYPE : " + case10.caseType);
        System.out.println("COURT NAME : " + case10.courtName);
        System.out.println("JUDGE NAME : " + case10.judgeName);
        System.out.println("PLAINTIFF : " + case10.plaintiff);
        System.out.println("DEFENDANT : " + case10.defendant);
        System.out.println("IS RESOLVED : " + case10.isResolved);

        CourtCase case11 = new CourtCase();
        case11.caseNumber = "CRIM123";
        case11.caseType = "Criminal";
        case11.courtName = "High Court";
        case11.judgeName = "Justice V. Gowda";
        case11.plaintiff = "State of Maharashtra";
        case11.defendant = "PQR Ltd";
        case11.isResolved = false;
        System.out.println("CASE NUMBER : " + case11.caseNumber);
        System.out.println("CASE TYPE : " + case11.caseType);
        System.out.println("COURT NAME : " + case11.courtName);
        System.out.println("JUDGE NAME : " + case11.judgeName);
        System.out.println("PLAINTIFF : " + case11.plaintiff);
        System.out.println("DEFENDANT : " + case11.defendant);
        System.out.println("IS RESOLVED : " + case11.isResolved);

        CourtCase case12 = new CourtCase();
        case12.caseNumber = "LAB789";
        case12.caseType = "Labor";
        case12.courtName = "District Court";
        case12.judgeName = "Justice J. Reddy";
        case12.plaintiff = "Workers Group";
        case12.defendant = "Textile Corp";
        case12.isResolved = true;
        System.out.println("CASE NUMBER : " + case12.caseNumber);
        System.out.println("CASE TYPE : " + case12.caseType);
        System.out.println("COURT NAME : " + case12.courtName);
        System.out.println("JUDGE NAME : " + case12.judgeName);
        System.out.println("PLAINTIFF : " + case12.plaintiff);
        System.out.println("DEFENDANT : " + case12.defendant);
        System.out.println("IS RESOLVED : " + case12.isResolved);

        CourtCase case13 = new CourtCase();
        case13.caseNumber = "TAX321";
        case13.caseType = "Tax";
        case13.courtName = "Income Tax Tribunal";
        case13.judgeName = "Justice A. Patel";
        case13.plaintiff = "Income Tax Dept";
        case13.defendant = "XYZ Finance";
        case13.isResolved = false;
        System.out.println("CASE NUMBER : " + case13.caseNumber);
        System.out.println("CASE TYPE : " + case13.caseType);
        System.out.println("COURT NAME : " + case13.courtName);
        System.out.println("JUDGE NAME : " + case13.judgeName);
        System.out.println("PLAINTIFF : " + case13.plaintiff);
        System.out.println("DEFENDANT : " + case13.defendant);
        System.out.println("IS RESOLVED : " + case13.isResolved);

        CourtCase case14 = new CourtCase();
        case14.caseNumber = "ENV999";
        case14.caseType = "Environmental";
        case14.courtName = "Green Tribunal";
        case14.judgeName = "Justice R. Banerjee";
        case14.plaintiff = "Save Earth Org";
        case14.defendant = "Oil Industries";
        case14.isResolved = true;
        System.out.println("CASE NUMBER : " + case14.caseNumber);
        System.out.println("CASE TYPE : " + case14.caseType);
        System.out.println("COURT NAME : " + case14.courtName);
        System.out.println("JUDGE NAME : " + case14.judgeName);
        System.out.println("PLAINTIFF : " + case14.plaintiff);
        System.out.println("DEFENDANT : " + case14.defendant);
        System.out.println("IS RESOLVED : " + case14.isResolved);

        CourtCase case15 = new CourtCase();
        case15.caseNumber = "IP102";
        case15.caseType = "Intellectual Property";
        case15.courtName = "Commercial Court";
        case15.judgeName = "Justice D. Khanna";
        case15.plaintiff = "AppDev Co.";
        case15.defendant = "SoftCorp";
        case15.isResolved = false;
        System.out.println("CASE NUMBER : " + case15.caseNumber);
        System.out.println("CASE TYPE : " + case15.caseType);
        System.out.println("COURT NAME : " + case15.courtName);
        System.out.println("JUDGE NAME : " + case15.judgeName);
        System.out.println("PLAINTIFF : " + case15.plaintiff);
        System.out.println("DEFENDANT : " + case15.defendant);
        System.out.println("IS RESOLVED : " + case15.isResolved);

        CourtCase case16 = new CourtCase();
        case16.caseNumber = "PROP504";
        case16.caseType = "Property";
        case16.courtName = "City Civil Court";
        case16.judgeName = "Justice H. Iyer";
        case16.plaintiff = "Suresh";
        case16.defendant = "Ramesh";
        case16.isResolved = true;
        System.out.println("CASE NUMBER : " + case16.caseNumber);
        System.out.println("CASE TYPE : " + case16.caseType);
        System.out.println("COURT NAME : " + case16.courtName);
        System.out.println("JUDGE NAME : " + case16.judgeName);
        System.out.println("PLAINTIFF : " + case16.plaintiff);
        System.out.println("DEFENDANT : " + case16.defendant);
        System.out.println("IS RESOLVED : " + case16.isResolved);

        CourtCase case17 = new CourtCase();
        case17.caseNumber = "TRADE210";
        case17.caseType = "Trade";
        case17.courtName = "Commercial Court";
        case17.judgeName = "Justice N. Shankar";
        case17.plaintiff = "Global Traders";
        case17.defendant = "TradeHub";
        case17.isResolved = false;
        System.out.println("CASE NUMBER : " + case17.caseNumber);
        System.out.println("CASE TYPE : " + case17.caseType);
        System.out.println("COURT NAME : " + case17.courtName);
        System.out.println("JUDGE NAME : " + case17.judgeName);
        System.out.println("PLAINTIFF : " + case17.plaintiff);
        System.out.println("DEFENDANT : " + case17.defendant);
        System.out.println("IS RESOLVED : " + case17.isResolved);

        CourtCase case18 = new CourtCase();
        case18.caseNumber = "CIV888";
        case18.caseType = "Civil";
        case18.courtName = "High Court";
        case18.judgeName = "Justice M. Kumar";
        case18.plaintiff = "Anil";
        case18.defendant = "Vinay";
        case18.isResolved = true;
        System.out.println("CASE NUMBER : " + case18.caseNumber);
        System.out.println("CASE TYPE : " + case18.caseType);
        System.out.println("COURT NAME : " + case18.courtName);
        System.out.println("JUDGE NAME : " + case18.judgeName);
        System.out.println("PLAINTIFF : " + case18.plaintiff);
        System.out.println("DEFENDANT : " + case18.defendant);
        System.out.println("IS RESOLVED : " + case18.isResolved);

        CourtCase case19 = new CourtCase();
        case19.caseNumber = "CRIM212";
        case19.caseType = "Criminal";
        case19.courtName = "Sessions Court";
        case19.judgeName = "Justice S. Rao";
        case19.plaintiff = "State of UP";
        case19.defendant = "XYZ Corp";
        case19.isResolved = false;
        System.out.println("CASE NUMBER : " + case19.caseNumber);
        System.out.println("CASE TYPE : " + case19.caseType);
        System.out.println("COURT NAME : " + case19.courtName);
        System.out.println("JUDGE NAME : " + case19.judgeName);
        System.out.println("PLAINTIFF : " + case19.plaintiff);
        System.out.println("DEFENDANT : " + case19.defendant);
        System.out.println("IS RESOLVED : " + case19.isResolved);

        CourtCase case20 = new CourtCase();
        case20.caseNumber = "FAM707";
        case20.caseType = "Family";
        case20.courtName = "Family Court";
        case20.judgeName = "Justice K. Das";
        case20.plaintiff = "Sneha";
        case20.defendant = "Amit";
        case20.isResolved = true;
        System.out.println("CASE NUMBER : " + case20.caseNumber);
        System.out.println("CASE TYPE : " + case20.caseType);
        System.out.println("COURT NAME : " + case20.courtName);
        System.out.println("JUDGE NAME : " + case20.judgeName);
        System.out.println("PLAINTIFF : " + case20.plaintiff);
        System.out.println("DEFENDANT : " + case20.defendant);
        System.out.println("IS RESOLVED : " + case20.isResolved);

        System.out.println("MAIN ENDED");
    }
}
