class CrackersRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Crackers cracker1 = new Crackers();
        cracker1.name = "Flowerpot Deluxe";
        cracker1.type = "Flowerpot";
        cracker1.brand = "Standard";
        cracker1.price = 150.50f;
        cracker1.quantity = 10;
        cracker1.isEcoFriendly = true;
        System.out.println("NAME : " + cracker1.name);
        System.out.println("TYPE : " + cracker1.type);
        System.out.println("BRAND : " + cracker1.brand);
        System.out.println("PRICE : " + cracker1.price);
        System.out.println("QUANTITY : " + cracker1.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker1.isEcoFriendly);

        Crackers cracker2 = new Crackers();
        cracker2.name = "Sky Rocket";
        cracker2.type = "Rocket";
        cracker2.brand = "Ananda";
        cracker2.price = 250.00f;
        cracker2.quantity = 5;
        cracker2.isEcoFriendly = false;
        System.out.println("NAME : " + cracker2.name);
        System.out.println("TYPE : " + cracker2.type);
        System.out.println("BRAND : " + cracker2.brand);
        System.out.println("PRICE : " + cracker2.price);
        System.out.println("QUANTITY : " + cracker2.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker2.isEcoFriendly);

        Crackers cracker3 = new Crackers();
        cracker3.name = "Electric Sparkler";
        cracker3.type = "Sparkler";
        cracker3.brand = "Ayyan";
        cracker3.price = 100.00f;
        cracker3.quantity = 20;
        cracker3.isEcoFriendly = true;
        System.out.println("NAME : " + cracker3.name);
        System.out.println("TYPE : " + cracker3.type);
        System.out.println("BRAND : " + cracker3.brand);
        System.out.println("PRICE : " + cracker3.price);
        System.out.println("QUANTITY : " + cracker3.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker3.isEcoFriendly);

        Crackers cracker4 = new Crackers();
        cracker4.name = "Whistling Rocket";
        cracker4.type = "Rocket";
        cracker4.brand = "Sri Kaliswari";
        cracker4.price = 300.00f;
        cracker4.quantity = 6;
        cracker4.isEcoFriendly = false;
        System.out.println("NAME : " + cracker4.name);
        System.out.println("TYPE : " + cracker4.type);
        System.out.println("BRAND : " + cracker4.brand);
        System.out.println("PRICE : " + cracker4.price);
        System.out.println("QUANTITY : " + cracker4.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker4.isEcoFriendly);

        Crackers cracker5 = new Crackers();
        cracker5.name = "Green Anar";
        cracker5.type = "Flowerpot";
        cracker5.brand = "Standard";
        cracker5.price = 180.75f;
        cracker5.quantity = 8;
        cracker5.isEcoFriendly = true;
        System.out.println("NAME : " + cracker5.name);
        System.out.println("TYPE : " + cracker5.type);
        System.out.println("BRAND : " + cracker5.brand);
        System.out.println("PRICE : " + cracker5.price);
        System.out.println("QUANTITY : " + cracker5.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker5.isEcoFriendly);

        Crackers cracker6 = new Crackers();
        cracker6.name = "Color Fountain";
        cracker6.type = "Flowerpot";
        cracker6.brand = "Ayyan";
        cracker6.price = 200.00f;
        cracker6.quantity = 10;
        cracker6.isEcoFriendly = true;
        System.out.println("NAME : " + cracker6.name);
        System.out.println("TYPE : " + cracker6.type);
        System.out.println("BRAND : " + cracker6.brand);
        System.out.println("PRICE : " + cracker6.price);
        System.out.println("QUANTITY : " + cracker6.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker6.isEcoFriendly);

        Crackers cracker7 = new Crackers();
        cracker7.name = "Ground Spinner";
        cracker7.type = "Spinner";
        cracker7.brand = "Sri Kaliswari";
        cracker7.price = 120.00f;
        cracker7.quantity = 15;
        cracker7.isEcoFriendly = false;
        System.out.println("NAME : " + cracker7.name);
        System.out.println("TYPE : " + cracker7.type);
        System.out.println("BRAND : " + cracker7.brand);
        System.out.println("PRICE : " + cracker7.price);
        System.out.println("QUANTITY : " + cracker7.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker7.isEcoFriendly);

        Crackers cracker8 = new Crackers();
        cracker8.name = "Magic Pencil";
        cracker8.type = "Sparkler";
        cracker8.brand = "Standard";
        cracker8.price = 80.00f;
        cracker8.quantity = 25;
        cracker8.isEcoFriendly = true;
        System.out.println("NAME : " + cracker8.name);
        System.out.println("TYPE : " + cracker8.type);
        System.out.println("BRAND : " + cracker8.brand);
        System.out.println("PRICE : " + cracker8.price);
        System.out.println("QUANTITY : " + cracker8.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker8.isEcoFriendly);

        Crackers cracker9 = new Crackers();
        cracker9.name = "Chakri Deluxe";
        cracker9.type = "Spinner";
        cracker9.brand = "Ananda";
        cracker9.price = 90.00f;
        cracker9.quantity = 12;
        cracker9.isEcoFriendly = false;
        System.out.println("NAME : " + cracker9.name);
        System.out.println("TYPE : " + cracker9.type);
        System.out.println("BRAND : " + cracker9.brand);
        System.out.println("PRICE : " + cracker9.price);
        System.out.println("QUANTITY : " + cracker9.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker9.isEcoFriendly);

        Crackers cracker10 = new Crackers();
        cracker10.name = "Crackling Rocket";
        cracker10.type = "Rocket";
        cracker10.brand = "Ayyan";
        cracker10.price = 350.00f;
        cracker10.quantity = 5;
        cracker10.isEcoFriendly = false;
        System.out.println("NAME : " + cracker10.name);
        System.out.println("TYPE : " + cracker10.type);
        System.out.println("BRAND : " + cracker10.brand);
        System.out.println("PRICE : " + cracker10.price);
        System.out.println("QUANTITY : " + cracker10.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker10.isEcoFriendly);

        // Similarly, create cracker11 to cracker20
        Crackers cracker11 = new Crackers();
        cracker11.name = "Twinkling Star";
        cracker11.type = "Sparkler";
        cracker11.brand = "Standard";
        cracker11.price = 70.00f;
        cracker11.quantity = 20;
        cracker11.isEcoFriendly = true;
        System.out.println("NAME : " + cracker11.name);
        System.out.println("TYPE : " + cracker11.type);
        System.out.println("BRAND : " + cracker11.brand);
        System.out.println("PRICE : " + cracker11.price);
        System.out.println("QUANTITY : " + cracker11.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker11.isEcoFriendly);

        Crackers cracker12 = new Crackers();
        cracker12.name = "Thunder Bomb";
        cracker12.type = "Bomb";
        cracker12.brand = "Sri Kaliswari";
        cracker12.price = 220.00f;
        cracker12.quantity = 10;
        cracker12.isEcoFriendly = false;
        System.out.println("NAME : " + cracker12.name);
        System.out.println("TYPE : " + cracker12.type);
        System.out.println("BRAND : " + cracker12.brand);
        System.out.println("PRICE : " + cracker12.price);
        System.out.println("QUANTITY : " + cracker12.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker12.isEcoFriendly);

        Crackers cracker13 = new Crackers();
        cracker13.name = "Colorful Sky Shot";
        cracker13.type = "Rocket";
        cracker13.brand = "Ananda";
        cracker13.price = 280.00f;
        cracker13.quantity = 5;
        cracker13.isEcoFriendly = false;
        System.out.println("NAME : " + cracker13.name);
        System.out.println("TYPE : " + cracker13.type);
        System.out.println("BRAND : " + cracker13.brand);
        System.out.println("PRICE : " + cracker13.price);
        System.out.println("QUANTITY : " + cracker13.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker13.isEcoFriendly);

        Crackers cracker14 = new Crackers();
        cracker14.name = "Golden Anar";
        cracker14.type = "Flowerpot";
        cracker14.brand = "Standard";
        cracker14.price = 190.00f;
        cracker14.quantity = 7;
        cracker14.isEcoFriendly = true;
        System.out.println("NAME : " + cracker14.name);
        System.out.println("TYPE : " + cracker14.type);
        System.out.println("BRAND : " + cracker14.brand);
        System.out.println("PRICE : " + cracker14.price);
        System.out.println("QUANTITY : " + cracker14.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker14.isEcoFriendly);

        Crackers cracker15 = new Crackers();
        cracker15.name = "Magic Spinner";
        cracker15.type = "Spinner";
        cracker15.brand = "Ayyan";
        cracker15.price = 100.00f;
        cracker15.quantity = 15;
        cracker15.isEcoFriendly = true;
        System.out.println("NAME : " + cracker15.name);
        System.out.println("TYPE : " + cracker15.type);
        System.out.println("BRAND : " + cracker15.brand);
        System.out.println("PRICE : " + cracker15.price);
        System.out.println("QUANTITY : " + cracker15.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker15.isEcoFriendly);

        Crackers cracker16 = new Crackers();
        cracker16.name = "Fire Pencil";
        cracker16.type = "Sparkler";
        cracker16.brand = "Standard";
        cracker16.price = 85.00f;
        cracker16.quantity = 18;
        cracker16.isEcoFriendly = true;
        System.out.println("NAME : " + cracker16.name);
        System.out.println("TYPE : " + cracker16.type);
        System.out.println("BRAND : " + cracker16.brand);
        System.out.println("PRICE : " + cracker16.price);
        System.out.println("QUANTITY : " + cracker16.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker16.isEcoFriendly);

        Crackers cracker17 = new Crackers();
        cracker17.name = "Mini Bomb";
        cracker17.type = "Bomb";
        cracker17.brand = "Sri Kaliswari";
        cracker17.price = 150.00f;
        cracker17.quantity = 12;
        cracker17.isEcoFriendly = false;
        System.out.println("NAME : " + cracker17.name);
        System.out.println("TYPE : " + cracker17.type);
        System.out.println("BRAND : " + cracker17.brand);
        System.out.println("PRICE : " + cracker17.price);
        System.out.println("QUANTITY : " + cracker17.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker17.isEcoFriendly);

        Crackers cracker18 = new Crackers();
        cracker18.name = "Laser Fountain";
        cracker18.type = "Flowerpot";
        cracker18.brand = "Ananda";
        cracker18.price = 220.00f;
        cracker18.quantity = 8;
        cracker18.isEcoFriendly = true;
        System.out.println("NAME : " + cracker18.name);
        System.out.println("TYPE : " + cracker18.type);
        System.out.println("BRAND : " + cracker18.brand);
        System.out.println("PRICE : " + cracker18.price);
        System.out.println("QUANTITY : " + cracker18.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker18.isEcoFriendly);

        Crackers cracker19 = new Crackers();
        cracker19.name = "Color Sparkler";
        cracker19.type = "Sparkler";
        cracker19.brand = "Ayyan";
        cracker19.price = 95.00f;
        cracker19.quantity = 20;
        cracker19.isEcoFriendly = true;
        System.out.println("NAME : " + cracker19.name);
        System.out.println("TYPE : " + cracker19.type);
        System.out.println("BRAND : " + cracker19.brand);
        System.out.println("PRICE : " + cracker19.price);
        System.out.println("QUANTITY : " + cracker19.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker19.isEcoFriendly);

        Crackers cracker20 = new Crackers();
        cracker20.name = "Ultimate Sky Rocket";
        cracker20.type = "Rocket";
        cracker20.brand = "Sri Kaliswari";
        cracker20.price = 400.00f;
        cracker20.quantity = 4;
        cracker20.isEcoFriendly = false;
        System.out.println("NAME : " + cracker20.name);
        System.out.println("TYPE : " + cracker20.type);
        System.out.println("BRAND : " + cracker20.brand);
        System.out.println("PRICE : " + cracker20.price);
        System.out.println("QUANTITY : " + cracker20.quantity);
        System.out.println("ECO-FRIENDLY : " + cracker20.isEcoFriendly);

        System.out.println("MAIN ENDED");
    }
}
