class FestivalsRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Festivals fest1 = new Festivals();
        fest1.name = "Diwali";
        fest1.state = "All India";
        fest1.month = "October-November";
        fest1.durationDays = 5;
        fest1.isNationalHoliday = true;
        fest1.significance = "Festival of Lights";
        System.out.println("NAME : " + fest1.name);
        System.out.println("STATE : " + fest1.state);
        System.out.println("MONTH : " + fest1.month);
        System.out.println("DURATION DAYS : " + fest1.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest1.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest1.significance);

        Festivals fest2 = new Festivals();
        fest2.name = "Holi";
        fest2.state = "All India";
        fest2.month = "March";
        fest2.durationDays = 2;
        fest2.isNationalHoliday = true;
        fest2.significance = "Festival of Colors";
        System.out.println("NAME : " + fest2.name);
        System.out.println("STATE : " + fest2.state);
        System.out.println("MONTH : " + fest2.month);
        System.out.println("DURATION DAYS : " + fest2.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest2.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest2.significance);

        Festivals fest3 = new Festivals();
        fest3.name = "Navratri";
        fest3.state = "Gujarat";
        fest3.month = "September-October";
        fest3.durationDays = 9;
        fest3.isNationalHoliday = false;
        fest3.significance = "Worship of Goddess Durga";
        System.out.println("NAME : " + fest3.name);
        System.out.println("STATE : " + fest3.state);
        System.out.println("MONTH : " + fest3.month);
        System.out.println("DURATION DAYS : " + fest3.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest3.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest3.significance);

        Festivals fest4 = new Festivals();
        fest4.name = "Pongal";
        fest4.state = "Tamil Nadu";
        fest4.month = "January";
        fest4.durationDays = 4;
        fest4.isNationalHoliday = true;
        fest4.significance = "Harvest Festival";
        System.out.println("NAME : " + fest4.name);
        System.out.println("STATE : " + fest4.state);
        System.out.println("MONTH : " + fest4.month);
        System.out.println("DURATION DAYS : " + fest4.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest4.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest4.significance);

        Festivals fest5 = new Festivals();
        fest5.name = "Onam";
        fest5.state = "Kerala";
        fest5.month = "August-September";
        fest5.durationDays = 10;
        fest5.isNationalHoliday = true;
        fest5.significance = "Homecoming of King Mahabali";
        System.out.println("NAME : " + fest5.name);
        System.out.println("STATE : " + fest5.state);
        System.out.println("MONTH : " + fest5.month);
        System.out.println("DURATION DAYS : " + fest5.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest5.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest5.significance);

        Festivals fest6 = new Festivals();
        fest6.name = "Baisakhi";
        fest6.state = "Punjab";
        fest6.month = "April";
        fest6.durationDays = 1;
        fest6.isNationalHoliday = true;
        fest6.significance = "Harvest Festival of Punjab";
        System.out.println("NAME : " + fest6.name);
        System.out.println("STATE : " + fest6.state);
        System.out.println("MONTH : " + fest6.month);
        System.out.println("DURATION DAYS : " + fest6.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest6.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest6.significance);

        Festivals fest7 = new Festivals();
        fest7.name = "Ganesh Chaturthi";
        fest7.state = "Maharashtra";
        fest7.month = "August-September";
        fest7.durationDays = 10;
        fest7.isNationalHoliday = false;
        fest7.significance = "Birth of Lord Ganesha";
        System.out.println("NAME : " + fest7.name);
        System.out.println("STATE : " + fest7.state);
        System.out.println("MONTH : " + fest7.month);
        System.out.println("DURATION DAYS : " + fest7.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest7.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest7.significance);

        Festivals fest8 = new Festivals();
        fest8.name = "Durga Puja";
        fest8.state = "West Bengal";
        fest8.month = "September-October";
        fest8.durationDays = 5;
        fest8.isNationalHoliday = true;
        fest8.significance = "Worship of Goddess Durga";
        System.out.println("NAME : " + fest8.name);
        System.out.println("STATE : " + fest8.state);
        System.out.println("MONTH : " + fest8.month);
        System.out.println("DURATION DAYS : " + fest8.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest8.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest8.significance);

        Festivals fest9 = new Festivals();
        fest9.name = "Eid-ul-Fitr";
        fest9.state = "All India";
        fest9.month = "Varies";
        fest9.durationDays = 1;
        fest9.isNationalHoliday = true;
        fest9.significance = "End of Ramadan";
        System.out.println("NAME : " + fest9.name);
        System.out.println("STATE : " + fest9.state);
        System.out.println("MONTH : " + fest9.month);
        System.out.println("DURATION DAYS : " + fest9.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest9.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest9.significance);

        Festivals fest10 = new Festivals();
        fest10.name = "Christmas";
        fest10.state = "All India";
        fest10.month = "December";
        fest10.durationDays = 1;
        fest10.isNationalHoliday = true;
        fest10.significance = "Birth of Jesus Christ";
        System.out.println("NAME : " + fest10.name);
        System.out.println("STATE : " + fest10.state);
        System.out.println("MONTH : " + fest10.month);
        System.out.println("DURATION DAYS : " + fest10.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest10.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest10.significance);

        Festivals fest11 = new Festivals();
        fest11.name = "Makar Sankranti";
        fest11.state = "All India";
        fest11.month = "January";
        fest11.durationDays = 1;
        fest11.isNationalHoliday = true;
        fest11.significance = "Harvest and Kite Festival";
        System.out.println("NAME : " + fest11.name);
        System.out.println("STATE : " + fest11.state);
        System.out.println("MONTH : " + fest11.month);
        System.out.println("DURATION DAYS : " + fest11.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest11.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest11.significance);

        Festivals fest12 = new Festivals();
        fest12.name = "Raksha Bandhan";
        fest12.state = "All India";
        fest12.month = "August";
        fest12.durationDays = 1;
        fest12.isNationalHoliday = false;
        fest12.significance = "Bond of Brother and Sister";
        System.out.println("NAME : " + fest12.name);
        System.out.println("STATE : " + fest12.state);
        System.out.println("MONTH : " + fest12.month);
        System.out.println("DURATION DAYS : " + fest12.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest12.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest12.significance);

        Festivals fest13 = new Festivals();
        fest13.name = "Janmashtami";
        fest13.state = "Uttar Pradesh";
        fest13.month = "August";
        fest13.durationDays = 2;
        fest13.isNationalHoliday = false;
        fest13.significance = "Birth of Lord Krishna";
        System.out.println("NAME : " + fest13.name);
        System.out.println("STATE : " + fest13.state);
        System.out.println("MONTH : " + fest13.month);
        System.out.println("DURATION DAYS : " + fest13.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest13.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest13.significance);

        Festivals fest14 = new Festivals();
        fest14.name = "Karva Chauth";
        fest14.state = "North India";
        fest14.month = "October-November";
        fest14.durationDays = 1;
        fest14.isNationalHoliday = false;
        fest14.significance = "Fasting for Husband's Long Life";
        System.out.println("NAME : " + fest14.name);
        System.out.println("STATE : " + fest14.state);
        System.out.println("MONTH : " + fest14.month);
        System.out.println("DURATION DAYS : " + fest14.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest14.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest14.significance);

        Festivals fest15 = new Festivals();
        fest15.name = "Bihu";
        fest15.state = "Assam";
        fest15.month = "April";
        fest15.durationDays = 7;
        fest15.isNationalHoliday = true;
        fest15.significance = "Harvest Festival of Assam";
        System.out.println("NAME : " + fest15.name);
        System.out.println("STATE : " + fest15.state);
        System.out.println("MONTH : " + fest15.month);
        System.out.println("DURATION DAYS : " + fest15.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest15.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest15.significance);

        Festivals fest16 = new Festivals();
        fest16.name = "Ugadi";
        fest16.state = "Andhra Pradesh";
        fest16.month = "March-April";
        fest16.durationDays = 1;
        fest16.isNationalHoliday = true;
        fest16.significance = "New Year of Andhra & Karnataka";
        System.out.println("NAME : " + fest16.name);
        System.out.println("STATE : " + fest16.state);
        System.out.println("MONTH : " + fest16.month);
        System.out.println("DURATION DAYS : " + fest16.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest16.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest16.significance);

        Festivals fest17 = new Festivals();
        fest17.name = "Vishu";
        fest17.state = "Kerala";
        fest17.month = "April";
        fest17.durationDays = 1;
        fest17.isNationalHoliday = true;
        fest17.significance = "Malayalam New Year";
        System.out.println("NAME : " + fest17.name);
        System.out.println("STATE : " + fest17.state);
        System.out.println("MONTH : " + fest17.month);
        System.out.println("DURATION DAYS : " + fest17.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest17.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest17.significance);

        Festivals fest18 = new Festivals();
        fest18.name = "Mahashivratri";
        fest18.state = "All India";
        fest18.month = "February-March";
        fest18.durationDays = 1;
        fest18.isNationalHoliday = true;
        fest18.significance = "Worship of Lord Shiva";
        System.out.println("NAME : " + fest18.name);
        System.out.println("STATE : " + fest18.state);
        System.out.println("MONTH : " + fest18.month);
        System.out.println("DURATION DAYS : " + fest18.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest18.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest18.significance);

        Festivals fest19 = new Festivals();
        fest19.name = "Ram Navami";
        fest19.state = "All India";
        fest19.month = "March-April";
        fest19.durationDays = 1;
        fest19.isNationalHoliday = true;
        fest19.significance = "Birth of Lord Rama";
        System.out.println("NAME : " + fest19.name);
        System.out.println("STATE : " + fest19.state);
        System.out.println("MONTH : " + fest19.month);
        System.out.println("DURATION DAYS : " + fest19.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest19.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest19.significance);

        Festivals fest20 = new Festivals();
        fest20.name = "Buddha Purnima";
        fest20.state = "All India";
        fest20.month = "April-May";
        fest20.durationDays = 1;
        fest20.isNationalHoliday = true;
        fest20.significance = "Birth of Lord Buddha";
        System.out.println("NAME : " + fest20.name);
        System.out.println("STATE : " + fest20.state);
        System.out.println("MONTH : " + fest20.month);
        System.out.println("DURATION DAYS : " + fest20.durationDays);
        System.out.println("NATIONAL HOLIDAY : " + fest20.isNationalHoliday);
        System.out.println("SIGNIFICANCE : " + fest20.significance);

        System.out.println("MAIN ENDED");
    }
}
