class FishRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Fish fish1 = new Fish();
        fish1.name = "Salmon";
        fish1.type = "Ray-finned";
        fish1.color = "Pink";
        fish1.weight = 3.5f;
        fish1.isFreshWater = true;
        fish1.habitat = "Rivers";
        System.out.println("NAME : " + fish1.name);
        System.out.println("TYPE : " + fish1.type);
        System.out.println("COLOR : " + fish1.color);
        System.out.println("WEIGHT : " + fish1.weight);
        System.out.println("FRESH WATER : " + fish1.isFreshWater);
        System.out.println("HABITAT : " + fish1.habitat);

        Fish fish2 = new Fish();
        fish2.name = "Tuna";
        fish2.type = "Mackerel";
        fish2.color = "Blue-Silver";
        fish2.weight = 40.0f;
        fish2.isFreshWater = false;
        fish2.habitat = "Oceans";
        System.out.println("NAME : " + fish2.name);
        System.out.println("TYPE : " + fish2.type);
        System.out.println("COLOR : " + fish2.color);
        System.out.println("WEIGHT : " + fish2.weight);
        System.out.println("FRESH WATER : " + fish2.isFreshWater);
        System.out.println("HABITAT : " + fish2.habitat);

        Fish fish3 = new Fish();
        fish3.name = "Clownfish";
        fish3.type = "Anemonefish";
        fish3.color = "Orange-White";
        fish3.weight = 0.25f;
        fish3.isFreshWater = false;
        fish3.habitat = "Coral Reefs";
        System.out.println("NAME : " + fish3.name);
        System.out.println("TYPE : " + fish3.type);
        System.out.println("COLOR : " + fish3.color);
        System.out.println("WEIGHT : " + fish3.weight);
        System.out.println("FRESH WATER : " + fish3.isFreshWater);
        System.out.println("HABITAT : " + fish3.habitat);

        Fish fish4 = new Fish();
        fish4.name = "Catfish";
        fish4.type = "Siluriformes";
        fish4.color = "Brown";
        fish4.weight = 2.0f;
        fish4.isFreshWater = true;
        fish4.habitat = "Lakes";
        System.out.println("NAME : " + fish4.name);
        System.out.println("TYPE : " + fish4.type);
        System.out.println("COLOR : " + fish4.color);
        System.out.println("WEIGHT : " + fish4.weight);
        System.out.println("FRESH WATER : " + fish4.isFreshWater);
        System.out.println("HABITAT : " + fish4.habitat);

        Fish fish5 = new Fish();
        fish5.name = "Betta";
        fish5.type = "Siamese Fighter";
        fish5.color = "Red";
        fish5.weight = 0.05f;
        fish5.isFreshWater = true;
        fish5.habitat = "Aquarium";
        System.out.println("NAME : " + fish5.name);
        System.out.println("TYPE : " + fish5.type);
        System.out.println("COLOR : " + fish5.color);
        System.out.println("WEIGHT : " + fish5.weight);
        System.out.println("FRESH WATER : " + fish5.isFreshWater);
        System.out.println("HABITAT : " + fish5.habitat);

        Fish fish6 = new Fish();
        fish6.name = "Goldfish";
        fish6.type = "Carp";
        fish6.color = "Golden";
        fish6.weight = 0.2f;
        fish6.isFreshWater = true;
        fish6.habitat = "Ponds";
        System.out.println("NAME : " + fish6.name);
        System.out.println("TYPE : " + fish6.type);
        System.out.println("COLOR : " + fish6.color);
        System.out.println("WEIGHT : " + fish6.weight);
        System.out.println("FRESH WATER : " + fish6.isFreshWater);
        System.out.println("HABITAT : " + fish6.habitat);

        Fish fish7 = new Fish();
        fish7.name = "Swordfish";
        fish7.type = "Billfish";
        fish7.color = "Silver-Blue";
        fish7.weight = 50.0f;
        fish7.isFreshWater = false;
        fish7.habitat = "Deep Sea";
        System.out.println("NAME : " + fish7.name);
        System.out.println("TYPE : " + fish7.type);
        System.out.println("COLOR : " + fish7.color);
        System.out.println("WEIGHT : " + fish7.weight);
        System.out.println("FRESH WATER : " + fish7.isFreshWater);
        System.out.println("HABITAT : " + fish7.habitat);

        Fish fish8 = new Fish();
        fish8.name = "Carp";
        fish8.type = "Cyprinidae";
        fish8.color = "Olive";
        fish8.weight = 4.0f;
        fish8.isFreshWater = true;
        fish8.habitat = "Lakes";
        System.out.println("NAME : " + fish8.name);
        System.out.println("TYPE : " + fish8.type);
        System.out.println("COLOR : " + fish8.color);
        System.out.println("WEIGHT : " + fish8.weight);
        System.out.println("FRESH WATER : " + fish8.isFreshWater);
        System.out.println("HABITAT : " + fish8.habitat);

        Fish fish9 = new Fish();
        fish9.name = "Snapper";
        fish9.type = "Lutjanidae";
        fish9.color = "Red";
        fish9.weight = 6.0f;
        fish9.isFreshWater = false;
        fish9.habitat = "Coastal Waters";
        System.out.println("NAME : " + fish9.name);
        System.out.println("TYPE : " + fish9.type);
        System.out.println("COLOR : " + fish9.color);
        System.out.println("WEIGHT : " + fish9.weight);
        System.out.println("FRESH WATER : " + fish9.isFreshWater);
        System.out.println("HABITAT : " + fish9.habitat);

        Fish fish10 = new Fish();
        fish10.name = "Shark";
        fish10.type = "Cartilaginous";
        fish10.color = "Grey";
        fish10.weight = 150.0f;
        fish10.isFreshWater = false;
        fish10.habitat = "Ocean";
        System.out.println("NAME : " + fish10.name);
        System.out.println("TYPE : " + fish10.type);
        System.out.println("COLOR : " + fish10.color);
        System.out.println("WEIGHT : " + fish10.weight);
        System.out.println("FRESH WATER : " + fish10.isFreshWater);
        System.out.println("HABITAT : " + fish10.habitat);

        Fish fish11 = new Fish();
        fish11.name = "Tilapia";
        fish11.type = "Cichlid";
        fish11.color = "Grey";
        fish11.weight = 1.2f;
        fish11.isFreshWater = true;
        fish11.habitat = "Rivers";
        System.out.println("NAME : " + fish11.name);
        System.out.println("TYPE : " + fish11.type);
        System.out.println("COLOR : " + fish11.color);
        System.out.println("WEIGHT : " + fish11.weight);
        System.out.println("FRESH WATER : " + fish11.isFreshWater);
        System.out.println("HABITAT : " + fish11.habitat);

        Fish fish12 = new Fish();
        fish12.name = "Anchovy";
        fish12.type = "Engraulidae";
        fish12.color = "Silver";
        fish12.weight = 0.05f;
        fish12.isFreshWater = false;
        fish12.habitat = "Sea";
        System.out.println("NAME : " + fish12.name);
        System.out.println("TYPE : " + fish12.type);
        System.out.println("COLOR : " + fish12.color);
        System.out.println("WEIGHT : " + fish12.weight);
        System.out.println("FRESH WATER : " + fish12.isFreshWater);
        System.out.println("HABITAT : " + fish12.habitat);

        Fish fish13 = new Fish();
        fish13.name = "Mahi Mahi";
        fish13.type = "Dolphinfish";
        fish13.color = "Blue-Green";
        fish13.weight = 7.0f;
        fish13.isFreshWater = false;
        fish13.habitat = "Tropical Oceans";
        System.out.println("NAME : " + fish13.name);
        System.out.println("TYPE : " + fish13.type);
        System.out.println("COLOR : " + fish13.color);
        System.out.println("WEIGHT : " + fish13.weight);
        System.out.println("FRESH WATER : " + fish13.isFreshWater);
        System.out.println("HABITAT : " + fish13.habitat);

        Fish fish14 = new Fish();
        fish14.name = "Herring";
        fish14.type = "Clupeidae";
        fish14.color = "Silver";
        fish14.weight = 0.8f;
        fish14.isFreshWater = false;
        fish14.habitat = "Atlantic Ocean";
        System.out.println("NAME : " + fish14.name);
        System.out.println("TYPE : " + fish14.type);
        System.out.println("COLOR : " + fish14.color);
        System.out.println("WEIGHT : " + fish14.weight);
        System.out.println("FRESH WATER : " + fish14.isFreshWater);
        System.out.println("HABITAT : " + fish14.habitat);

        Fish fish15 = new Fish();
        fish15.name = "Guppy";
        fish15.type = "Poecilia Reticulata";
        fish15.color = "Multi-colored";
        fish15.weight = 0.02f;
        fish15.isFreshWater = true;
        fish15.habitat = "Aquarium";
        System.out.println("NAME : " + fish15.name);
        System.out.println("TYPE : " + fish15.type);
        System.out.println("COLOR : " + fish15.color);
        System.out.println("WEIGHT : " + fish15.weight);
        System.out.println("FRESH WATER : " + fish15.isFreshWater);
        System.out.println("HABITAT : " + fish15.habitat);

        Fish fish16 = new Fish();
        fish16.name = "Pufferfish";
        fish16.type = "Tetraodontidae";
        fish16.color = "Yellow-Green";
        fish16.weight = 1.0f;
        fish16.isFreshWater = false;
        fish16.habitat = "Tropical Seas";
        System.out.println("NAME : " + fish16.name);
        System.out.println("TYPE : " + fish16.type);
        System.out.println("COLOR : " + fish16.color);
        System.out.println("WEIGHT : " + fish16.weight);
        System.out.println("FRESH WATER : " + fish16.isFreshWater);
        System.out.println("HABITAT : " + fish16.habitat);

        Fish fish17 = new Fish();
        fish17.name = "Sardine";
        fish17.type = "Clupeidae";
        fish17.color = "Silver";
        fish17.weight = 0.1f;
        fish17.isFreshWater = false;
        fish17.habitat = "Mediterranean Sea";
        System.out.println("NAME : " + fish17.name);
        System.out.println("TYPE : " + fish17.type);
        System.out.println("COLOR : " + fish17.color);
        System.out.println("WEIGHT : " + fish17.weight);
        System.out.println("FRESH WATER : " + fish17.isFreshWater);
        System.out.println("HABITAT : " + fish17.habitat);

        Fish fish18 = new Fish();
        fish18.name = "Trout";
        fish18.type = "Salmonidae";
        fish18.color = "Brown";
        fish18.weight = 2.5f;
        fish18.isFreshWater = true;
        fish18.habitat = "Rivers";
        System.out.println("NAME : " + fish18.name);
        System.out.println("TYPE : " + fish18.type);
        System.out.println("COLOR : " + fish18.color);
        System.out.println("WEIGHT : " + fish18.weight);
        System.out.println("FRESH WATER : " + fish18.isFreshWater);
        System.out.println("HABITAT : " + fish18.habitat);

        Fish fish19 = new Fish();
        fish19.name = "Marlin";
        fish19.type = "Billfish";
        fish19.color = "Blue";
        fish19.weight = 80.0f;
        fish19.isFreshWater = false;
        fish19.habitat = "Open Ocean";
        System.out.println("NAME : " + fish19.name);
        System.out.println("TYPE : " + fish19.type);
        System.out.println("COLOR : " + fish19.color);
        System.out.println("WEIGHT : " + fish19.weight);
        System.out.println("FRESH WATER : " + fish19.isFreshWater);
        System.out.println("HABITAT : " + fish19.habitat);

        Fish fish20 = new Fish();
        fish20.name = "Koi";
        fish20.type = "Carp";
        fish20.color = "Orange-White";
        fish20.weight = 1.8f;
        fish20.isFreshWater = true;
        fish20.habitat = "Ponds";
        System.out.println("NAME : " + fish20.name);
        System.out.println("TYPE : " + fish20.type);
        System.out.println("COLOR : " + fish20.color);
        System.out.println("WEIGHT : " + fish20.weight);
        System.out.println("FRESH WATER : " + fish20.isFreshWater);
        System.out.println("HABITAT : " + fish20.habitat);

        System.out.println("MAIN ENDED");
    }
}
