class ForestSafariRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        ForestSafari safari1 = new ForestSafari();
        safari1.location = "Jim Corbett";
        safari1.vehicleType = "Jeep";
        safari1.ticketPrice = 2500.0f;
        safari1.durationHours = 3;
        safari1.includesGuide = true;
        safari1.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari1.location);
        System.out.println("VEHICLE : " + safari1.vehicleType);
        System.out.println("TICKET PRICE : " + safari1.ticketPrice);
        System.out.println("DURATION : " + safari1.durationHours + " hrs");
        System.out.println("GUIDE : " + safari1.includesGuide);
        System.out.println("BEST SEASON : " + safari1.bestSeason);

        ForestSafari safari2 = new ForestSafari();
        safari2.location = "Kaziranga";
        safari2.vehicleType = "Elephant Ride";
        safari2.ticketPrice = 3000.0f;
        safari2.durationHours = 2;
        safari2.includesGuide = true;
        safari2.bestSeason = "Spring";
        System.out.println("LOCATION : " + safari2.location);
        System.out.println("VEHICLE : " + safari2.vehicleType);
        System.out.println("TICKET PRICE : " + safari2.ticketPrice);
        System.out.println("DURATION : " + safari2.durationHours + " hrs");
        System.out.println("GUIDE : " + safari2.includesGuide);
        System.out.println("BEST SEASON : " + safari2.bestSeason);

        ForestSafari safari3 = new ForestSafari();
        safari3.location = "Gir National Park";
        safari3.vehicleType = "Open Bus";
        safari3.ticketPrice = 1800.0f;
        safari3.durationHours = 4;
        safari3.includesGuide = true;
        safari3.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari3.location);
        System.out.println("VEHICLE : " + safari3.vehicleType);
        System.out.println("TICKET PRICE : " + safari3.ticketPrice);
        System.out.println("DURATION : " + safari3.durationHours + " hrs");
        System.out.println("GUIDE : " + safari3.includesGuide);
        System.out.println("BEST SEASON : " + safari3.bestSeason);

        ForestSafari safari4 = new ForestSafari();
        safari4.location = "Ranthambore";
        safari4.vehicleType = "Gypsy";
        safari4.ticketPrice = 2200.0f;
        safari4.durationHours = 3;
        safari4.includesGuide = true;
        safari4.bestSeason = "Autumn";
        System.out.println("LOCATION : " + safari4.location);
        System.out.println("VEHICLE : " + safari4.vehicleType);
        System.out.println("TICKET PRICE : " + safari4.ticketPrice);
        System.out.println("DURATION : " + safari4.durationHours + " hrs");
        System.out.println("GUIDE : " + safari4.includesGuide);
        System.out.println("BEST SEASON : " + safari4.bestSeason);

        ForestSafari safari5 = new ForestSafari();
        safari5.location = "Sundarbans";
        safari5.vehicleType = "Boat Safari";
        safari5.ticketPrice = 3500.0f;
        safari5.durationHours = 5;
        safari5.includesGuide = true;
        safari5.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari5.location);
        System.out.println("VEHICLE : " + safari5.vehicleType);
        System.out.println("TICKET PRICE : " + safari5.ticketPrice);
        System.out.println("DURATION : " + safari5.durationHours + " hrs");
        System.out.println("GUIDE : " + safari5.includesGuide);
        System.out.println("BEST SEASON : " + safari5.bestSeason);

        ForestSafari safari6 = new ForestSafari();
        safari6.location = "Bandhavgarh";
        safari6.vehicleType = "Jeep";
        safari6.ticketPrice = 2000.0f;
        safari6.durationHours = 3;
        safari6.includesGuide = false;
        safari6.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari6.location);
        System.out.println("VEHICLE : " + safari6.vehicleType);
        System.out.println("TICKET PRICE : " + safari6.ticketPrice);
        System.out.println("DURATION : " + safari6.durationHours + " hrs");
        System.out.println("GUIDE : " + safari6.includesGuide);
        System.out.println("BEST SEASON : " + safari6.bestSeason);

        ForestSafari safari7 = new ForestSafari();
        safari7.location = "Periyar Wildlife Sanctuary";
        safari7.vehicleType = "Boat";
        safari7.ticketPrice = 2800.0f;
        safari7.durationHours = 4;
        safari7.includesGuide = true;
        safari7.bestSeason = "Monsoon";
        System.out.println("LOCATION : " + safari7.location);
        System.out.println("VEHICLE : " + safari7.vehicleType);
        System.out.println("TICKET PRICE : " + safari7.ticketPrice);
        System.out.println("DURATION : " + safari7.durationHours + " hrs");
        System.out.println("GUIDE : " + safari7.includesGuide);
        System.out.println("BEST SEASON : " + safari7.bestSeason);

        ForestSafari safari8 = new ForestSafari();
        safari8.location = "Mudumalai";
        safari8.vehicleType = "Van";
        safari8.ticketPrice = 1700.0f;
        safari8.durationHours = 2;
        safari8.includesGuide = true;
        safari8.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari8.location);
        System.out.println("VEHICLE : " + safari8.vehicleType);
        System.out.println("TICKET PRICE : " + safari8.ticketPrice);
        System.out.println("DURATION : " + safari8.durationHours + " hrs");
        System.out.println("GUIDE : " + safari8.includesGuide);
        System.out.println("BEST SEASON : " + safari8.bestSeason);

        ForestSafari safari9 = new ForestSafari();
        safari9.location = "Pench National Park";
        safari9.vehicleType = "Jeep";
        safari9.ticketPrice = 2300.0f;
        safari9.durationHours = 3;
        safari9.includesGuide = false;
        safari9.bestSeason = "Spring";
        System.out.println("LOCATION : " + safari9.location);
        System.out.println("VEHICLE : " + safari9.vehicleType);
        System.out.println("TICKET PRICE : " + safari9.ticketPrice);
        System.out.println("DURATION : " + safari9.durationHours + " hrs");
        System.out.println("GUIDE : " + safari9.includesGuide);
        System.out.println("BEST SEASON : " + safari9.bestSeason);

        ForestSafari safari10 = new ForestSafari();
        safari10.location = "Dudhwa National Park";
        safari10.vehicleType = "Gypsy";
        safari10.ticketPrice = 2100.0f;
        safari10.durationHours = 3;
        safari10.includesGuide = true;
        safari10.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari10.location);
        System.out.println("VEHICLE : " + safari10.vehicleType);
        System.out.println("TICKET PRICE : " + safari10.ticketPrice);
        System.out.println("DURATION : " + safari10.durationHours + " hrs");
        System.out.println("GUIDE : " + safari10.includesGuide);
        System.out.println("BEST SEASON : " + safari10.bestSeason);

        ForestSafari safari11 = new ForestSafari();
        safari11.location = "Nagarhole";
        safari11.vehicleType = "Canter";
        safari11.ticketPrice = 2500.0f;
        safari11.durationHours = 4;
        safari11.includesGuide = true;
        safari11.bestSeason = "Monsoon";
        System.out.println("LOCATION : " + safari11.location);
        System.out.println("VEHICLE : " + safari11.vehicleType);
        System.out.println("TICKET PRICE : " + safari11.ticketPrice);
        System.out.println("DURATION : " + safari11.durationHours + " hrs");
        System.out.println("GUIDE : " + safari11.includesGuide);
        System.out.println("BEST SEASON : " + safari11.bestSeason);

        ForestSafari safari12 = new ForestSafari();
        safari12.location = "Manas National Park";
        safari12.vehicleType = "Jeep";
        safari12.ticketPrice = 3000.0f;
        safari12.durationHours = 3;
        safari12.includesGuide = false;
        safari12.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari12.location);
        System.out.println("VEHICLE : " + safari12.vehicleType);
        System.out.println("TICKET PRICE : " + safari12.ticketPrice);
        System.out.println("DURATION : " + safari12.durationHours + " hrs");
        System.out.println("GUIDE : " + safari12.includesGuide);
        System.out.println("BEST SEASON : " + safari12.bestSeason);

        ForestSafari safari13 = new ForestSafari();
        safari13.location = "Bandipur";
        safari13.vehicleType = "Bus";
        safari13.ticketPrice = 1800.0f;
        safari13.durationHours = 2;
        safari13.includesGuide = true;
        safari13.bestSeason = "Summer";
        System.out.println("LOCATION : " + safari13.location);
        System.out.println("VEHICLE : " + safari13.vehicleType);
        System.out.println("TICKET PRICE : " + safari13.ticketPrice);
        System.out.println("DURATION : " + safari13.durationHours + " hrs");
        System.out.println("GUIDE : " + safari13.includesGuide);
        System.out.println("BEST SEASON : " + safari13.bestSeason);

        ForestSafari safari14 = new ForestSafari();
        safari14.location = "Tadoba";
        safari14.vehicleType = "Jeep";
        safari14.ticketPrice = 2500.0f;
        safari14.durationHours = 3;
        safari14.includesGuide = true;
        safari14.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari14.location);
        System.out.println("VEHICLE : " + safari14.vehicleType);
        System.out.println("TICKET PRICE : " + safari14.ticketPrice);
        System.out.println("DURATION : " + safari14.durationHours + " hrs");
        System.out.println("GUIDE : " + safari14.includesGuide);
        System.out.println("BEST SEASON : " + safari14.bestSeason);

        ForestSafari safari15 = new ForestSafari();
        safari15.location = "Anamalai Tiger Reserve";
        safari15.vehicleType = "Van";
        safari15.ticketPrice = 2000.0f;
        safari15.durationHours = 2;
        safari15.includesGuide = false;
        safari15.bestSeason = "Spring";
        System.out.println("LOCATION : " + safari15.location);
        System.out.println("VEHICLE : " + safari15.vehicleType);
        System.out.println("TICKET PRICE : " + safari15.ticketPrice);
        System.out.println("DURATION : " + safari15.durationHours + " hrs");
        System.out.println("GUIDE : " + safari15.includesGuide);
        System.out.println("BEST SEASON : " + safari15.bestSeason);

        ForestSafari safari16 = new ForestSafari();
        safari16.location = "Buxa Tiger Reserve";
        safari16.vehicleType = "Jeep";
        safari16.ticketPrice = 2700.0f;
        safari16.durationHours = 4;
        safari16.includesGuide = true;
        safari16.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari16.location);
        System.out.println("VEHICLE : " + safari16.vehicleType);
        System.out.println("TICKET PRICE : " + safari16.ticketPrice);
        System.out.println("DURATION : " + safari16.durationHours + " hrs");
        System.out.println("GUIDE : " + safari16.includesGuide);
        System.out.println("BEST SEASON : " + safari16.bestSeason);

        ForestSafari safari17 = new ForestSafari();
        safari17.location = "Kanha";
        safari17.vehicleType = "Gypsy";
        safari17.ticketPrice = 2400.0f;
        safari17.durationHours = 3;
        safari17.includesGuide = true;
        safari17.bestSeason = "Autumn";
        System.out.println("LOCATION : " + safari17.location);
        System.out.println("VEHICLE : " + safari17.vehicleType);
        System.out.println("TICKET PRICE : " + safari17.ticketPrice);
        System.out.println("DURATION : " + safari17.durationHours + " hrs");
        System.out.println("GUIDE : " + safari17.includesGuide);
        System.out.println("BEST SEASON : " + safari17.bestSeason);

        ForestSafari safari18 = new ForestSafari();
        safari18.location = "Valmiki National Park";
        safari18.vehicleType = "Jeep";
        safari18.ticketPrice = 2200.0f;
        safari18.durationHours = 3;
        safari18.includesGuide = true;
        safari18.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari18.location);
        System.out.println("VEHICLE : " + safari18.vehicleType);
        System.out.println("TICKET PRICE : " + safari18.ticketPrice);
        System.out.println("DURATION : " + safari18.durationHours + " hrs");
        System.out.println("GUIDE : " + safari18.includesGuide);
        System.out.println("BEST SEASON : " + safari18.bestSeason);

        ForestSafari safari19 = new ForestSafari();
        safari19.location = "Simlipal";
        safari19.vehicleType = "Open Jeep";
        safari19.ticketPrice = 2000.0f;
        safari19.durationHours = 3;
        safari19.includesGuide = false;
        safari19.bestSeason = "Winter";
        System.out.println("LOCATION : " + safari19.location);
        System.out.println("VEHICLE : " + safari19.vehicleType);
        System.out.println("TICKET PRICE : " + safari19.ticketPrice);
        System.out.println("DURATION : " + safari19.durationHours + " hrs");
        System.out.println("GUIDE : " + safari19.includesGuide);
        System.out.println("BEST SEASON : " + safari19.bestSeason);

        ForestSafari safari20 = new ForestSafari();
        safari20.location = "Parambikulam";
        safari20.vehicleType = "Van";
        safari20.ticketPrice = 1900.0f;
        safari20.durationHours = 2;
        safari20.includesGuide = true;
        safari20.bestSeason = "Monsoon";
        System.out.println("LOCATION : " + safari20.location);
        System.out.println("VEHICLE : " + safari20.vehicleType);
        System.out.println("TICKET PRICE : " + safari20.ticketPrice);
        System.out.println("DURATION : " + safari20.durationHours + " hrs");
        System.out.println("GUIDE : " + safari20.includesGuide);
        System.out.println("BEST SEASON : " + safari20.bestSeason);

        System.out.println("MAIN ENDED");
    }
}
