class GiTagRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        GiTag tag1 = new GiTag();
        tag1.productName = "Darjeeling Tea";
        tag1.state = "West Bengal";
        tag1.yearOfRegistration = 2004;
        tag1.category = "Agricultural";
        tag1.isHandcrafted = false;
        tag1.region = "Darjeeling";
        System.out.println("PRODUCT NAME : " + tag1.productName);
        System.out.println("STATE : " + tag1.state);
        System.out.println("YEAR OF REGISTRATION : " + tag1.yearOfRegistration);
        System.out.println("CATEGORY : " + tag1.category);
        System.out.println("HANDCRAFTED : " + tag1.isHandcrafted);
        System.out.println("REGION : " + tag1.region);

        GiTag tag2 = new GiTag();
        tag2.productName = "Kanjeevaram Silk Saree";
        tag2.state = "Tamil Nadu";
        tag2.yearOfRegistration = 2005;
        tag2.category = "Handicraft";
        tag2.isHandcrafted = true;
        tag2.region = "Kanchipuram";
        System.out.println("PRODUCT NAME : " + tag2.productName);
        System.out.println("STATE : " + tag2.state);
        System.out.println("YEAR OF REGISTRATION : " + tag2.yearOfRegistration);
        System.out.println("CATEGORY : " + tag2.category);
        System.out.println("HANDCRAFTED : " + tag2.isHandcrafted);
        System.out.println("REGION : " + tag2.region);

        GiTag tag3 = new GiTag();
        tag3.productName = "Mysore Silk";
        tag3.state = "Karnataka";
        tag3.yearOfRegistration = 2005;
        tag3.category = "Handicraft";
        tag3.isHandcrafted = true;
        tag3.region = "Mysore";
        System.out.println("PRODUCT NAME : " + tag3.productName);
        System.out.println("STATE : " + tag3.state);
        System.out.println("YEAR OF REGISTRATION : " + tag3.yearOfRegistration);
        System.out.println("CATEGORY : " + tag3.category);
        System.out.println("HANDCRAFTED : " + tag3.isHandcrafted);
        System.out.println("REGION : " + tag3.region);

        GiTag tag4 = new GiTag();
        tag4.productName = "Nagpur Orange";
        tag4.state = "Maharashtra";
        tag4.yearOfRegistration = 2014;
        tag4.category = "Agricultural";
        tag4.isHandcrafted = false;
        tag4.region = "Nagpur";
        System.out.println("PRODUCT NAME : " + tag4.productName);
        System.out.println("STATE : " + tag4.state);
        System.out.println("YEAR OF REGISTRATION : " + tag4.yearOfRegistration);
        System.out.println("CATEGORY : " + tag4.category);
        System.out.println("HANDCRAFTED : " + tag4.isHandcrafted);
        System.out.println("REGION : " + tag4.region);

        GiTag tag5 = new GiTag();
        tag5.productName = "Banarasi Saree";
        tag5.state = "Uttar Pradesh";
        tag5.yearOfRegistration = 2009;
        tag5.category = "Handicraft";
        tag5.isHandcrafted = true;
        tag5.region = "Varanasi";
        System.out.println("PRODUCT NAME : " + tag5.productName);
        System.out.println("STATE : " + tag5.state);
        System.out.println("YEAR OF REGISTRATION : " + tag5.yearOfRegistration);
        System.out.println("CATEGORY : " + tag5.category);
        System.out.println("HANDCRAFTED : " + tag5.isHandcrafted);
        System.out.println("REGION : " + tag5.region);

        GiTag tag6 = new GiTag();
        tag6.productName = "Bikaneri Bhujia";
        tag6.state = "Rajasthan";
        tag6.yearOfRegistration = 2010;
        tag6.category = "Foodstuff";
        tag6.isHandcrafted = false;
        tag6.region = "Bikaner";
        System.out.println("PRODUCT NAME : " + tag6.productName);
        System.out.println("STATE : " + tag6.state);
        System.out.println("YEAR OF REGISTRATION : " + tag6.yearOfRegistration);
        System.out.println("CATEGORY : " + tag6.category);
        System.out.println("HANDCRAFTED : " + tag6.isHandcrafted);
        System.out.println("REGION : " + tag6.region);

        GiTag tag7 = new GiTag();
        tag7.productName = "Aranmula Kannadi";
        tag7.state = "Kerala";
        tag7.yearOfRegistration = 2005;
        tag7.category = "Handicraft";
        tag7.isHandcrafted = true;
        tag7.region = "Aranmula";
        System.out.println("PRODUCT NAME : " + tag7.productName);
        System.out.println("STATE : " + tag7.state);
        System.out.println("YEAR OF REGISTRATION : " + tag7.yearOfRegistration);
        System.out.println("CATEGORY : " + tag7.category);
        System.out.println("HANDCRAFTED : " + tag7.isHandcrafted);
        System.out.println("REGION : " + tag7.region);

        GiTag tag8 = new GiTag();
        tag8.productName = "Kashmir Pashmina";
        tag8.state = "Jammu & Kashmir";
        tag8.yearOfRegistration = 2008;
        tag8.category = "Handicraft";
        tag8.isHandcrafted = true;
        tag8.region = "Kashmir";
        System.out.println("PRODUCT NAME : " + tag8.productName);
        System.out.println("STATE : " + tag8.state);
        System.out.println("YEAR OF REGISTRATION : " + tag8.yearOfRegistration);
        System.out.println("CATEGORY : " + tag8.category);
        System.out.println("HANDCRAFTED : " + tag8.isHandcrafted);
        System.out.println("REGION : " + tag8.region);

        GiTag tag9 = new GiTag();
        tag9.productName = "Tirupati Laddu";
        tag9.state = "Andhra Pradesh";
        tag9.yearOfRegistration = 2009;
        tag9.category = "Foodstuff";
        tag9.isHandcrafted = false;
        tag9.region = "Tirupati";
        System.out.println("PRODUCT NAME : " + tag9.productName);
        System.out.println("STATE : " + tag9.state);
        System.out.println("YEAR OF REGISTRATION : " + tag9.yearOfRegistration);
        System.out.println("CATEGORY : " + tag9.category);
        System.out.println("HANDCRAFTED : " + tag9.isHandcrafted);
        System.out.println("REGION : " + tag9.region);

        GiTag tag10 = new GiTag();
        tag10.productName = "Malabar Pepper";
        tag10.state = "Kerala";
        tag10.yearOfRegistration = 2008;
        tag10.category = "Agricultural";
        tag10.isHandcrafted = false;
        tag10.region = "Malabar";
        System.out.println("PRODUCT NAME : " + tag10.productName);
        System.out.println("STATE : " + tag10.state);
        System.out.println("YEAR OF REGISTRATION : " + tag10.yearOfRegistration);
        System.out.println("CATEGORY : " + tag10.category);
        System.out.println("HANDCRAFTED : " + tag10.isHandcrafted);
        System.out.println("REGION : " + tag10.region);

        GiTag tag11 = new GiTag();
        tag11.productName = "Solapur Chaddar";
        tag11.state = "Maharashtra";
        tag11.yearOfRegistration = 2015;
        tag11.category = "Handicraft";
        tag11.isHandcrafted = true;
        tag11.region = "Solapur";
        System.out.println("PRODUCT NAME : " + tag11.productName);
        System.out.println("STATE : " + tag11.state);
        System.out.println("YEAR OF REGISTRATION : " + tag11.yearOfRegistration);
        System.out.println("CATEGORY : " + tag11.category);
        System.out.println("HANDCRAFTED : " + tag11.isHandcrafted);
        System.out.println("REGION : " + tag11.region);

        GiTag tag12 = new GiTag();
        tag12.productName = "Hyderabadi Haleem";
        tag12.state = "Telangana";
        tag12.yearOfRegistration = 2010;
        tag12.category = "Foodstuff";
        tag12.isHandcrafted = false;
        tag12.region = "Hyderabad";
        System.out.println("PRODUCT NAME : " + tag12.productName);
        System.out.println("STATE : " + tag12.state);
        System.out.println("YEAR OF REGISTRATION : " + tag12.yearOfRegistration);
        System.out.println("CATEGORY : " + tag12.category);
        System.out.println("HANDCRAFTED : " + tag12.isHandcrafted);
        System.out.println("REGION : " + tag12.region);

        GiTag tag13 = new GiTag();
        tag13.productName = "Sangli Turmeric";
        tag13.state = "Maharashtra";
        tag13.yearOfRegistration = 2018;
        tag13.category = "Agricultural";
        tag13.isHandcrafted = false;
        tag13.region = "Sangli";
        System.out.println("PRODUCT NAME : " + tag13.productName);
        System.out.println("STATE : " + tag13.state);
        System.out.println("YEAR OF REGISTRATION : " + tag13.yearOfRegistration);
        System.out.println("CATEGORY : " + tag13.category);
        System.out.println("HANDCRAFTED : " + tag13.isHandcrafted);
        System.out.println("REGION : " + tag13.region);

        GiTag tag14 = new GiTag();
        tag14.productName = "Kullu Shawl";
        tag14.state = "Himachal Pradesh";
        tag14.yearOfRegistration = 2009;
        tag14.category = "Handicraft";
        tag14.isHandcrafted = true;
        tag14.region = "Kullu";
        System.out.println("PRODUCT NAME : " + tag14.productName);
        System.out.println("STATE : " + tag14.state);
        System.out.println("YEAR OF REGISTRATION : " + tag14.yearOfRegistration);
        System.out.println("CATEGORY : " + tag14.category);
        System.out.println("HANDCRAFTED : " + tag14.isHandcrafted);
        System.out.println("REGION : " + tag14.region);

        GiTag tag15 = new GiTag();
        tag15.productName = "Alphonso Mango";
        tag15.state = "Maharashtra";
        tag15.yearOfRegistration = 2018;
        tag15.category = "Agricultural";
        tag15.isHandcrafted = false;
        tag15.region = "Ratnagiri";
        System.out.println("PRODUCT NAME : " + tag15.productName);
        System.out.println("STATE : " + tag15.state);
        System.out.println("YEAR OF REGISTRATION : " + tag15.yearOfRegistration);
        System.out.println("CATEGORY : " + tag15.category);
        System.out.println("HANDCRAFTED : " + tag15.isHandcrafted);
        System.out.println("REGION : " + tag15.region);

        GiTag tag16 = new GiTag();
        tag16.productName = "Warli Painting";
        tag16.state = "Maharashtra";
        tag16.yearOfRegistration = 2011;
        tag16.category = "Handicraft";
        tag16.isHandcrafted = true;
        tag16.region = "Thane";
        System.out.println("PRODUCT NAME : " + tag16.productName);
        System.out.println("STATE : " + tag16.state);
        System.out.println("YEAR OF REGISTRATION : " + tag16.yearOfRegistration);
        System.out.println("CATEGORY : " + tag16.category);
        System.out.println("HANDCRAFTED : " + tag16.isHandcrafted);
        System.out.println("REGION : " + tag16.region);

        GiTag tag17 = new GiTag();
        tag17.productName = "Coorg Orange";
        tag17.state = "Karnataka";
        tag17.yearOfRegistration = 2014;
        tag17.category = "Agricultural";
        tag17.isHandcrafted = false;
        tag17.region = "Coorg";
        System.out.println("PRODUCT NAME : " + tag17.productName);
        System.out.println("STATE : " + tag17.state);
        System.out.println("YEAR OF REGISTRATION : " + tag17.yearOfRegistration);
        System.out.println("CATEGORY : " + tag17.category);
        System.out.println("HANDCRAFTED : " + tag17.isHandcrafted);
        System.out.println("REGION : " + tag17.region);

        GiTag tag18 = new GiTag();
        tag18.productName = "Naga Chilli";
        tag18.state = "Nagaland";
        tag18.yearOfRegistration = 2010;
        tag18.category = "Agricultural";
        tag18.isHandcrafted = false;
        tag18.region = "Kohima";
        System.out.println("PRODUCT NAME : " + tag18.productName);
        System.out.println("STATE : " + tag18.state);
        System.out.println("YEAR OF REGISTRATION : " + tag18.yearOfRegistration);
        System.out.println("CATEGORY : " + tag18.category);
        System.out.println("HANDCRAFTED : " + tag18.isHandcrafted);
        System.out.println("REGION : " + tag18.region);

        GiTag tag19 = new GiTag();
        tag19.productName = "Sikkim Large Cardamom";
        tag19.state = "Sikkim";
        tag19.yearOfRegistration = 2010;
        tag19.category = "Agricultural";
        tag19.isHandcrafted = false;
        tag19.region = "Sikkim";
        System.out.println("PRODUCT NAME : " + tag19.productName);
        System.out.println("STATE : " + tag19.state);
        System.out.println("YEAR OF REGISTRATION : " + tag19.yearOfRegistration);
        System.out.println("CATEGORY : " + tag19.category);
        System.out.println("HANDCRAFTED : " + tag19.isHandcrafted);
        System.out.println("REGION : " + tag19.region);

        GiTag tag20 = new GiTag();
        tag20.productName = "Kolhapuri Chappal";
        tag20.state = "Maharashtra";
        tag20.yearOfRegistration = 2009;
        tag20.category = "Handicraft";
        tag20.isHandcrafted = true;
        tag20.region = "Kolhapur";
        System.out.println("PRODUCT NAME : " + tag20.productName);
        System.out.println("STATE : " + tag20.state);
        System.out.println("YEAR OF REGISTRATION : " + tag20.yearOfRegistration);
        System.out.println("CATEGORY : " + tag20.category);
        System.out.println("HANDCRAFTED : " + tag20.isHandcrafted);
        System.out.println("REGION : " + tag20.region);

        System.out.println("MAIN ENDED");
    }
}
