class GymEquipmentRunner {

    public static void main(String gym[]) {
        System.out.println("MAIN STARTED");

        GymEquipment equipment1 = new GymEquipment();
        equipment1.name = "Treadmill";
        equipment1.type = "Cardio";
        equipment1.brand = "PowerMax";
        equipment1.price = 59999.99f;
        equipment1.material = "Steel";
        equipment1.weight = 80f;
        System.out.println("NAME : " + equipment1.name);
        System.out.println("TYPE : " + equipment1.type);
        System.out.println("BRAND : " + equipment1.brand);
        System.out.println("PRICE : " + equipment1.price);
        System.out.println("MATERIAL : " + equipment1.material);
        System.out.println("WEIGHT : " + equipment1.weight + " kg");

        GymEquipment equipment2 = new GymEquipment();
        equipment2.name = "Dumbbell Set";
        equipment2.type = "Strength";
        equipment2.brand = "Kobo";
        equipment2.price = 2999.99f;
        equipment2.material = "Cast Iron";
        equipment2.weight = 20f;
        System.out.println("NAME : " + equipment2.name);
        System.out.println("TYPE : " + equipment2.type);
        System.out.println("BRAND : " + equipment2.brand);
        System.out.println("PRICE : " + equipment2.price);
        System.out.println("MATERIAL : " + equipment2.material);
        System.out.println("WEIGHT : " + equipment2.weight + " kg");

        GymEquipment equipment3 = new GymEquipment();
        equipment3.name = "Exercise Bike";
        equipment3.type = "Cardio";
        equipment3.brand = "Fitkit";
        equipment3.price = 19999.50f;
        equipment3.material = "Steel";
        equipment3.weight = 60f;
        System.out.println("NAME : " + equipment3.name);
        System.out.println("TYPE : " + equipment3.type);
        System.out.println("BRAND : " + equipment3.brand);
        System.out.println("PRICE : " + equipment3.price);
        System.out.println("MATERIAL : " + equipment3.material);
        System.out.println("WEIGHT : " + equipment3.weight + " kg");

        GymEquipment equipment4 = new GymEquipment();
        equipment4.name = "Barbell Rod";
        equipment4.type = "Strength";
        equipment4.brand = "Afton";
        equipment4.price = 2499.75f;
        equipment4.material = "Steel";
        equipment4.weight = 15f;
        System.out.println("NAME : " + equipment4.name);
        System.out.println("TYPE : " + equipment4.type);
        System.out.println("BRAND : " + equipment4.brand);
        System.out.println("PRICE : " + equipment4.price);
        System.out.println("MATERIAL : " + equipment4.material);
        System.out.println("WEIGHT : " + equipment4.weight + " kg");

        GymEquipment equipment5 = new GymEquipment();
        equipment5.name = "Kettlebell";
        equipment5.type = "Strength";
        equipment5.brand = "Protoner";
        equipment5.price = 799.99f;
        equipment5.material = "Cast Iron";
        equipment5.weight = 10f;
        System.out.println("NAME : " + equipment5.name);
        System.out.println("TYPE : " + equipment5.type);
        System.out.println("BRAND : " + equipment5.brand);
        System.out.println("PRICE : " + equipment5.price);
        System.out.println("MATERIAL : " + equipment5.material);
        System.out.println("WEIGHT : " + equipment5.weight + " kg");

        GymEquipment equipment6 = new GymEquipment();
        equipment6.name = "Rowing Machine";
        equipment6.type = "Cardio";
        equipment6.brand = "Durafit";
        equipment6.price = 42999.00f;
        equipment6.material = "Steel";
        equipment6.weight = 70f;
        System.out.println("NAME : " + equipment6.name);
        System.out.println("TYPE : " + equipment6.type);
        System.out.println("BRAND : " + equipment6.brand);
        System.out.println("PRICE : " + equipment6.price);
        System.out.println("MATERIAL : " + equipment6.material);
        System.out.println("WEIGHT : " + equipment6.weight + " kg");

        GymEquipment equipment7 = new GymEquipment();
        equipment7.name = "Smith Machine";
        equipment7.type = "Strength";
        equipment7.brand = "BodyCraft";
        equipment7.price = 74999.50f;
        equipment7.material = "Steel";
        equipment7.weight = 90f;
        System.out.println("NAME : " + equipment7.name);
        System.out.println("TYPE : " + equipment7.type);
        System.out.println("BRAND : " + equipment7.brand);
        System.out.println("PRICE : " + equipment7.price);
        System.out.println("MATERIAL : " + equipment7.material);
        System.out.println("WEIGHT : " + equipment7.weight + " kg");

        GymEquipment equipment8 = new GymEquipment();
        equipment8.name = "Lat Pulldown Machine";
        equipment8.type = "Strength";
        equipment8.brand = "Powerline";
        equipment8.price = 45999.99f;
        equipment8.material = "Steel";
        equipment8.weight = 100f;
        System.out.println("NAME : " + equipment8.name);
        System.out.println("TYPE : " + equipment8.type);
        System.out.println("BRAND : " + equipment8.brand);
        System.out.println("PRICE : " + equipment8.price);
        System.out.println("MATERIAL : " + equipment8.material);
        System.out.println("WEIGHT : " + equipment8.weight + " kg");

        GymEquipment equipment9 = new GymEquipment();
        equipment9.name = "Chest Press Machine";
        equipment9.type = "Strength";
        equipment9.brand = "Lifeline";
        equipment9.price = 53999.75f;
        equipment9.material = "Steel";
        equipment9.weight = 120f;
        System.out.println("NAME : " + equipment9.name);
        System.out.println("TYPE : " + equipment9.type);
        System.out.println("BRAND : " + equipment9.brand);
        System.out.println("PRICE : " + equipment9.price);
        System.out.println("MATERIAL : " + equipment9.material);
        System.out.println("WEIGHT : " + equipment9.weight + " kg");

        GymEquipment equipment10 = new GymEquipment();
        equipment10.name = "Incline Bench";
        equipment10.type = "Strength";
        equipment10.brand = "Reebok";
        equipment10.price = 8999.99f;
        equipment10.material = "Steel & Foam";
        equipment10.weight = 25f;
        System.out.println("NAME : " + equipment10.name);
        System.out.println("TYPE : " + equipment10.type);
        System.out.println("BRAND : " + equipment10.brand);
        System.out.println("PRICE : " + equipment10.price);
        System.out.println("MATERIAL : " + equipment10.material);
        System.out.println("WEIGHT : " + equipment10.weight + " kg");

        GymEquipment equipment11 = new GymEquipment();
        equipment11.name = "Flat Bench";
        equipment11.type = "Strength";
        equipment11.brand = "Domyos";
        equipment11.price = 6999.50f;
        equipment11.material = "Steel & Foam";
        equipment11.weight = 20f;
        System.out.println("NAME : " + equipment11.name);
        System.out.println("TYPE : " + equipment11.type);
        System.out.println("BRAND : " + equipment11.brand);
        System.out.println("PRICE : " + equipment11.price);
        System.out.println("MATERIAL : " + equipment11.material);
        System.out.println("WEIGHT : " + equipment11.weight + " kg");

        GymEquipment equipment12 = new GymEquipment();
        equipment12.name = "Ab Roller";
        equipment12.type = "Core Training";
        equipment12.brand = "Domyos";
        equipment12.price = 999.00f;
        equipment12.material = "Plastic & Steel";
        equipment12.weight = 2f;
        System.out.println("NAME : " + equipment12.name);
        System.out.println("TYPE : " + equipment12.type);
        System.out.println("BRAND : " + equipment12.brand);
        System.out.println("PRICE : " + equipment12.price);
        System.out.println("MATERIAL : " + equipment12.material);
        System.out.println("WEIGHT : " + equipment12.weight + " kg");

        GymEquipment equipment13 = new GymEquipment();
        equipment13.name = "Resistance Bands";
        equipment13.type = "Strength & Flexibility";
        equipment13.brand = "Boldfit";
        equipment13.price = 599.00f;
        equipment13.material = "Latex";
        equipment13.weight = 1f;
        System.out.println("NAME : " + equipment13.name);
        System.out.println("TYPE : " + equipment13.type);
        System.out.println("BRAND : " + equipment13.brand);
        System.out.println("PRICE : " + equipment13.price);
        System.out.println("MATERIAL : " + equipment13.material);
        System.out.println("WEIGHT : " + equipment13.weight + " kg");

        GymEquipment equipment14 = new GymEquipment();
        equipment14.name = "Pull-up Bar";
        equipment14.type = "Strength";
        equipment14.brand = "Protoner";
        equipment14.price = 1999.50f;
        equipment14.material = "Steel";
        equipment14.weight = 5f;
        System.out.println("NAME : " + equipment14.name);
        System.out.println("TYPE : " + equipment14.type);
        System.out.println("BRAND : " + equipment14.brand);
        System.out.println("PRICE : " + equipment14.price);
        System.out.println("MATERIAL : " + equipment14.material);
        System.out.println("WEIGHT : " + equipment14.weight + " kg");

        GymEquipment equipment15 = new GymEquipment();
        equipment15.name = "Leg Press Machine";
        equipment15.type = "Strength";
        equipment15.brand = "FitKing";
        equipment15.price = 89999.00f;
        equipment15.material = "Steel";
        equipment15.weight = 150f;
        System.out.println("NAME : " + equipment15.name);
        System.out.println("TYPE : " + equipment15.type);
        System.out.println("BRAND : " + equipment15.brand);
        System.out.println("PRICE : " + equipment15.price);
        System.out.println("MATERIAL : " + equipment15.material);
        System.out.println("WEIGHT : " + equipment15.weight + " kg");

        GymEquipment equipment16 = new GymEquipment();
        equipment16.name = "Seated Row Machine";
        equipment16.type = "Strength";
        equipment16.brand = "Impulse";
        equipment16.price = 69999.00f;
        equipment16.material = "Steel";
        equipment16.weight = 110f;
        System.out.println("NAME : " + equipment16.name);
        System.out.println("TYPE : " + equipment16.type);
        System.out.println("BRAND : " + equipment16.brand);
        System.out.println("PRICE : " + equipment16.price);
        System.out.println("MATERIAL : " + equipment16.material);
        System.out.println("WEIGHT : " + equipment16.weight + " kg");

        GymEquipment equipment17 = new GymEquipment();
        equipment17.name = "Cross Trainer";
        equipment17.type = "Cardio";
        equipment17.brand = "Sole Fitness";
        equipment17.price = 45999.00f;
        equipment17.material = "Steel";
        equipment17.weight = 75f;
        System.out.println("NAME : " + equipment17.name);
        System.out.println("TYPE : " + equipment17.type);
        System.out.println("BRAND : " + equipment17.brand);
        System.out.println("PRICE : " + equipment17.price);
        System.out.println("MATERIAL : " + equipment17.material);
        System.out.println("WEIGHT : " + equipment17.weight + " kg");

        GymEquipment equipment18 = new GymEquipment();
        equipment18.name = "Stepper Machine";
        equipment18.type = "Cardio";
        equipment18.brand = "Aerofit";
        equipment18.price = 17999.00f;
        equipment18.material = "Steel";
        equipment18.weight = 30f;
        System.out.println("NAME : " + equipment18.name);
        System.out.println("TYPE : " + equipment18.type);
        System.out.println("BRAND : " + equipment18.brand);
        System.out.println("PRICE : " + equipment18.price);
        System.out.println("MATERIAL : " + equipment18.material);
        System.out.println("WEIGHT : " + equipment18.weight + " kg");

        GymEquipment equipment19 = new GymEquipment();
        equipment19.name = "Punching Bag";
        equipment19.type = "Boxing";
        equipment19.brand = "Everlast";
        equipment19.price = 4999.00f;
        equipment19.material = "Synthetic Leather";
        equipment19.weight = 25f;
        System.out.println("NAME : " + equipment19.name);
        System.out.println("TYPE : " + equipment19.type);
        System.out.println("BRAND : " + equipment19.brand);
        System.out.println("PRICE : " + equipment19.price);
        System.out.println("MATERIAL : " + equipment19.material);
        System.out.println("WEIGHT : " + equipment19.weight + " kg");

        GymEquipment equipment20 = new GymEquipment();
        equipment20.name = "Battle Rope";
        equipment20.type = "Functional Training";
        equipment20.brand = "Aurion";
        equipment20.price = 3599.00f;
        equipment20.material = "Poly Dacron";
        equipment20.weight = 12f;
        System.out.println("NAME : " + equipment20.name);
        System.out.println("TYPE : " + equipment20.type);
        System.out.println("BRAND : " + equipment20.brand);
        System.out.println("PRICE : " + equipment20.price);
        System.out.println("MATERIAL : " + equipment20.material);
        System.out.println("WEIGHT : " + equipment20.weight + " kg");

        System.out.println("MAIN ENDED");
    }
}
