class HairClipRunner {

    public static void main(String clip[]) {
        System.out.println("MAIN STARTED");

        HairClip hairClip1 = new HairClip();
        hairClip1.color = "BLACK";
        hairClip1.material = "PLASTIC";
        hairClip1.brand = "Clippy";
        hairClip1.price = 49.99f;
        hairClip1.type = "Alligator Clip";
        hairClip1.size = "Medium";
        System.out.println("COLOR : " + hairClip1.color);
        System.out.println("MATERIAL : " + hairClip1.material);
        System.out.println("BRAND : " + hairClip1.brand);
        System.out.println("PRICE : " + hairClip1.price);
        System.out.println("TYPE : " + hairClip1.type);
        System.out.println("SIZE : " + hairClip1.size);

        HairClip hairClip2 = new HairClip();
        hairClip2.color = "PINK";
        hairClip2.material = "METAL";
        hairClip2.brand = "GlamClips";
        hairClip2.price = 59.99f;
        hairClip2.type = "Snap Clip";
        hairClip2.size = "Small";
        System.out.println("COLOR : " + hairClip2.color);
        System.out.println("MATERIAL : " + hairClip2.material);
        System.out.println("BRAND : " + hairClip2.brand);
        System.out.println("PRICE : " + hairClip2.price);
        System.out.println("TYPE : " + hairClip2.type);
        System.out.println("SIZE : " + hairClip2.size);

        HairClip hairClip3 = new HairClip();
        hairClip3.color = "BLUE";
        hairClip3.material = "ACRYLIC";
        hairClip3.brand = "Hairy";
        hairClip3.price = 79.50f;
        hairClip3.type = "Claw Clip";
        hairClip3.size = "Large";
        System.out.println("COLOR : " + hairClip3.color);
        System.out.println("MATERIAL : " + hairClip3.material);
        System.out.println("BRAND : " + hairClip3.brand);
        System.out.println("PRICE : " + hairClip3.price);
        System.out.println("TYPE : " + hairClip3.type);
        System.out.println("SIZE : " + hairClip3.size);

        HairClip hairClip4 = new HairClip();
        hairClip4.color = "RED";
        hairClip4.material = "PLASTIC";
        hairClip4.brand = "StyleClips";
        hairClip4.price = 69.99f;
        hairClip4.type = "Banana Clip";
        hairClip4.size = "Medium";
        System.out.println("COLOR : " + hairClip4.color);
        System.out.println("MATERIAL : " + hairClip4.material);
        System.out.println("BRAND : " + hairClip4.brand);
        System.out.println("PRICE : " + hairClip4.price);
        System.out.println("TYPE : " + hairClip4.type);
        System.out.println("SIZE : " + hairClip4.size);

        HairClip hairClip5 = new HairClip();
        hairClip5.color = "WHITE";
        hairClip5.material = "METAL";
        hairClip5.brand = "ClipIt";
        hairClip5.price = 89.00f;
        hairClip5.type = "Bobby Pin";
        hairClip5.size = "Small";
        System.out.println("COLOR : " + hairClip5.color);
        System.out.println("MATERIAL : " + hairClip5.material);
        System.out.println("BRAND : " + hairClip5.brand);
        System.out.println("PRICE : " + hairClip5.price);
        System.out.println("TYPE : " + hairClip5.type);
        System.out.println("SIZE : " + hairClip5.size);

        HairClip hairClip6 = new HairClip();
        hairClip6.color = "GOLD";
        hairClip6.material = "METAL";
        hairClip6.brand = "Eleganza";
        hairClip6.price = 129.99f;
        hairClip6.type = "Hair Barrettes";
        hairClip6.size = "Medium";
        System.out.println("COLOR : " + hairClip6.color);
        System.out.println("MATERIAL : " + hairClip6.material);
        System.out.println("BRAND : " + hairClip6.brand);
        System.out.println("PRICE : " + hairClip6.price);
        System.out.println("TYPE : " + hairClip6.type);
        System.out.println("SIZE : " + hairClip6.size);

        HairClip hairClip7 = new HairClip();
        hairClip7.color = "SILVER";
        hairClip7.material = "STEEL";
        hairClip7.brand = "GlamSnap";
        hairClip7.price = 139.50f;
        hairClip7.type = "Snap Clip";
        hairClip7.size = "Large";
        System.out.println("COLOR : " + hairClip7.color);
        System.out.println("MATERIAL : " + hairClip7.material);
        System.out.println("BRAND : " + hairClip7.brand);
        System.out.println("PRICE : " + hairClip7.price);
        System.out.println("TYPE : " + hairClip7.type);
        System.out.println("SIZE : " + hairClip7.size);

        HairClip hairClip8 = new HairClip();
        hairClip8.color = "PURPLE";
        hairClip8.material = "PLASTIC";
        hairClip8.brand = "ClipStar";
        hairClip8.price = 99.99f;
        hairClip8.type = "Claw Clip";
        hairClip8.size = "Medium";
        System.out.println("COLOR : " + hairClip8.color);
        System.out.println("MATERIAL : " + hairClip8.material);
        System.out.println("BRAND : " + hairClip8.brand);
        System.out.println("PRICE : " + hairClip8.price);
        System.out.println("TYPE : " + hairClip8.type);
        System.out.println("SIZE : " + hairClip8.size);

        HairClip hairClip9 = new HairClip();
        hairClip9.color = "BROWN";
        hairClip9.material = "WOOD";
        hairClip9.brand = "EcoClips";
        hairClip9.price = 149.00f;
        hairClip9.type = "Banana Clip";
        hairClip9.size = "Large";
        System.out.println("COLOR : " + hairClip9.color);
        System.out.println("MATERIAL : " + hairClip9.material);
        System.out.println("BRAND : " + hairClip9.brand);
        System.out.println("PRICE : " + hairClip9.price);
        System.out.println("TYPE : " + hairClip9.type);
        System.out.println("SIZE : " + hairClip9.size);

        HairClip hairClip10 = new HairClip();
        hairClip10.color = "GREEN";
        hairClip10.material = "ACRYLIC";
        hairClip10.brand = "HairCharm";
        hairClip10.price = 79.90f;
        hairClip10.type = "Alligator Clip";
        hairClip10.size = "Small";
        System.out.println("COLOR : " + hairClip10.color);
        System.out.println("MATERIAL : " + hairClip10.material);
        System.out.println("BRAND : " + hairClip10.brand);
        System.out.println("PRICE : " + hairClip10.price);
        System.out.println("TYPE : " + hairClip10.type);
        System.out.println("SIZE : " + hairClip10.size);

        HairClip hairClip11 = new HairClip();
        hairClip11.color = "YELLOW";
        hairClip11.material = "PLASTIC";
        hairClip11.brand = "SunnyClips";
        hairClip11.price = 69.99f;
        hairClip11.type = "Snap Clip";
        hairClip11.size = "Medium";
        System.out.println("COLOR : " + hairClip11.color);
        System.out.println("MATERIAL : " + hairClip11.material);
        System.out.println("BRAND : " + hairClip11.brand);
        System.out.println("PRICE : " + hairClip11.price);
        System.out.println("TYPE : " + hairClip11.type);
        System.out.println("SIZE : " + hairClip11.size);

        HairClip hairClip12 = new HairClip();
        hairClip12.color = "ORANGE";
        hairClip12.material = "METAL";
        hairClip12.brand = "ColorClips";
        hairClip12.price = 89.50f;
        hairClip12.type = "Claw Clip";
        hairClip12.size = "Large";
        System.out.println("COLOR : " + hairClip12.color);
        System.out.println("MATERIAL : " + hairClip12.material);
        System.out.println("BRAND : " + hairClip12.brand);
        System.out.println("PRICE : " + hairClip12.price);
        System.out.println("TYPE : " + hairClip12.type);
        System.out.println("SIZE : " + hairClip12.size);

        HairClip hairClip13 = new HairClip();
        hairClip13.color = "CREAM";
        hairClip13.material = "ACRYLIC";
        hairClip13.brand = "ChicClips";
        hairClip13.price = 119.00f;
        hairClip13.type = "Banana Clip";
        hairClip13.size = "Small";
        System.out.println("COLOR : " + hairClip13.color);
        System.out.println("MATERIAL : " + hairClip13.material);
        System.out.println("BRAND : " + hairClip13.brand);
        System.out.println("PRICE : " + hairClip13.price);
        System.out.println("TYPE : " + hairClip13.type);
        System.out.println("SIZE : " + hairClip13.size);

        HairClip hairClip14 = new HairClip();
        hairClip14.color = "MULTI-COLOR";
        hairClip14.material = "PLASTIC";
        hairClip14.brand = "TrendyClips";
        hairClip14.price = 149.50f;
        hairClip14.type = "Alligator Clip";
        hairClip14.size = "Medium";
        System.out.println("COLOR : " + hairClip14.color);
        System.out.println("MATERIAL : " + hairClip14.material);
        System.out.println("BRAND : " + hairClip14.brand);
        System.out.println("PRICE : " + hairClip14.price);
        System.out.println("TYPE : " + hairClip14.type);
        System.out.println("SIZE : " + hairClip14.size);

        HairClip hairClip15 = new HairClip();
        hairClip15.color = "PEACH";
        hairClip15.material = "METAL";
        hairClip15.brand = "GlowClip";
        hairClip15.price = 179.99f;
        hairClip15.type = "Bobby Pin";
        hairClip15.size = "Small";
        System.out.println("COLOR : " + hairClip15.color);
        System.out.println("MATERIAL : " + hairClip15.material);
        System.out.println("BRAND : " + hairClip15.brand);
        System.out.println("PRICE : " + hairClip15.price);
        System.out.println("TYPE : " + hairClip15.type);
        System.out.println("SIZE : " + hairClip15.size);

        HairClip hairClip16 = new HairClip();
        hairClip16.color = "TEAL";
        hairClip16.material = "PLASTIC";
        hairClip16.brand = "OceanClips";
        hairClip16.price = 129.00f;
        hairClip16.type = "Claw Clip";
        hairClip16.size = "Large";
        System.out.println("COLOR : " + hairClip16.color);
        System.out.println("MATERIAL : " + hairClip16.material);
        System.out.println("BRAND : " + hairClip16.brand);
        System.out.println("PRICE : " + hairClip16.price);
        System.out.println("TYPE : " + hairClip16.type);
        System.out.println("SIZE : " + hairClip16.size);

        HairClip hairClip17 = new HairClip();
        hairClip17.color = "NAVY BLUE";
        hairClip17.material = "ACRYLIC";
        hairClip17.brand = "RoyalClips";
        hairClip17.price = 159.50f;
        hairClip17.type = "Snap Clip";
        hairClip17.size = "Medium";
        System.out.println("COLOR : " + hairClip17.color);
        System.out.println("MATERIAL : " + hairClip17.material);
        System.out.println("BRAND : " + hairClip17.brand);
        System.out.println("PRICE : " + hairClip17.price);
        System.out.println("TYPE : " + hairClip17.type);
        System.out.println("SIZE : " + hairClip17.size);

        HairClip hairClip18 = new HairClip();
        hairClip18.color = "ROSE GOLD";
        hairClip18.material = "METAL";
        hairClip18.brand = "LuxuryClips";
        hairClip18.price = 199.00f;
        hairClip18.type = "Hair Barrettes";
        hairClip18.size = "Small";
        System.out.println("COLOR : " + hairClip18.color);
        System.out.println("MATERIAL : " + hairClip18.material);
        System.out.println("BRAND : " + hairClip18.brand);
        System.out.println("PRICE : " + hairClip18.price);
        System.out.println("TYPE : " + hairClip18.type);
        System.out.println("SIZE : " + hairClip18.size);

        HairClip hairClip19 = new HairClip();
        hairClip19.color = "TRANSPARENT";
        hairClip19.material = "PLASTIC";
        hairClip19.brand = "ClearStyle";
        hairClip19.price = 89.99f;
        hairClip19.type = "Alligator Clip";
        hairClip19.size = "Medium";
        System.out.println("COLOR : " + hairClip19.color);
        System.out.println("MATERIAL : " + hairClip19.material);
        System.out.println("BRAND : " + hairClip19.brand);
        System.out.println("PRICE : " + hairClip19.price);
        System.out.println("TYPE : " + hairClip19.type);
        System.out.println("SIZE : " + hairClip19.size);

        HairClip hairClip20 = new HairClip();
        hairClip20.color = "LAVENDER";
        hairClip20.material = "ACRYLIC";
        hairClip20.brand = "FloraClips";
        hairClip20.price = 169.00f;
        hairClip20.type = "Claw Clip";
        hairClip20.size = "Large";
        System.out.println("COLOR : " + hairClip20.color);
        System.out.println("MATERIAL : " + hairClip20.material);
        System.out.println("BRAND : " + hairClip20.brand);
        System.out.println("PRICE : " + hairClip20.price);
        System.out.println("TYPE : " + hairClip20.type);
        System.out.println("SIZE : " + hairClip20.size);

        System.out.println("MAIN ENDED");
    }
}
