class HatRunner {

    public static void main(String hatArray[]) {
        System.out.println("MAIN STARTED");

        Hat hat1 = new Hat();
        hat1.brand = "Adidas";
        hat1.color = "Black";
        hat1.material = "Cotton";
        hat1.style = "Baseball";
        hat1.size = "L";
        hat1.price = 999.99f;
        System.out.println("BRAND : " + hat1.brand);
        System.out.println("COLOR : " + hat1.color);
        System.out.println("MATERIAL : " + hat1.material);
        System.out.println("STYLE : " + hat1.style);
        System.out.println("SIZE : " + hat1.size);
        System.out.println("PRICE : " + hat1.price);

        Hat hat2 = new Hat();
        hat2.brand = "Nike";
        hat2.color = "White";
        hat2.material = "Polyester";
        hat2.style = "Snapback";
        hat2.size = "M";
        hat2.price = 1099.50f;
        System.out.println("BRAND : " + hat2.brand);
        System.out.println("COLOR : " + hat2.color);
        System.out.println("MATERIAL : " + hat2.material);
        System.out.println("STYLE : " + hat2.style);
        System.out.println("SIZE : " + hat2.size);
        System.out.println("PRICE : " + hat2.price);

        Hat hat3 = new Hat();
        hat3.brand = "Puma";
        hat3.color = "Blue";
        hat3.material = "Cotton Blend";
        hat3.style = "Trucker";
        hat3.size = "XL";
        hat3.price = 799.00f;
        System.out.println("BRAND : " + hat3.brand);
        System.out.println("COLOR : " + hat3.color);
        System.out.println("MATERIAL : " + hat3.material);
        System.out.println("STYLE : " + hat3.style);
        System.out.println("SIZE : " + hat3.size);
        System.out.println("PRICE : " + hat3.price);

        Hat hat4 = new Hat();
        hat4.brand = "Levi's";
        hat4.color = "Grey";
        hat4.material = "Denim";
        hat4.style = "Bucket";
        hat4.size = "L";
        hat4.price = 1199.75f;
        System.out.println("BRAND : " + hat4.brand);
        System.out.println("COLOR : " + hat4.color);
        System.out.println("MATERIAL : " + hat4.material);
        System.out.println("STYLE : " + hat4.style);
        System.out.println("SIZE : " + hat4.size);
        System.out.println("PRICE : " + hat4.price);

        Hat hat5 = new Hat();
        hat5.brand = "Under Armour";
        hat5.color = "Green";
        hat5.material = "Nylon";
        hat5.style = "Baseball";
        hat5.size = "M";
        hat5.price = 899.00f;
        System.out.println("BRAND : " + hat5.brand);
        System.out.println("COLOR : " + hat5.color);
        System.out.println("MATERIAL : " + hat5.material);
        System.out.println("STYLE : " + hat5.style);
        System.out.println("SIZE : " + hat5.size);
        System.out.println("PRICE : " + hat5.price);

        Hat hat6 = new Hat();
        hat6.brand = "New Era";
        hat6.color = "Navy Blue";
        hat6.material = "Polyester";
        hat6.style = "Snapback";
        hat6.size = "L";
        hat6.price = 1350.00f;
        System.out.println("BRAND : " + hat6.brand);
        System.out.println("COLOR : " + hat6.color);
        System.out.println("MATERIAL : " + hat6.material);
        System.out.println("STYLE : " + hat6.style);
        System.out.println("SIZE : " + hat6.size);
        System.out.println("PRICE : " + hat6.price);

        Hat hat7 = new Hat();
        hat7.brand = "Fila";
        hat7.color = "Yellow";
        hat7.material = "Cotton";
        hat7.style = "Trucker";
        hat7.size = "XL";
        hat7.price = 950.00f;
        System.out.println("BRAND : " + hat7.brand);
        System.out.println("COLOR : " + hat7.color);
        System.out.println("MATERIAL : " + hat7.material);
        System.out.println("STYLE : " + hat7.style);
        System.out.println("SIZE : " + hat7.size);
        System.out.println("PRICE : " + hat7.price);

        Hat hat8 = new Hat();
        hat8.brand = "Gucci";
        hat8.color = "Brown";
        hat8.material = "Leather";
        hat8.style = "Fedora";
        hat8.size = "M";
        hat8.price = 5999.00f;
        System.out.println("BRAND : " + hat8.brand);
        System.out.println("COLOR : " + hat8.color);
        System.out.println("MATERIAL : " + hat8.material);
        System.out.println("STYLE : " + hat8.style);
        System.out.println("SIZE : " + hat8.size);
        System.out.println("PRICE : " + hat8.price);

        Hat hat9 = new Hat();
        hat9.brand = "H&M";
        hat9.color = "Beige";
        hat9.material = "Straw";
        hat9.style = "Panama";
        hat9.size = "L";
        hat9.price = 1299.00f;
        System.out.println("BRAND : " + hat9.brand);
        System.out.println("COLOR : " + hat9.color);
        System.out.println("MATERIAL : " + hat9.material);
        System.out.println("STYLE : " + hat9.style);
        System.out.println("SIZE : " + hat9.size);
        System.out.println("PRICE : " + hat9.price);

        Hat hat10 = new Hat();
        hat10.brand = "Zara";
        hat10.color = "White";
        hat10.material = "Cotton";
        hat10.style = "Sun Hat";
        hat10.size = "M";
        hat10.price = 1499.00f;
        System.out.println("BRAND : " + hat10.brand);
        System.out.println("COLOR : " + hat10.color);
        System.out.println("MATERIAL : " + hat10.material);
        System.out.println("STYLE : " + hat10.style);
        System.out.println("SIZE : " + hat10.size);
        System.out.println("PRICE : " + hat10.price);

        Hat hat11 = new Hat();
        hat11.brand = "Adidas";
        hat11.color = "Red";
        hat11.material = "Polyester";
        hat11.style = "Snapback";
        hat11.size = "L";
        hat11.price = 1199.00f;
        System.out.println("BRAND : " + hat11.brand);
        System.out.println("COLOR : " + hat11.color);
        System.out.println("MATERIAL : " + hat11.material);
        System.out.println("STYLE : " + hat11.style);
        System.out.println("SIZE : " + hat11.size);
        System.out.println("PRICE : " + hat11.price);

        Hat hat12 = new Hat();
        hat12.brand = "Puma";
        hat12.color = "Grey";
        hat12.material = "Cotton";
        hat12.style = "Baseball";
        hat12.size = "XL";
        hat12.price = 1099.00f;
        System.out.println("BRAND : " + hat12.brand);
        System.out.println("COLOR : " + hat12.color);
        System.out.println("MATERIAL : " + hat12.material);
        System.out.println("STYLE : " + hat12.style);
        System.out.println("SIZE : " + hat12.size);
        System.out.println("PRICE : " + hat12.price);

        Hat hat13 = new Hat();
        hat13.brand = "Levi's";
        hat13.color = "Blue";
        hat13.material = "Denim";
        hat13.style = "Trucker";
        hat13.size = "M";
        hat13.price = 999.00f;
        System.out.println("BRAND : " + hat13.brand);
        System.out.println("COLOR : " + hat13.color);
        System.out.println("MATERIAL : " + hat13.material);
        System.out.println("STYLE : " + hat13.style);
        System.out.println("SIZE : " + hat13.size);
        System.out.println("PRICE : " + hat13.price);

        Hat hat14 = new Hat();
        hat14.brand = "Tommy Hilfiger";
        hat14.color = "Black";
        hat14.material = "Cotton";
        hat14.style = "Baseball";
        hat14.size = "M";
        hat14.price = 1799.00f;
        System.out.println("BRAND : " + hat14.brand);
        System.out.println("COLOR : " + hat14.color);
        System.out.println("MATERIAL : " + hat14.material);
        System.out.println("STYLE : " + hat14.style);
        System.out.println("SIZE : " + hat14.size);
        System.out.println("PRICE : " + hat14.price);

        Hat hat15 = new Hat();
        hat15.brand = "Reebok";
        hat15.color = "Green";
        hat15.material = "Polyester";
        hat15.style = "Snapback";
        hat15.size = "XL";
        hat15.price = 899.00f;
        System.out.println("BRAND : " + hat15.brand);
        System.out.println("COLOR : " + hat15.color);
        System.out.println("MATERIAL : " + hat15.material);
        System.out.println("STYLE : " + hat15.style);
        System.out.println("SIZE : " + hat15.size);
        System.out.println("PRICE : " + hat15.price);

        Hat hat16 = new Hat();
        hat16.brand = "Under Armour";
        hat16.color = "Orange";
        hat16.material = "Nylon";
        hat16.style = "Trucker";
        hat16.size = "L";
        hat16.price = 950.00f;
        System.out.println("BRAND : " + hat16.brand);
        System.out.println("COLOR : " + hat16.color);
        System.out.println("MATERIAL : " + hat16.material);
        System.out.println("STYLE : " + hat16.style);
        System.out.println("SIZE : " + hat16.size);
        System.out.println("PRICE : " + hat16.price);

        Hat hat17 = new Hat();
        hat17.brand = "H&M";
        hat17.color = "Brown";
        hat17.material = "Straw";
        hat17.style = "Panama";
        hat17.size = "M";
        hat17.price = 1299.00f;
        System.out.println("BRAND : " + hat17.brand);
        System.out.println("COLOR : " + hat17.color);
        System.out.println("MATERIAL : " + hat17.material);
        System.out.println("STYLE : " + hat17.style);
        System.out.println("SIZE : " + hat17.size);
        System.out.println("PRICE : " + hat17.price);

        Hat hat18 = new Hat();
        hat18.brand = "Gucci";
        hat18.color = "Black";
        hat18.material = "Leather";
        hat18.style = "Fedora";
        hat18.size = "L";
        hat18.price = 5999.00f;
        System.out.println("BRAND : " + hat18.brand);
        System.out.println("COLOR : " + hat18.color);
        System.out.println("MATERIAL : " + hat18.material);
        System.out.println("STYLE : " + hat18.style);
        System.out.println("SIZE : " + hat18.size);
        System.out.println("PRICE : " + hat18.price);

        Hat hat19 = new Hat();
        hat19.brand = "Zara";
        hat19.color = "Cream";
        hat19.material = "Cotton";
        hat19.style = "Sun Hat";
        hat19.size = "XL";
        hat19.price = 1499.00f;
        System.out.println("BRAND : " + hat19.brand);
        System.out.println("COLOR : " + hat19.color);
        System.out.println("MATERIAL : " + hat19.material);
        System.out.println("STYLE : " + hat19.style);
        System.out.println("SIZE : " + hat19.size);
        System.out.println("PRICE : " + hat19.price);

        Hat hat20 = new Hat();
        hat20.brand = "Nike";
        hat20.color = "Blue";
        hat20.material = "Polyester";
        hat20.style = "Baseball";
        hat20.size = "M";
        hat20.price = 1099.00f;
        System.out.println("BRAND : " + hat20.brand);
        System.out.println("COLOR : " + hat20.color);
        System.out.println("MATERIAL : " + hat20.material);
        System.out.println("STYLE : " + hat20.style);
        System.out.println("SIZE : " + hat20.size);
        System.out.println("PRICE : " + hat20.price);

        System.out.println("MAIN ENDED");
    }
}
