class InvitationCardRunner {

    public static void main(String cardArray[]) {
        System.out.println("MAIN STARTED");

        InvitationCard card1 = new InvitationCard();
        card1.occasion = "Wedding";
        card1.color = "Red & Gold";
        card1.size = "A5";
        card1.material = "Glossy Paper";
        card1.design = "Floral Pattern";
        card1.price = 50.0f;
        System.out.println("OCCASION : " + card1.occasion);
        System.out.println("COLOR : " + card1.color);
        System.out.println("SIZE : " + card1.size);
        System.out.println("MATERIAL : " + card1.material);
        System.out.println("DESIGN : " + card1.design);
        System.out.println("PRICE : " + card1.price);

        InvitationCard card2 = new InvitationCard();
        card2.occasion = "Birthday";
        card2.color = "Blue & Silver";
        card2.size = "A6";
        card2.material = "Matte Paper";
        card2.design = "Balloon Theme";
        card2.price = 25.0f;
        System.out.println("OCCASION : " + card2.occasion);
        System.out.println("COLOR : " + card2.color);
        System.out.println("SIZE : " + card2.size);
        System.out.println("MATERIAL : " + card2.material);
        System.out.println("DESIGN : " + card2.design);
        System.out.println("PRICE : " + card2.price);

        InvitationCard card3 = new InvitationCard();
        card3.occasion = "Housewarming";
        card3.color = "Green & Cream";
        card3.size = "A5";
        card3.material = "Handmade Paper";
        card3.design = "Minimalist Design";
        card3.price = 40.0f;
        System.out.println("OCCASION : " + card3.occasion);
        System.out.println("COLOR : " + card3.color);
        System.out.println("SIZE : " + card3.size);
        System.out.println("MATERIAL : " + card3.material);
        System.out.println("DESIGN : " + card3.design);
        System.out.println("PRICE : " + card3.price);

        InvitationCard card4 = new InvitationCard();
        card4.occasion = "Engagement";
        card4.color = "Purple & Gold";
        card4.size = "A4";
        card4.material = "Glossy Paper";
        card4.design = "Traditional Motifs";
        card4.price = 55.0f;
        System.out.println("OCCASION : " + card4.occasion);
        System.out.println("COLOR : " + card4.color);
        System.out.println("SIZE : " + card4.size);
        System.out.println("MATERIAL : " + card4.material);
        System.out.println("DESIGN : " + card4.design);
        System.out.println("PRICE : " + card4.price);

        InvitationCard card5 = new InvitationCard();
        card5.occasion = "Anniversary";
        card5.color = "White & Silver";
        card5.size = "A5";
        card5.material = "Matte Paper";
        card5.design = "Heart Patterns";
        card5.price = 35.0f;
        System.out.println("OCCASION : " + card5.occasion);
        System.out.println("COLOR : " + card5.color);
        System.out.println("SIZE : " + card5.size);
        System.out.println("MATERIAL : " + card5.material);
        System.out.println("DESIGN : " + card5.design);
        System.out.println("PRICE : " + card5.price);

        InvitationCard card6 = new InvitationCard();
        card6.occasion = "Baby Shower";
        card6.color = "Pink & White";
        card6.size = "A6";
        card6.material = "Glossy Paper";
        card6.design = "Cartoon Theme";
        card6.price = 28.0f;
        System.out.println("OCCASION : " + card6.occasion);
        System.out.println("COLOR : " + card6.color);
        System.out.println("SIZE : " + card6.size);
        System.out.println("MATERIAL : " + card6.material);
        System.out.println("DESIGN : " + card6.design);
        System.out.println("PRICE : " + card6.price);

        InvitationCard card7 = new InvitationCard();
        card7.occasion = "Graduation";
        card7.color = "Black & Gold";
        card7.size = "A5";
        card7.material = "Matte Paper";
        card7.design = "Modern Fonts";
        card7.price = 30.0f;
        System.out.println("OCCASION : " + card7.occasion);
        System.out.println("COLOR : " + card7.color);
        System.out.println("SIZE : " + card7.size);
        System.out.println("MATERIAL : " + card7.material);
        System.out.println("DESIGN : " + card7.design);
        System.out.println("PRICE : " + card7.price);

        InvitationCard card8 = new InvitationCard();
        card8.occasion = "Retirement";
        card8.color = "Brown & Cream";
        card8.size = "A5";
        card8.material = "Handmade Paper";
        card8.design = "Classic Pattern";
        card8.price = 42.0f;
        System.out.println("OCCASION : " + card8.occasion);
        System.out.println("COLOR : " + card8.color);
        System.out.println("SIZE : " + card8.size);
        System.out.println("MATERIAL : " + card8.material);
        System.out.println("DESIGN : " + card8.design);
        System.out.println("PRICE : " + card8.price);

        InvitationCard card9 = new InvitationCard();
        card9.occasion = "Farewell";
        card9.color = "Yellow & White";
        card9.size = "A5";
        card9.material = "Glossy Paper";
        card9.design = "Farewell Theme";
        card9.price = 38.0f;
        System.out.println("OCCASION : " + card9.occasion);
        System.out.println("COLOR : " + card9.color);
        System.out.println("SIZE : " + card9.size);
        System.out.println("MATERIAL : " + card9.material);
        System.out.println("DESIGN : " + card9.design);
        System.out.println("PRICE : " + card9.price);

        InvitationCard card10 = new InvitationCard();
        card10.occasion = "Corporate Event";
        card10.color = "Blue & White";
        card10.size = "A4";
        card10.material = "Matte Paper";
        card10.design = "Professional Design";
        card10.price = 60.0f;
        System.out.println("OCCASION : " + card10.occasion);
        System.out.println("COLOR : " + card10.color);
        System.out.println("SIZE : " + card10.size);
        System.out.println("MATERIAL : " + card10.material);
        System.out.println("DESIGN : " + card10.design);
        System.out.println("PRICE : " + card10.price);

        InvitationCard card11 = new InvitationCard();
        card11.occasion = "Festival Party";
        card11.color = "Red & Green";
        card11.size = "A6";
        card11.material = "Glossy Paper";
        card11.design = "Diwali Theme";
        card11.price = 32.0f;
        System.out.println("OCCASION : " + card11.occasion);
        System.out.println("COLOR : " + card11.color);
        System.out.println("SIZE : " + card11.size);
        System.out.println("MATERIAL : " + card11.material);
        System.out.println("DESIGN : " + card11.design);
        System.out.println("PRICE : " + card11.price);

        InvitationCard card12 = new InvitationCard();
        card12.occasion = "Inauguration";
        card12.color = "White & Gold";
        card12.size = "A4";
        card12.material = "Handmade Paper";
        card12.design = "Elegant Design";
        card12.price = 55.0f;
        System.out.println("OCCASION : " + card12.occasion);
        System.out.println("COLOR : " + card12.color);
        System.out.println("SIZE : " + card12.size);
        System.out.println("MATERIAL : " + card12.material);
        System.out.println("DESIGN : " + card12.design);
        System.out.println("PRICE : " + card12.price);

        InvitationCard card13 = new InvitationCard();
        card13.occasion = "Baby Naming Ceremony";
        card13.color = "Pink & Yellow";
        card13.size = "A6";
        card13.material = "Matte Paper";
        card13.design = "Cute Cartoon";
        card13.price = 30.0f;
        System.out.println("OCCASION : " + card13.occasion);
        System.out.println("COLOR : " + card13.color);
        System.out.println("SIZE : " + card13.size);
        System.out.println("MATERIAL : " + card13.material);
        System.out.println("DESIGN : " + card13.design);
        System.out.println("PRICE : " + card13.price);

        InvitationCard card14 = new InvitationCard();
        card14.occasion = "Bachelor Party";
        card14.color = "Black & Silver";
        card14.size = "A5";
        card14.material = "Glossy Paper";
        card14.design = "Modern Graphics";
        card14.price = 40.0f;
        System.out.println("OCCASION : " + card14.occasion);
        System.out.println("COLOR : " + card14.color);
        System.out.println("SIZE : " + card14.size);
        System.out.println("MATERIAL : " + card14.material);
        System.out.println("DESIGN : " + card14.design);
        System.out.println("PRICE : " + card14.price);

        InvitationCard card15 = new InvitationCard();
        card15.occasion = "Bridal Shower";
        card15.color = "Peach & White";
        card15.size = "A6";
        card15.material = "Matte Paper";
        card15.design = "Floral Borders";
        card15.price = 28.0f;
        System.out.println("OCCASION : " + card15.occasion);
        System.out.println("COLOR : " + card15.color);
        System.out.println("SIZE : " + card15.size);
        System.out.println("MATERIAL : " + card15.material);
        System.out.println("DESIGN : " + card15.design);
        System.out.println("PRICE : " + card15.price);

        InvitationCard card16 = new InvitationCard();
        card16.occasion = "Music Concert";
        card16.color = "Red & Black";
        card16.size = "A5";
        card16.material = "Glossy Paper";
        card16.design = "Rock Theme";
        card16.price = 35.0f;
        System.out.println("OCCASION : " + card16.occasion);
        System.out.println("COLOR : " + card16.color);
        System.out.println("SIZE : " + card16.size);
        System.out.println("MATERIAL : " + card16.material);
        System.out.println("DESIGN : " + card16.design);
        System.out.println("PRICE : " + card16.price);

        InvitationCard card17 = new InvitationCard();
        card17.occasion = "Sports Event";
        card17.color = "Orange & White";
        card17.size = "A4";
        card17.material = "Matte Paper";
        card17.design = "Sports Icons";
        card17.price = 45.0f;
        System.out.println("OCCASION : " + card17.occasion);
        System.out.println("COLOR : " + card17.color);
        System.out.println("SIZE : " + card17.size);
        System.out.println("MATERIAL : " + card17.material);
        System.out.println("DESIGN : " + card17.design);
        System.out.println("PRICE : " + card17.price);

        InvitationCard card18 = new InvitationCard();
        card18.occasion = "Charity Gala";
        card18.color = "White & Purple";
        card18.size = "A5";
        card18.material = "Handmade Paper";
        card18.design = "Premium Design";
        card18.price = 60.0f;
        System.out.println("OCCASION : " + card18.occasion);
        System.out.println("COLOR : " + card18.color);
        System.out.println("SIZE : " + card18.size);
        System.out.println("MATERIAL : " + card18.material);
        System.out.println("DESIGN : " + card18.design);
        System.out.println("PRICE : " + card18.price);

        InvitationCard card19 = new InvitationCard();
        card19.occasion = "Art Exhibition";
        card19.color = "Blue & Beige";
        card19.size = "A6";
        card19.material = "Glossy Paper";
        card19.design = "Abstract Art";
        card19.price = 38.0f;
        System.out.println("OCCASION : " + card19.occasion);
        System.out.println("COLOR : " + card19.color);
        System.out.println("SIZE : " + card19.size);
        System.out.println("MATERIAL : " + card19.material);
        System.out.println("DESIGN : " + card19.design);
        System.out.println("PRICE : " + card19.price);

        InvitationCard card20 = new InvitationCard();
        card20.occasion = "Festival Gathering";
        card20.color = "Maroon & Gold";
        card20.size = "A5";
        card20.material = "Matte Paper";
        card20.design = "Indian Motifs";
        card20.price = 50.0f;
        System.out.println("OCCASION : " + card20.occasion);
        System.out.println("COLOR : " + card20.color);
        System.out.println("SIZE : " + card20.size);
        System.out.println("MATERIAL : " + card20.material);
        System.out.println("DESIGN : " + card20.design);
        System.out.println("PRICE : " + card20.price);

        System.out.println("MAIN ENDED");
    }
}
