class JewelleryRunner {

    public static void main(String jewel[]) {
        System.out.println("MAIN STARTED");

        Jewellery jewellery1 = new Jewellery();
        jewellery1.name = "Gold Ring";
        jewellery1.type = "Ring";
        jewellery1.material = "22K Gold";
        jewellery1.brand = "Tanishq";
        jewellery1.price = 25000.50f;
        jewellery1.weight = 4.5f;
        System.out.println("NAME : " + jewellery1.name);
        System.out.println("TYPE : " + jewellery1.type);
        System.out.println("MATERIAL : " + jewellery1.material);
        System.out.println("BRAND : " + jewellery1.brand);
        System.out.println("PRICE : " + jewellery1.price);
        System.out.println("WEIGHT : " + jewellery1.weight + " g");

        Jewellery jewellery2 = new Jewellery();
        jewellery2.name = "Diamond Necklace";
        jewellery2.type = "Necklace";
        jewellery2.material = "Diamond & Platinum";
        jewellery2.brand = "Kalyan Jewellers";
        jewellery2.price = 150000.75f;
        jewellery2.weight = 20f;
        System.out.println("NAME : " + jewellery2.name);
        System.out.println("TYPE : " + jewellery2.type);
        System.out.println("MATERIAL : " + jewellery2.material);
        System.out.println("BRAND : " + jewellery2.brand);
        System.out.println("PRICE : " + jewellery2.price);
        System.out.println("WEIGHT : " + jewellery2.weight + " g");

        Jewellery jewellery3 = new Jewellery();
        jewellery3.name = "Silver Bracelet";
        jewellery3.type = "Bracelet";
        jewellery3.material = "Sterling Silver";
        jewellery3.brand = "Malabar Gold";
        jewellery3.price = 5000.99f;
        jewellery3.weight = 12.5f;
        System.out.println("NAME : " + jewellery3.name);
        System.out.println("TYPE : " + jewellery3.type);
        System.out.println("MATERIAL : " + jewellery3.material);
        System.out.println("BRAND : " + jewellery3.brand);
        System.out.println("PRICE : " + jewellery3.price);
        System.out.println("WEIGHT : " + jewellery3.weight + " g");

        Jewellery jewellery4 = new Jewellery();
        jewellery4.name = "Pearl Earrings";
        jewellery4.type = "Earrings";
        jewellery4.material = "Pearl & Silver";
        jewellery4.brand = "CaratLane";
        jewellery4.price = 7999.50f;
        jewellery4.weight = 8.0f;
        System.out.println("NAME : " + jewellery4.name);
        System.out.println("TYPE : " + jewellery4.type);
        System.out.println("MATERIAL : " + jewellery4.material);
        System.out.println("BRAND : " + jewellery4.brand);
        System.out.println("PRICE : " + jewellery4.price);
        System.out.println("WEIGHT : " + jewellery4.weight + " g");

        Jewellery jewellery5 = new Jewellery();
        jewellery5.name = "Platinum Chain";
        jewellery5.type = "Chain";
        jewellery5.material = "Platinum";
        jewellery5.brand = "Joyalukkas";
        jewellery5.price = 120000.00f;
        jewellery5.weight = 25f;
        System.out.println("NAME : " + jewellery5.name);
        System.out.println("TYPE : " + jewellery5.type);
        System.out.println("MATERIAL : " + jewellery5.material);
        System.out.println("BRAND : " + jewellery5.brand);
        System.out.println("PRICE : " + jewellery5.price);
        System.out.println("WEIGHT : " + jewellery5.weight + " g");

        Jewellery jewellery6 = new Jewellery();
        jewellery6.name = "Gold Bangles";
        jewellery6.type = "Bangles";
        jewellery6.material = "22K Gold";
        jewellery6.brand = "Tanishq";
        jewellery6.price = 60000.00f;
        jewellery6.weight = 30f;
        System.out.println("NAME : " + jewellery6.name);
        System.out.println("TYPE : " + jewellery6.type);
        System.out.println("MATERIAL : " + jewellery6.material);
        System.out.println("BRAND : " + jewellery6.brand);
        System.out.println("PRICE : " + jewellery6.price);
        System.out.println("WEIGHT : " + jewellery6.weight + " g");

        Jewellery jewellery7 = new Jewellery();
        jewellery7.name = "Diamond Ring";
        jewellery7.type = "Ring";
        jewellery7.material = "Diamond & Gold";
        jewellery7.brand = "CaratLane";
        jewellery7.price = 35000.99f;
        jewellery7.weight = 5.5f;
        System.out.println("NAME : " + jewellery7.name);
        System.out.println("TYPE : " + jewellery7.type);
        System.out.println("MATERIAL : " + jewellery7.material);
        System.out.println("BRAND : " + jewellery7.brand);
        System.out.println("PRICE : " + jewellery7.price);
        System.out.println("WEIGHT : " + jewellery7.weight + " g");

        Jewellery jewellery8 = new Jewellery();
        jewellery8.name = "Emerald Pendant";
        jewellery8.type = "Pendant";
        jewellery8.material = "Gold & Emerald";
        jewellery8.brand = "Malabar Gold";
        jewellery8.price = 45000.00f;
        jewellery8.weight = 10f;
        System.out.println("NAME : " + jewellery8.name);
        System.out.println("TYPE : " + jewellery8.type);
        System.out.println("MATERIAL : " + jewellery8.material);
        System.out.println("BRAND : " + jewellery8.brand);
        System.out.println("PRICE : " + jewellery8.price);
        System.out.println("WEIGHT : " + jewellery8.weight + " g");

        Jewellery jewellery9 = new Jewellery();
        jewellery9.name = "Ruby Earrings";
        jewellery9.type = "Earrings";
        jewellery9.material = "Gold & Ruby";
        jewellery9.brand = "Kalyan Jewellers";
        jewellery9.price = 28000.00f;
        jewellery9.weight = 9.0f;
        System.out.println("NAME : " + jewellery9.name);
        System.out.println("TYPE : " + jewellery9.type);
        System.out.println("MATERIAL : " + jewellery9.material);
        System.out.println("BRAND : " + jewellery9.brand);
        System.out.println("PRICE : " + jewellery9.price);
        System.out.println("WEIGHT : " + jewellery9.weight + " g");

        Jewellery jewellery10 = new Jewellery();
        jewellery10.name = "Silver Anklet";
        jewellery10.type = "Anklet";
        jewellery10.material = "Sterling Silver";
        jewellery10.brand = "PNG Jewellers";
        jewellery10.price = 3500.00f;
        jewellery10.weight = 15.0f;
        System.out.println("NAME : " + jewellery10.name);
        System.out.println("TYPE : " + jewellery10.type);
        System.out.println("MATERIAL : " + jewellery10.material);
        System.out.println("BRAND : " + jewellery10.brand);
        System.out.println("PRICE : " + jewellery10.price);
        System.out.println("WEIGHT : " + jewellery10.weight + " g");

        Jewellery jewellery11 = new Jewellery();
        jewellery11.name = "Pearl Necklace";
        jewellery11.type = "Necklace";
        jewellery11.material = "Pearl & Silver";
        jewellery11.brand = "Senco Gold";
        jewellery11.price = 22000.00f;
        jewellery11.weight = 22f;
        System.out.println("NAME : " + jewellery11.name);
        System.out.println("TYPE : " + jewellery11.type);
        System.out.println("MATERIAL : " + jewellery11.material);
        System.out.println("BRAND : " + jewellery11.brand);
        System.out.println("PRICE : " + jewellery11.price);
        System.out.println("WEIGHT : " + jewellery11.weight + " g");

        Jewellery jewellery12 = new Jewellery();
        jewellery12.name = "Platinum Ring";
        jewellery12.type = "Ring";
        jewellery12.material = "Platinum";
        jewellery12.brand = "Joyalukkas";
        jewellery12.price = 60000.00f;
        jewellery12.weight = 6f;
        System.out.println("NAME : " + jewellery12.name);
        System.out.println("TYPE : " + jewellery12.type);
        System.out.println("MATERIAL : " + jewellery12.material);
        System.out.println("BRAND : " + jewellery12.brand);
        System.out.println("PRICE : " + jewellery12.price);
        System.out.println("WEIGHT : " + jewellery12.weight + " g");

        Jewellery jewellery13 = new Jewellery();
        jewellery13.name = "Sapphire Earrings";
        jewellery13.type = "Earrings";
        jewellery13.material = "Gold & Sapphire";
        jewellery13.brand = "CaratLane";
        jewellery13.price = 32000.00f;
        jewellery13.weight = 7.0f;
        System.out.println("NAME : " + jewellery13.name);
        System.out.println("TYPE : " + jewellery13.type);
        System.out.println("MATERIAL : " + jewellery13.material);
        System.out.println("BRAND : " + jewellery13.brand);
        System.out.println("PRICE : " + jewellery13.price);
        System.out.println("WEIGHT : " + jewellery13.weight + " g");

        Jewellery jewellery14 = new Jewellery();
        jewellery14.name = "Gold Chain";
        jewellery14.type = "Chain";
        jewellery14.material = "22K Gold";
        jewellery14.brand = "Tanishq";
        jewellery14.price = 75000.00f;
        jewellery14.weight = 28f;
        System.out.println("NAME : " + jewellery14.name);
        System.out.println("TYPE : " + jewellery14.type);
        System.out.println("MATERIAL : " + jewellery14.material);
        System.out.println("BRAND : " + jewellery14.brand);
        System.out.println("PRICE : " + jewellery14.price);
        System.out.println("WEIGHT : " + jewellery14.weight + " g");

        Jewellery jewellery15 = new Jewellery();
        jewellery15.name = "Emerald Ring";
        jewellery15.type = "Ring";
        jewellery15.material = "Gold & Emerald";
        jewellery15.brand = "Malabar Gold";
        jewellery15.price = 28000.00f;
        jewellery15.weight = 4.5f;
        System.out.println("NAME : " + jewellery15.name);
        System.out.println("TYPE : " + jewellery15.type);
        System.out.println("MATERIAL : " + jewellery15.material);
        System.out.println("BRAND : " + jewellery15.brand);
        System.out.println("PRICE : " + jewellery15.price);
        System.out.println("WEIGHT : " + jewellery15.weight + " g");

        Jewellery jewellery16 = new Jewellery();
        jewellery16.name = "Platinum Bracelet";
        jewellery16.type = "Bracelet";
        jewellery16.material = "Platinum";
        jewellery16.brand = "Joyalukkas";
        jewellery16.price = 95000.00f;
        jewellery16.weight = 18.0f;
        System.out.println("NAME : " + jewellery16.name);
        System.out.println("TYPE : " + jewellery16.type);
        System.out.println("MATERIAL : " + jewellery16.material);
        System.out.println("BRAND : " + jewellery16.brand);
        System.out.println("PRICE : " + jewellery16.price);
        System.out.println("WEIGHT : " + jewellery16.weight + " g");

        Jewellery jewellery17 = new Jewellery();
        jewellery17.name = "Gold Earrings";
        jewellery17.type = "Earrings";
        jewellery17.material = "22K Gold";
        jewellery17.brand = "Kalyan Jewellers";
        jewellery17.price = 21000.00f;
        jewellery17.weight = 6.0f;
        System.out.println("NAME : " + jewellery17.name);
        System.out.println("TYPE : " + jewellery17.type);
        System.out.println("MATERIAL : " + jewellery17.material);
        System.out.println("BRAND : " + jewellery17.brand);
        System.out.println("PRICE : " + jewellery17.price);
        System.out.println("WEIGHT : " + jewellery17.weight + " g");

        Jewellery jewellery18 = new Jewellery();
        jewellery18.name = "Pearl Bracelet";
        jewellery18.type = "Bracelet";
        jewellery18.material = "Pearl & Gold";
        jewellery18.brand = "CaratLane";
        jewellery18.price = 12000.00f;
        jewellery18.weight = 10f;
        System.out.println("NAME : " + jewellery18.name);
        System.out.println("TYPE : " + jewellery18.type);
        System.out.println("MATERIAL : " + jewellery18.material);
        System.out.println("BRAND : " + jewellery18.brand);
        System.out.println("PRICE : " + jewellery18.price);
        System.out.println("WEIGHT : " + jewellery18.weight + " g");

        Jewellery jewellery19 = new Jewellery();
        jewellery19.name = "Platinum Pendant";
        jewellery19.type = "Pendant";
        jewellery19.material = "Platinum";
        jewellery19.brand = "Joyalukkas";
        jewellery19.price = 40000.00f;
        jewellery19.weight = 9.0f;
        System.out.println("NAME : " + jewellery19.name);
        System.out.println("TYPE : " + jewellery19.type);
        System.out.println("MATERIAL : " + jewellery19.material);
        System.out.println("BRAND : " + jewellery19.brand);
        System.out.println("PRICE : " + jewellery19.price);
        System.out.println("WEIGHT : " + jewellery19.weight + " g");

        Jewellery jewellery20 = new Jewellery();
        jewellery20.name = "Silver Toe Ring";
        jewellery20.type = "Toe Ring";
        jewellery20.material = "Sterling Silver";
        jewellery20.brand = "PNG Jewellers";
        jewellery20.price = 1800.00f;
        jewellery20.weight = 3.0f;
        System.out.println("NAME : " + jewellery20.name);
        System.out.println("TYPE : " + jewellery20.type);
        System.out.println("MATERIAL : " + jewellery20.material);
        System.out.println("BRAND : " + jewellery20.brand);
        System.out.println("PRICE : " + jewellery20.price);
        System.out.println("WEIGHT : " + jewellery20.weight + " g");

        System.out.println("MAIN ENDED");
    }
}
