class MarbleRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Marble marble1 = new Marble();
        marble1.color = "White";
        marble1.type = "Italian";
        marble1.origin = "Italy";
        marble1.pricePerKg = 450.50f;
        marble1.isPolished = true;
        marble1.pattern = "Veined";
        System.out.println("COLOR : " + marble1.color);
        System.out.println("TYPE : " + marble1.type);
        System.out.println("ORIGIN : " + marble1.origin);
        System.out.println("PRICE/KG : " + marble1.pricePerKg);
        System.out.println("POLISHED : " + marble1.isPolished);
        System.out.println("PATTERN : " + marble1.pattern);

        Marble marble2 = new Marble();
        marble2.color = "Green";
        marble2.type = "Indian Green";
        marble2.origin = "India";
        marble2.pricePerKg = 300.00f;
        marble2.isPolished = false;
        marble2.pattern = "Plain";
        System.out.println("COLOR : " + marble2.color);
        System.out.println("TYPE : " + marble2.type);
        System.out.println("ORIGIN : " + marble2.origin);
        System.out.println("PRICE/KG : " + marble2.pricePerKg);
        System.out.println("POLISHED : " + marble2.isPolished);
        System.out.println("PATTERN : " + marble2.pattern);

        Marble marble3 = new Marble();
        marble3.color = "Black";
        marble3.type = "Nero Marquina";
        marble3.origin = "Spain";
        marble3.pricePerKg = 550.75f;
        marble3.isPolished = true;
        marble3.pattern = "Solid";
        System.out.println("COLOR : " + marble3.color);
        System.out.println("TYPE : " + marble3.type);
        System.out.println("ORIGIN : " + marble3.origin);
        System.out.println("PRICE/KG : " + marble3.pricePerKg);
        System.out.println("POLISHED : " + marble3.isPolished);
        System.out.println("PATTERN : " + marble3.pattern);

        Marble marble4 = new Marble();
        marble4.color = "Pink";
        marble4.type = "Makrana Pink";
        marble4.origin = "India";
        marble4.pricePerKg = 400.25f;
        marble4.isPolished = false;
        marble4.pattern = "Grainy";
        System.out.println("COLOR : " + marble4.color);
        System.out.println("TYPE : " + marble4.type);
        System.out.println("ORIGIN : " + marble4.origin);
        System.out.println("PRICE/KG : " + marble4.pricePerKg);
        System.out.println("POLISHED : " + marble4.isPolished);
        System.out.println("PATTERN : " + marble4.pattern);

        Marble marble5 = new Marble();
        marble5.color = "Beige";
        marble5.type = "Crema Marfil";
        marble5.origin = "Spain";
        marble5.pricePerKg = 600.00f;
        marble5.isPolished = true;
        marble5.pattern = "Veined";
        System.out.println("COLOR : " + marble5.color);
        System.out.println("TYPE : " + marble5.type);
        System.out.println("ORIGIN : " + marble5.origin);
        System.out.println("PRICE/KG : " + marble5.pricePerKg);
        System.out.println("POLISHED : " + marble5.isPolished);
        System.out.println("PATTERN : " + marble5.pattern);

        Marble marble6 = new Marble();
        marble6.color = "Grey";
        marble6.type = "Pacific Grey";
        marble6.origin = "China";
        marble6.pricePerKg = 350.00f;
        marble6.isPolished = false;
        marble6.pattern = "Cloudy";
        System.out.println("COLOR : " + marble6.color);
        System.out.println("TYPE : " + marble6.type);
        System.out.println("ORIGIN : " + marble6.origin);
        System.out.println("PRICE/KG : " + marble6.pricePerKg);
        System.out.println("POLISHED : " + marble6.isPolished);
        System.out.println("PATTERN : " + marble6.pattern);

        Marble marble7 = new Marble();
        marble7.color = "Yellow";
        marble7.type = "Jaisalmer Yellow";
        marble7.origin = "India";
        marble7.pricePerKg = 280.50f;
        marble7.isPolished = false;
        marble7.pattern = "Plain";
        System.out.println("COLOR : " + marble7.color);
        System.out.println("TYPE : " + marble7.type);
        System.out.println("ORIGIN : " + marble7.origin);
        System.out.println("PRICE/KG : " + marble7.pricePerKg);
        System.out.println("POLISHED : " + marble7.isPolished);
        System.out.println("PATTERN : " + marble7.pattern);

        Marble marble8 = new Marble();
        marble8.color = "Brown";
        marble8.type = "Dark Emperador";
        marble8.origin = "Spain";
        marble8.pricePerKg = 480.00f;
        marble8.isPolished = true;
        marble8.pattern = "Spider";
        System.out.println("COLOR : " + marble8.color);
        System.out.println("TYPE : " + marble8.type);
        System.out.println("ORIGIN : " + marble8.origin);
        System.out.println("PRICE/KG : " + marble8.pricePerKg);
        System.out.println("POLISHED : " + marble8.isPolished);
        System.out.println("PATTERN : " + marble8.pattern);

        Marble marble9 = new Marble();
        marble9.color = "Blue";
        marble9.type = "Azul Macaubas";
        marble9.origin = "Brazil";
        marble9.pricePerKg = 900.00f;
        marble9.isPolished = true;
        marble9.pattern = "Striped";
        System.out.println("COLOR : " + marble9.color);
        System.out.println("TYPE : " + marble9.type);
        System.out.println("ORIGIN : " + marble9.origin);
        System.out.println("PRICE/KG : " + marble9.pricePerKg);
        System.out.println("POLISHED : " + marble9.isPolished);
        System.out.println("PATTERN : " + marble9.pattern);

        Marble marble10 = new Marble();
        marble10.color = "Gold";
        marble10.type = "Golden Portoro";
        marble10.origin = "Italy";
        marble10.pricePerKg = 1200.00f;
        marble10.isPolished = true;
        marble10.pattern = "Veined";
        System.out.println("COLOR : " + marble10.color);
        System.out.println("TYPE : " + marble10.type);
        System.out.println("ORIGIN : " + marble10.origin);
        System.out.println("PRICE/KG : " + marble10.pricePerKg);
        System.out.println("POLISHED : " + marble10.isPolished);
        System.out.println("PATTERN : " + marble10.pattern);

        Marble marble11 = new Marble();
        marble11.color = "Ivory";
        marble11.type = "Indian Ivory";
        marble11.origin = "India";
        marble11.pricePerKg = 320.00f;
        marble11.isPolished = false;
        marble11.pattern = "Plain";
        System.out.println("COLOR : " + marble11.color);
        System.out.println("TYPE : " + marble11.type);
        System.out.println("ORIGIN : " + marble11.origin);
        System.out.println("PRICE/KG : " + marble11.pricePerKg);
        System.out.println("POLISHED : " + marble11.isPolished);
        System.out.println("PATTERN : " + marble11.pattern);

        Marble marble12 = new Marble();
        marble12.color = "Green";
        marble12.type = "Forest Green";
        marble12.origin = "India";
        marble12.pricePerKg = 380.00f;
        marble12.isPolished = true;
        marble12.pattern = "Leafy";
        System.out.println("COLOR : " + marble12.color);
        System.out.println("TYPE : " + marble12.type);
        System.out.println("ORIGIN : " + marble12.origin);
        System.out.println("PRICE/KG : " + marble12.pricePerKg);
        System.out.println("POLISHED : " + marble12.isPolished);
        System.out.println("PATTERN : " + marble12.pattern);

        Marble marble13 = new Marble();
        marble13.color = "Black";
        marble13.type = "Black Galaxy";
        marble13.origin = "India";
        marble13.pricePerKg = 750.00f;
        marble13.isPolished = true;
        marble13.pattern = "Speckled";
        System.out.println("COLOR : " + marble13.color);
        System.out.println("TYPE : " + marble13.type);
        System.out.println("ORIGIN : " + marble13.origin);
        System.out.println("PRICE/KG : " + marble13.pricePerKg);
        System.out.println("POLISHED : " + marble13.isPolished);
        System.out.println("PATTERN : " + marble13.pattern);

        Marble marble14 = new Marble();
        marble14.color = "Cream";
        marble14.type = "Botticino";
        marble14.origin = "Italy";
        marble14.pricePerKg = 620.00f;
        marble14.isPolished = true;
        marble14.pattern = "Veined";
        System.out.println("COLOR : " + marble14.color);
        System.out.println("TYPE : " + marble14.type);
        System.out.println("ORIGIN : " + marble14.origin);
        System.out.println("PRICE/KG : " + marble14.pricePerKg);
        System.out.println("POLISHED : " + marble14.isPolished);
        System.out.println("PATTERN : " + marble14.pattern);

        Marble marble15 = new Marble();
        marble15.color = "Brown";
        marble15.type = "Rain Forest Brown";
        marble15.origin = "India";
        marble15.pricePerKg = 580.00f;
        marble15.isPolished = false;
        marble15.pattern = "Leafy";
        System.out.println("COLOR : " + marble15.color);
        System.out.println("TYPE : " + marble15.type);
        System.out.println("ORIGIN : " + marble15.origin);
        System.out.println("PRICE/KG : " + marble15.pricePerKg);
        System.out.println("POLISHED : " + marble15.isPolished);
        System.out.println("PATTERN : " + marble15.pattern);

        Marble marble16 = new Marble();
        marble16.color = "Red";
        marble16.type = "Rosso Alicante";
        marble16.origin = "Spain";
        marble16.pricePerKg = 860.00f;
        marble16.isPolished = true;
        marble16.pattern = "Veined";
        System.out.println("COLOR : " + marble16.color);
        System.out.println("TYPE : " + marble16.type);
        System.out.println("ORIGIN : " + marble16.origin);
        System.out.println("PRICE/KG : " + marble16.pricePerKg);
        System.out.println("POLISHED : " + marble16.isPolished);
        System.out.println("PATTERN : " + marble16.pattern);

        Marble marble17 = new Marble();
        marble17.color = "White";
        marble17.type = "Makrana White";
        marble17.origin = "India";
        marble17.pricePerKg = 500.00f;
        marble17.isPolished = true;
        marble17.pattern = "Plain";
        System.out.println("COLOR : " + marble17.color);
        System.out.println("TYPE : " + marble17.type);
        System.out.println("ORIGIN : " + marble17.origin);
        System.out.println("PRICE/KG : " + marble17.pricePerKg);
        System.out.println("POLISHED : " + marble17.isPolished);
        System.out.println("PATTERN : " + marble17.pattern);

        Marble marble18 = new Marble();
        marble18.color = "Purple";
        marble18.type = "Lilac Marble";
        marble18.origin = "Turkey";
        marble18.pricePerKg = 980.00f;
        marble18.isPolished = true;
        marble18.pattern = "Striped";
        System.out.println("COLOR : " + marble18.color);
        System.out.println("TYPE : " + marble18.type);
        System.out.println("ORIGIN : " + marble18.origin);
        System.out.println("PRICE/KG : " + marble18.pricePerKg);
        System.out.println("POLISHED : " + marble18.isPolished);
        System.out.println("PATTERN : " + marble18.pattern);

        Marble marble19 = new Marble();
        marble19.color = "Green";
        marble19.type = "Emerald Marble";
        marble19.origin = "Brazil";
        marble19.pricePerKg = 1050.00f;
        marble19.isPolished = true;
        marble19.pattern = "Crystalline";
        System.out.println("COLOR : " + marble19.color);
        System.out.println("TYPE : " + marble19.type);
        System.out.println("ORIGIN : " + marble19.origin);
        System.out.println("PRICE/KG : " + marble19.pricePerKg);
        System.out.println("POLISHED : " + marble19.isPolished);
        System.out.println("PATTERN : " + marble19.pattern);

        Marble marble20 = new Marble();
        marble20.color = "Silver";
        marble20.type = "Silver Travertine";
        marble20.origin = "Turkey";
        marble20.pricePerKg = 1100.00f;
        marble20.isPolished = false;
        marble20.pattern = "Linear";
        System.out.println("COLOR : " + marble20.color);
        System.out.println("TYPE : " + marble20.type);
        System.out.println("ORIGIN : " + marble20.origin);
        System.out.println("PRICE/KG : " + marble20.pricePerKg);
        System.out.println("POLISHED : " + marble20.isPolished);
        System.out.println("PATTERN : " + marble20.pattern);

        System.out.println("MAIN ENDED");
    }
}
