class NetworkRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Network network1 = new Network();
        network1.name = "Airtel";
        network1.type = "5G";
        network1.speed = 300.5f;
        network1.price = 499.0f;
        network1.country = "India";
        network1.isUnlimited = true;
        System.out.println("NAME : " + network1.name);
        System.out.println("TYPE : " + network1.type);
        System.out.println("SPEED : " + network1.speed + " Mbps");
        System.out.println("PRICE : " + network1.price);
        System.out.println("COUNTRY : " + network1.country);
        System.out.println("UNLIMITED : " + network1.isUnlimited);

        Network network2 = new Network();
        network2.name = "Jio";
        network2.type = "5G";
        network2.speed = 350.0f;
        network2.price = 399.0f;
        network2.country = "India";
        network2.isUnlimited = true;
        System.out.println("NAME : " + network2.name);
        System.out.println("TYPE : " + network2.type);
        System.out.println("SPEED : " + network2.speed + " Mbps");
        System.out.println("PRICE : " + network2.price);
        System.out.println("COUNTRY : " + network2.country);
        System.out.println("UNLIMITED : " + network2.isUnlimited);

        Network network3 = new Network();
        network3.name = "Vodafone Idea";
        network3.type = "4G";
        network3.speed = 150.0f;
        network3.price = 299.0f;
        network3.country = "India";
        network3.isUnlimited = false;
        System.out.println("NAME : " + network3.name);
        System.out.println("TYPE : " + network3.type);
        System.out.println("SPEED : " + network3.speed + " Mbps");
        System.out.println("PRICE : " + network3.price);
        System.out.println("COUNTRY : " + network3.country);
        System.out.println("UNLIMITED : " + network3.isUnlimited);

        Network network4 = new Network();
        network4.name = "BSNL";
        network4.type = "4G";
        network4.speed = 100.0f;
        network4.price = 249.0f;
        network4.country = "India";
        network4.isUnlimited = false;
        System.out.println("NAME : " + network4.name);
        System.out.println("TYPE : " + network4.type);
        System.out.println("SPEED : " + network4.speed + " Mbps");
        System.out.println("PRICE : " + network4.price);
        System.out.println("COUNTRY : " + network4.country);
        System.out.println("UNLIMITED : " + network4.isUnlimited);

        Network network5 = new Network();
        network5.name = "AT&T";
        network5.type = "5G";
        network5.speed = 400.0f;
        network5.price = 999.0f;
        network5.country = "USA";
        network5.isUnlimited = true;
        System.out.println("NAME : " + network5.name);
        System.out.println("TYPE : " + network5.type);
        System.out.println("SPEED : " + network5.speed + " Mbps");
        System.out.println("PRICE : " + network5.price);
        System.out.println("COUNTRY : " + network5.country);
        System.out.println("UNLIMITED : " + network5.isUnlimited);

        Network network6 = new Network();
        network6.name = "Verizon";
        network6.type = "5G";
        network6.speed = 420.0f;
        network6.price = 1099.0f;
        network6.country = "USA";
        network6.isUnlimited = true;
        System.out.println("NAME : " + network6.name);
        System.out.println("TYPE : " + network6.type);
        System.out.println("SPEED : " + network6.speed + " Mbps");
        System.out.println("PRICE : " + network6.price);
        System.out.println("COUNTRY : " + network6.country);
        System.out.println("UNLIMITED : " + network6.isUnlimited);

        Network network7 = new Network();
        network7.name = "T-Mobile";
        network7.type = "5G";
        network7.speed = 380.0f;
        network7.price = 950.0f;
        network7.country = "USA";
        network7.isUnlimited = true;
        System.out.println("NAME : " + network7.name);
        System.out.println("TYPE : " + network7.type);
        System.out.println("SPEED : " + network7.speed + " Mbps");
        System.out.println("PRICE : " + network7.price);
        System.out.println("COUNTRY : " + network7.country);
        System.out.println("UNLIMITED : " + network7.isUnlimited);

        Network network8 = new Network();
        network8.name = "BT Broadband";
        network8.type = "Broadband";
        network8.speed = 70.0f;
        network8.price = 799.0f;
        network8.country = "UK";
        network8.isUnlimited = true;
        System.out.println("NAME : " + network8.name);
        System.out.println("TYPE : " + network8.type);
        System.out.println("SPEED : " + network8.speed + " Mbps");
        System.out.println("PRICE : " + network8.price);
        System.out.println("COUNTRY : " + network8.country);
        System.out.println("UNLIMITED : " + network8.isUnlimited);

        Network network9 = new Network();
        network9.name = "EE";
        network9.type = "5G";
        network9.speed = 370.0f;
        network9.price = 899.0f;
        network9.country = "UK";
        network9.isUnlimited = true;
        System.out.println("NAME : " + network9.name);
        System.out.println("TYPE : " + network9.type);
        System.out.println("SPEED : " + network9.speed + " Mbps");
        System.out.println("PRICE : " + network9.price);
        System.out.println("COUNTRY : " + network9.country);
        System.out.println("UNLIMITED : " + network9.isUnlimited);

        Network network10 = new Network();
        network10.name = "O2";
        network10.type = "4G";
        network10.speed = 120.0f;
        network10.price = 650.0f;
        network10.country = "UK";
        network10.isUnlimited = false;
        System.out.println("NAME : " + network10.name);
        System.out.println("TYPE : " + network10.type);
        System.out.println("SPEED : " + network10.speed + " Mbps");
        System.out.println("PRICE : " + network10.price);
        System.out.println("COUNTRY : " + network10.country);
        System.out.println("UNLIMITED : " + network10.isUnlimited);

        Network network11 = new Network();
        network11.name = "Spectrum";
        network11.type = "Broadband";
        network11.speed = 100.0f;
        network11.price = 1200.0f;
        network11.country = "USA";
        network11.isUnlimited = true;
        System.out.println("NAME : " + network11.name);
        System.out.println("TYPE : " + network11.type);
        System.out.println("SPEED : " + network11.speed + " Mbps");
        System.out.println("PRICE : " + network11.price);
        System.out.println("COUNTRY : " + network11.country);
        System.out.println("UNLIMITED : " + network11.isUnlimited);

        Network network12 = new Network();
        network12.name = "Comcast Xfinity";
        network12.type = "Broadband";
        network12.speed = 120.0f;
        network12.price = 1500.0f;
        network12.country = "USA";
        network12.isUnlimited = true;
        System.out.println("NAME : " + network12.name);
        System.out.println("TYPE : " + network12.type);
        System.out.println("SPEED : " + network12.speed + " Mbps");
        System.out.println("PRICE : " + network12.price);
        System.out.println("COUNTRY : " + network12.country);
        System.out.println("UNLIMITED : " + network12.isUnlimited);

        Network network13 = new Network();
        network13.name = "Idea Broadband";
        network13.type = "Broadband";
        network13.speed = 60.0f;
        network13.price = 599.0f;
        network13.country = "India";
        network13.isUnlimited = false;
        System.out.println("NAME : " + network13.name);
        System.out.println("TYPE : " + network13.type);
        System.out.println("SPEED : " + network13.speed + " Mbps");
        System.out.println("PRICE : " + network13.price);
        System.out.println("COUNTRY : " + network13.country);
        System.out.println("UNLIMITED : " + network13.isUnlimited);

        Network network14 = new Network();
        network14.name = "MTNL";
        network14.type = "4G";
        network14.speed = 90.0f;
        network14.price = 399.0f;
        network14.country = "India";
        network14.isUnlimited = false;
        System.out.println("NAME : " + network14.name);
        System.out.println("TYPE : " + network14.type);
        System.out.println("SPEED : " + network14.speed + " Mbps");
        System.out.println("PRICE : " + network14.price);
        System.out.println("COUNTRY : " + network14.country);
        System.out.println("UNLIMITED : " + network14.isUnlimited);

        Network network15 = new Network();
        network15.name = "Google Fiber";
        network15.type = "Broadband";
        network15.speed = 1000.0f;
        network15.price = 2000.0f;
        network15.country = "USA";
        network15.isUnlimited = true;
        System.out.println("NAME : " + network15.name);
        System.out.println("TYPE : " + network15.type);
        System.out.println("SPEED : " + network15.speed + " Mbps");
        System.out.println("PRICE : " + network15.price);
        System.out.println("COUNTRY : " + network15.country);
        System.out.println("UNLIMITED : " + network15.isUnlimited);

        Network network16 = new Network();
        network16.name = "ACT Fibernet";
        network16.type = "Broadband";
        network16.speed = 500.0f;
        network16.price = 1299.0f;
        network16.country = "India";
        network16.isUnlimited = true;
        System.out.println("NAME : " + network16.name);
        System.out.println("TYPE : " + network16.type);
        System.out.println("SPEED : " + network16.speed + " Mbps");
        System.out.println("PRICE : " + network16.price);
        System.out.println("COUNTRY : " + network16.country);
        System.out.println("UNLIMITED : " + network16.isUnlimited);

        Network network17 = new Network();
        network17.name = "Reliance Netconnect";
        network17.type = "4G";
        network17.speed = 70.0f;
        network17.price = 450.0f;
        network17.country = "India";
        network17.isUnlimited = false;
        System.out.println("NAME : " + network17.name);
        System.out.println("TYPE : " + network17.type);
        System.out.println("SPEED : " + network17.speed + " Mbps");
        System.out.println("PRICE : " + network17.price);
        System.out.println("COUNTRY : " + network17.country);
        System.out.println("UNLIMITED : " + network17.isUnlimited);

        Network network18 = new Network();
        network18.name = "Tata Play Fiber";
        network18.type = "Broadband";
        network18.speed = 300.0f;
        network18.price = 999.0f;
        network18.country = "India";
        network18.isUnlimited = true;
        System.out.println("NAME : " + network18.name);
        System.out.println("TYPE : " + network18.type);
        System.out.println("SPEED : " + network18.speed + " Mbps");
        System.out.println("PRICE : " + network18.price);
        System.out.println("COUNTRY : " + network18.country);
        System.out.println("UNLIMITED : " + network18.isUnlimited);

        Network network19 = new Network();
        network19.name = "Hathway";
        network19.type = "Broadband";
        network19.speed = 200.0f;
        network19.price = 899.0f;
        network19.country = "India";
        network19.isUnlimited = true;
        System.out.println("NAME : " + network19.name);
        System.out.println("TYPE : " + network19.type);
        System.out.println("SPEED : " + network19.speed + " Mbps");
        System.out.println("PRICE : " + network19.price);
        System.out.println("COUNTRY : " + network19.country);
        System.out.println("UNLIMITED : " + network19.isUnlimited);

        Network network20 = new Network();
        network20.name = "BSNL Fiber";
        network20.type = "Broadband";
        network20.speed = 150.0f;
        network20.price = 849.0f;
        network20.country = "India";
        network20.isUnlimited = true;
        System.out.println("NAME : " + network20.name);
        System.out.println("TYPE : " + network20.type);
        System.out.println("SPEED : " + network20.speed + " Mbps");
        System.out.println("PRICE : " + network20.price);
        System.out.println("COUNTRY : " + network20.country);
        System.out.println("UNLIMITED : " + network20.isUnlimited);

        System.out.println("MAIN ENDED");
    }
}
