class PipeRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Pipe pipe1 = new Pipe();
        pipe1.material = "PVC";
        pipe1.length = 3.0f;
        pipe1.diameter = 2.5f;
        pipe1.color = "White";
        pipe1.price = 250.0f;
        pipe1.isFlexible = false;
        System.out.println("MATERIAL : " + pipe1.material);
        System.out.println("LENGTH : " + pipe1.length + " m");
        System.out.println("DIAMETER : " + pipe1.diameter + " inch");
        System.out.println("COLOR : " + pipe1.color);
        System.out.println("PRICE : " + pipe1.price);
        System.out.println("IS FLEXIBLE : " + pipe1.isFlexible);

        Pipe pipe2 = new Pipe();
        pipe2.material = "Steel";
        pipe2.length = 4.5f;
        pipe2.diameter = 3.0f;
        pipe2.color = "Silver";
        pipe2.price = 450.0f;
        pipe2.isFlexible = false;
        System.out.println("MATERIAL : " + pipe2.material);
        System.out.println("LENGTH : " + pipe2.length + " m");
        System.out.println("DIAMETER : " + pipe2.diameter + " inch");
        System.out.println("COLOR : " + pipe2.color);
        System.out.println("PRICE : " + pipe2.price);
        System.out.println("IS FLEXIBLE : " + pipe2.isFlexible);

        Pipe pipe3 = new Pipe();
        pipe3.material = "Copper";
        pipe3.length = 2.0f;
        pipe3.diameter = 1.5f;
        pipe3.color = "Brown";
        pipe3.price = 600.0f;
        pipe3.isFlexible = false;
        System.out.println("MATERIAL : " + pipe3.material);
        System.out.println("LENGTH : " + pipe3.length + " m");
        System.out.println("DIAMETER : " + pipe3.diameter + " inch");
        System.out.println("COLOR : " + pipe3.color);
        System.out.println("PRICE : " + pipe3.price);
        System.out.println("IS FLEXIBLE : " + pipe3.isFlexible);

        Pipe pipe4 = new Pipe();
        pipe4.material = "Plastic";
        pipe4.length = 5.0f;
        pipe4.diameter = 4.0f;
        pipe4.color = "Blue";
        pipe4.price = 150.0f;
        pipe4.isFlexible = true;
        System.out.println("MATERIAL : " + pipe4.material);
        System.out.println("LENGTH : " + pipe4.length + " m");
        System.out.println("DIAMETER : " + pipe4.diameter + " inch");
        System.out.println("COLOR : " + pipe4.color);
        System.out.println("PRICE : " + pipe4.price);
        System.out.println("IS FLEXIBLE : " + pipe4.isFlexible);

        Pipe pipe5 = new Pipe();
        pipe5.material = "Aluminium";
        pipe5.length = 3.5f;
        pipe5.diameter = 2.0f;
        pipe5.color = "Silver";
        pipe5.price = 320.0f;
        pipe5.isFlexible = false;
        System.out.println("MATERIAL : " + pipe5.material);
        System.out.println("LENGTH : " + pipe5.length + " m");
        System.out.println("DIAMETER : " + pipe5.diameter + " inch");
        System.out.println("COLOR : " + pipe5.color);
        System.out.println("PRICE : " + pipe5.price);
        System.out.println("IS FLEXIBLE : " + pipe5.isFlexible);

        Pipe pipe6 = new Pipe();
        pipe6.material = "HDPE";
        pipe6.length = 6.0f;
        pipe6.diameter = 3.5f;
        pipe6.color = "Black";
        pipe6.price = 400.0f;
        pipe6.isFlexible = true;
        System.out.println("MATERIAL : " + pipe6.material);
        System.out.println("LENGTH : " + pipe6.length + " m");
        System.out.println("DIAMETER : " + pipe6.diameter + " inch");
        System.out.println("COLOR : " + pipe6.color);
        System.out.println("PRICE : " + pipe6.price);
        System.out.println("IS FLEXIBLE : " + pipe6.isFlexible);

        Pipe pipe7 = new Pipe();
        pipe7.material = "Cast Iron";
        pipe7.length = 4.0f;
        pipe7.diameter = 2.0f;
        pipe7.color = "Grey";
        pipe7.price = 700.0f;
        pipe7.isFlexible = false;
        System.out.println("MATERIAL : " + pipe7.material);
        System.out.println("LENGTH : " + pipe7.length + " m");
        System.out.println("DIAMETER : " + pipe7.diameter + " inch");
        System.out.println("COLOR : " + pipe7.color);
        System.out.println("PRICE : " + pipe7.price);
        System.out.println("IS FLEXIBLE : " + pipe7.isFlexible);

        Pipe pipe8 = new Pipe();
        pipe8.material = "Galvanized Steel";
        pipe8.length = 3.2f;
        pipe8.diameter = 1.0f;
        pipe8.color = "Silver";
        pipe8.price = 500.0f;
        pipe8.isFlexible = false;
        System.out.println("MATERIAL : " + pipe8.material);
        System.out.println("LENGTH : " + pipe8.length + " m");
        System.out.println("DIAMETER : " + pipe8.diameter + " inch");
        System.out.println("COLOR : " + pipe8.color);
        System.out.println("PRICE : " + pipe8.price);
        System.out.println("IS FLEXIBLE : " + pipe8.isFlexible);

        Pipe pipe9 = new Pipe();
        pipe9.material = "Rubber";
        pipe9.length = 5.0f;
        pipe9.diameter = 1.5f;
        pipe9.color = "Black";
        pipe9.price = 200.0f;
        pipe9.isFlexible = true;
        System.out.println("MATERIAL : " + pipe9.material);
        System.out.println("LENGTH : " + pipe9.length + " m");
        System.out.println("DIAMETER : " + pipe9.diameter + " inch");
        System.out.println("COLOR : " + pipe9.color);
        System.out.println("PRICE : " + pipe9.price);
        System.out.println("IS FLEXIBLE : " + pipe9.isFlexible);

        Pipe pipe10 = new Pipe();
        pipe10.material = "Brass";
        pipe10.length = 2.5f;
        pipe10.diameter = 1.2f;
        pipe10.color = "Golden";
        pipe10.price = 800.0f;
        pipe10.isFlexible = false;
        System.out.println("MATERIAL : " + pipe10.material);
        System.out.println("LENGTH : " + pipe10.length + " m");
        System.out.println("DIAMETER : " + pipe10.diameter + " inch");
        System.out.println("COLOR : " + pipe10.color);
        System.out.println("PRICE : " + pipe10.price);
        System.out.println("IS FLEXIBLE : " + pipe10.isFlexible);

        Pipe pipe11 = new Pipe();
        pipe11.material = "PVC";
        pipe11.length = 7.0f;
        pipe11.diameter = 5.0f;
        pipe11.color = "White";
        pipe11.price = 600.0f;
        pipe11.isFlexible = false;
        System.out.println("MATERIAL : " + pipe11.material);
        System.out.println("LENGTH : " + pipe11.length + " m");
        System.out.println("DIAMETER : " + pipe11.diameter + " inch");
        System.out.println("COLOR : " + pipe11.color);
        System.out.println("PRICE : " + pipe11.price);
        System.out.println("IS FLEXIBLE : " + pipe11.isFlexible);

        Pipe pipe12 = new Pipe();
        pipe12.material = "Copper";
        pipe12.length = 1.5f;
        pipe12.diameter = 0.8f;
        pipe12.color = "Red";
        pipe12.price = 900.0f;
        pipe12.isFlexible = false;
        System.out.println("MATERIAL : " + pipe12.material);
        System.out.println("LENGTH : " + pipe12.length + " m");
        System.out.println("DIAMETER : " + pipe12.diameter + " inch");
        System.out.println("COLOR : " + pipe12.color);
        System.out.println("PRICE : " + pipe12.price);
        System.out.println("IS FLEXIBLE : " + pipe12.isFlexible);

        Pipe pipe13 = new Pipe();
        pipe13.material = "Plastic";
        pipe13.length = 8.0f;
        pipe13.diameter = 4.0f;
        pipe13.color = "Green";
        pipe13.price = 350.0f;
        pipe13.isFlexible = true;
        System.out.println("MATERIAL : " + pipe13.material);
        System.out.println("LENGTH : " + pipe13.length + " m");
        System.out.println("DIAMETER : " + pipe13.diameter + " inch");
        System.out.println("COLOR : " + pipe13.color);
        System.out.println("PRICE : " + pipe13.price);
        System.out.println("IS FLEXIBLE : " + pipe13.isFlexible);

        Pipe pipe14 = new Pipe();
        pipe14.material = "HDPE";
        pipe14.length = 9.0f;
        pipe14.diameter = 3.0f;
        pipe14.color = "Black";
        pipe14.price = 450.0f;
        pipe14.isFlexible = true;
        System.out.println("MATERIAL : " + pipe14.material);
        System.out.println("LENGTH : " + pipe14.length + " m");
        System.out.println("DIAMETER : " + pipe14.diameter + " inch");
        System.out.println("COLOR : " + pipe14.color);
        System.out.println("PRICE : " + pipe14.price);
        System.out.println("IS FLEXIBLE : " + pipe14.isFlexible);

        Pipe pipe15 = new Pipe();
        pipe15.material = "Cast Iron";
        pipe15.length = 2.0f;
        pipe15.diameter = 2.0f;
        pipe15.color = "Black";
        pipe15.price = 750.0f;
        pipe15.isFlexible = false;
        System.out.println("MATERIAL : " + pipe15.material);
        System.out.println("LENGTH : " + pipe15.length + " m");
        System.out.println("DIAMETER : " + pipe15.diameter + " inch");
        System.out.println("COLOR : " + pipe15.color);
        System.out.println("PRICE : " + pipe15.price);
        System.out.println("IS FLEXIBLE : " + pipe15.isFlexible);

        Pipe pipe16 = new Pipe();
        pipe16.material = "Aluminium";
        pipe16.length = 4.0f;
        pipe16.diameter = 2.5f;
        pipe16.color = "Silver";
        pipe16.price = 400.0f;
        pipe16.isFlexible = false;
        System.out.println("MATERIAL : " + pipe16.material);
        System.out.println("LENGTH : " + pipe16.length + " m");
        System.out.println("DIAMETER : " + pipe16.diameter + " inch");
        System.out.println("COLOR : " + pipe16.color);
        System.out.println("PRICE : " + pipe16.price);
        System.out.println("IS FLEXIBLE : " + pipe16.isFlexible);

        Pipe pipe17 = new Pipe();
        pipe17.material = "Galvanized Steel";
        pipe17.length = 6.0f;
        pipe17.diameter = 3.5f;
        pipe17.color = "Grey";
        pipe17.price = 650.0f;
        pipe17.isFlexible = false;
        System.out.println("MATERIAL : " + pipe17.material);
        System.out.println("LENGTH : " + pipe17.length + " m");
        System.out.println("DIAMETER : " + pipe17.diameter + " inch");
        System.out.println("COLOR : " + pipe17.color);
        System.out.println("PRICE : " + pipe17.price);
        System.out.println("IS FLEXIBLE : " + pipe17.isFlexible);

        Pipe pipe18 = new Pipe();
        pipe18.material = "Rubber";
        pipe18.length = 10.0f;
        pipe18.diameter = 2.0f;
        pipe18.color = "Black";
        pipe18.price = 300.0f;
        pipe18.isFlexible = true;
        System.out.println("MATERIAL : " + pipe18.material);
        System.out.println("LENGTH : " + pipe18.length + " m");
        System.out.println("DIAMETER : " + pipe18.diameter + " inch");
        System.out.println("COLOR : " + pipe18.color);
        System.out.println("PRICE : " + pipe18.price);
        System.out.println("IS FLEXIBLE : " + pipe18.isFlexible);

        Pipe pipe19 = new Pipe();
        pipe19.material = "Brass";
        pipe19.length = 1.0f;
        pipe19.diameter = 1.5f;
        pipe19.color = "Golden";
        pipe19.price = 1000.0f;
        pipe19.isFlexible = false;
        System.out.println("MATERIAL : " + pipe19.material);
        System.out.println("LENGTH : " + pipe19.length + " m");
        System.out.println("DIAMETER : " + pipe19.diameter + " inch");
        System.out.println("COLOR : " + pipe19.color);
        System.out.println("PRICE : " + pipe19.price);
        System.out.println("IS FLEXIBLE : " + pipe19.isFlexible);

        Pipe pipe20 = new Pipe();
        pipe20.material = "Steel";
        pipe20.length = 7.5f;
        pipe20.diameter = 4.5f;
        pipe20.color = "Silver";
        pipe20.price = 950.0f;
        pipe20.isFlexible = false;
        System.out.println("MATERIAL : " + pipe20.material);
        System.out.println("LENGTH : " + pipe20.length + " m");
        System.out.println("DIAMETER : " + pipe20.diameter + " inch");
        System.out.println("COLOR : " + pipe20.color);
        System.out.println("PRICE : " + pipe20.price);
        System.out.println("IS FLEXIBLE : " + pipe20.isFlexible);

        System.out.println("MAIN ENDED");
    }
}
