class PoliticianRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Politician politician1 = new Politician();
        politician1.name = "Narendra Modi";
        politician1.party = "BJP";
        politician1.position = "Prime Minister";
        politician1.age = 73;
        politician1.country = "India";
        politician1.isActive = true;
        System.out.println("NAME : " + politician1.name);
        System.out.println("PARTY : " + politician1.party);
        System.out.println("POSITION : " + politician1.position);
        System.out.println("AGE : " + politician1.age);
        System.out.println("COUNTRY : " + politician1.country);
        System.out.println("IS ACTIVE : " + politician1.isActive);

        Politician politician2 = new Politician();
        politician2.name = "Rahul Gandhi";
        politician2.party = "INC";
        politician2.position = "MP";
        politician2.age = 54;
        politician2.country = "India";
        politician2.isActive = true;
        System.out.println("NAME : " + politician2.name);
        System.out.println("PARTY : " + politician2.party);
        System.out.println("POSITION : " + politician2.position);
        System.out.println("AGE : " + politician2.age);
        System.out.println("COUNTRY : " + politician2.country);
        System.out.println("IS ACTIVE : " + politician2.isActive);

        Politician politician3 = new Politician();
        politician3.name = "Amit Shah";
        politician3.party = "BJP";
        politician3.position = "Home Minister";
        politician3.age = 60;
        politician3.country = "India";
        politician3.isActive = true;
        System.out.println("NAME : " + politician3.name);
        System.out.println("PARTY : " + politician3.party);
        System.out.println("POSITION : " + politician3.position);
        System.out.println("AGE : " + politician3.age);
        System.out.println("COUNTRY : " + politician3.country);
        System.out.println("IS ACTIVE : " + politician3.isActive);

        Politician politician4 = new Politician();
        politician4.name = "Sonia Gandhi";
        politician4.party = "INC";
        politician4.position = "Former President INC";
        politician4.age = 77;
        politician4.country = "India";
        politician4.isActive = true;
        System.out.println("NAME : " + politician4.name);
        System.out.println("PARTY : " + politician4.party);
        System.out.println("POSITION : " + politician4.position);
        System.out.println("AGE : " + politician4.age);
        System.out.println("COUNTRY : " + politician4.country);
        System.out.println("IS ACTIVE : " + politician4.isActive);

        Politician politician5 = new Politician();
        politician5.name = "Yogi Adityanath";
        politician5.party = "BJP";
        politician5.position = "CM of UP";
        politician5.age = 51;
        politician5.country = "India";
        politician5.isActive = true;
        System.out.println("NAME : " + politician5.name);
        System.out.println("PARTY : " + politician5.party);
        System.out.println("POSITION : " + politician5.position);
        System.out.println("AGE : " + politician5.age);
        System.out.println("COUNTRY : " + politician5.country);
        System.out.println("IS ACTIVE : " + politician5.isActive);

        Politician politician6 = new Politician();
        politician6.name = "Arvind Kejriwal";
        politician6.party = "AAP";
        politician6.position = "CM of Delhi";
        politician6.age = 56;
        politician6.country = "India";
        politician6.isActive = true;
        System.out.println("NAME : " + politician6.name);
        System.out.println("PARTY : " + politician6.party);
        System.out.println("POSITION : " + politician6.position);
        System.out.println("AGE : " + politician6.age);
        System.out.println("COUNTRY : " + politician6.country);
        System.out.println("IS ACTIVE : " + politician6.isActive);

        Politician politician7 = new Politician();
        politician7.name = "Mamata Banerjee";
        politician7.party = "TMC";
        politician7.position = "CM of West Bengal";
        politician7.age = 69;
        politician7.country = "India";
        politician7.isActive = true;
        System.out.println("NAME : " + politician7.name);
        System.out.println("PARTY : " + politician7.party);
        System.out.println("POSITION : " + politician7.position);
        System.out.println("AGE : " + politician7.age);
        System.out.println("COUNTRY : " + politician7.country);
        System.out.println("IS ACTIVE : " + politician7.isActive);

        Politician politician8 = new Politician();
        politician8.name = "Nitish Kumar";
        politician8.party = "JD(U)";
        politician8.position = "CM of Bihar";
        politician8.age = 73;
        politician8.country = "India";
        politician8.isActive = true;
        System.out.println("NAME : " + politician8.name);
        System.out.println("PARTY : " + politician8.party);
        System.out.println("POSITION : " + politician8.position);
        System.out.println("AGE : " + politician8.age);
        System.out.println("COUNTRY : " + politician8.country);
        System.out.println("IS ACTIVE : " + politician8.isActive);

        Politician politician9 = new Politician();
        politician9.name = "MK Stalin";
        politician9.party = "DMK";
        politician9.position = "CM of Tamil Nadu";
        politician9.age = 72;
        politician9.country = "India";
        politician9.isActive = true;
        System.out.println("NAME : " + politician9.name);
        System.out.println("PARTY : " + politician9.party);
        System.out.println("POSITION : " + politician9.position);
        System.out.println("AGE : " + politician9.age);
        System.out.println("COUNTRY : " + politician9.country);
        System.out.println("IS ACTIVE : " + politician9.isActive);

        Politician politician10 = new Politician();
        politician10.name = "Sharad Pawar";
        politician10.party = "NCP";
        politician10.position = "Party Chief";
        politician10.age = 84;
        politician10.country = "India";
        politician10.isActive = true;
        System.out.println("NAME : " + politician10.name);
        System.out.println("PARTY : " + politician10.party);
        System.out.println("POSITION : " + politician10.position);
        System.out.println("AGE : " + politician10.age);
        System.out.println("COUNTRY : " + politician10.country);
        System.out.println("IS ACTIVE : " + politician10.isActive);

        Politician politician11 = new Politician();
        politician11.name = "Pinarayi Vijayan";
        politician11.party = "CPI(M)";
        politician11.position = "CM of Kerala";
        politician11.age = 79;
        politician11.country = "India";
        politician11.isActive = true;
        System.out.println("NAME : " + politician11.name);
        System.out.println("PARTY : " + politician11.party);
        System.out.println("POSITION : " + politician11.position);
        System.out.println("AGE : " + politician11.age);
        System.out.println("COUNTRY : " + politician11.country);
        System.out.println("IS ACTIVE : " + politician11.isActive);

        Politician politician12 = new Politician();
        politician12.name = "Devendra Fadnavis";
        politician12.party = "BJP";
        politician12.position = "Deputy CM of Maharashtra";
        politician12.age = 54;
        politician12.country = "India";
        politician12.isActive = true;
        System.out.println("NAME : " + politician12.name);
        System.out.println("PARTY : " + politician12.party);
        System.out.println("POSITION : " + politician12.position);
        System.out.println("AGE : " + politician12.age);
        System.out.println("COUNTRY : " + politician12.country);
        System.out.println("IS ACTIVE : " + politician12.isActive);

        Politician politician13 = new Politician();
        politician13.name = "Manmohan Singh";
        politician13.party = "INC";
        politician13.position = "Former PM of India";
        politician13.age = 91;
        politician13.country = "India";
        politician13.isActive = false;
        System.out.println("NAME : " + politician13.name);
        System.out.println("PARTY : " + politician13.party);
        System.out.println("POSITION : " + politician13.position);
        System.out.println("AGE : " + politician13.age);
        System.out.println("COUNTRY : " + politician13.country);
        System.out.println("IS ACTIVE : " + politician13.isActive);

        Politician politician14 = new Politician();
        politician14.name = "Lalu Prasad Yadav";
        politician14.party = "RJD";
        politician14.position = "Former CM of Bihar";
        politician14.age = 77;
        politician14.country = "India";
        politician14.isActive = false;
        System.out.println("NAME : " + politician14.name);
        System.out.println("PARTY : " + politician14.party);
        System.out.println("POSITION : " + politician14.position);
        System.out.println("AGE : " + politician14.age);
        System.out.println("COUNTRY : " + politician14.country);
        System.out.println("IS ACTIVE : " + politician14.isActive);

        Politician politician15 = new Politician();
        politician15.name = "HD Kumaraswamy";
        politician15.party = "JD(S)";
        politician15.position = "Former CM of Karnataka";
        politician15.age = 65;
        politician15.country = "India";
        politician15.isActive = true;
        System.out.println("NAME : " + politician15.name);
        System.out.println("PARTY : " + politician15.party);
        System.out.println("POSITION : " + politician15.position);
        System.out.println("AGE : " + politician15.age);
        System.out.println("COUNTRY : " + politician15.country);
        System.out.println("IS ACTIVE : " + politician15.isActive);

        Politician politician16 = new Politician();
        politician16.name = "K Chandrashekar Rao";
        politician16.party = "BRS";
        politician16.position = "Former CM of Telangana";
        politician16.age = 71;
        politician16.country = "India";
        politician16.isActive = true;
        System.out.println("NAME : " + politician16.name);
        System.out.println("PARTY : " + politician16.party);
        System.out.println("POSITION : " + politician16.position);
        System.out.println("AGE : " + politician16.age);
        System.out.println("COUNTRY : " + politician16.country);
        System.out.println("IS ACTIVE : " + politician16.isActive);

        Politician politician17 = new Politician();
        politician17.name = "Hemant Soren";
        politician17.party = "JMM";
        politician17.position = "Former CM of Jharkhand";
        politician17.age = 49;
        politician17.country = "India";
        politician17.isActive = true;
        System.out.println("NAME : " + politician17.name);
        System.out.println("PARTY : " + politician17.party);
        System.out.println("POSITION : " + politician17.position);
        System.out.println("AGE : " + politician17.age);
        System.out.println("COUNTRY : " + politician17.country);
        System.out.println("IS ACTIVE : " + politician17.isActive);

        Politician politician18 = new Politician();
        politician18.name = "Mayawati";
        politician18.party = "BSP";
        politician18.position = "Former CM of UP";
        politician18.age = 68;
        politician18.country = "India";
        politician18.isActive = true;
        System.out.println("NAME : " + politician18.name);
        System.out.println("PARTY : " + politician18.party);
        System.out.println("POSITION : " + politician18.position);
        System.out.println("AGE : " + politician18.age);
        System.out.println("COUNTRY : " + politician18.country);
        System.out.println("IS ACTIVE : " + politician18.isActive);

        Politician politician19 = new Politician();
        politician19.name = "N. Chandrababu Naidu";
        politician19.party = "TDP";
        politician19.position = "CM of Andhra Pradesh";
        politician19.age = 74;
        politician19.country = "India";
        politician19.isActive = true;
        System.out.println("NAME : " + politician19.name);
        System.out.println("PARTY : " + politician19.party);
        System.out.println("POSITION : " + politician19.position);
        System.out.println("AGE : " + politician19.age);
        System.out.println("COUNTRY : " + politician19.country);
        System.out.println("IS ACTIVE : " + politician19.isActive);

        Politician politician20 = new Politician();
        politician20.name = "Siddaramaiah";
        politician20.party = "INC";
        politician20.position = "CM of Karnataka";
        politician20.age = 76;
        politician20.country = "India";
        politician20.isActive = true;
        System.out.println("NAME : " + politician20.name);
        System.out.println("PARTY : " + politician20.party);
        System.out.println("POSITION : " + politician20.position);
        System.out.println("AGE : " + politician20.age);
        System.out.println("COUNTRY : " + politician20.country);
        System.out.println("IS ACTIVE : " + politician20.isActive);

        System.out.println("MAIN ENDED");
    }
}
