class RodRunner {

    public static void main(String rodArray[]) {
        System.out.println("MAIN STARTED");

        Rod rod1 = new Rod();
        rod1.material = "Steel";
        rod1.type = "Round";
        rod1.length = 3.0f;
        rod1.diameter = 5.0f;
        rod1.weight = 12.5f;
        rod1.price = 2500.50f;
        System.out.println("MATERIAL : " + rod1.material);
        System.out.println("TYPE : " + rod1.type);
        System.out.println("LENGTH : " + rod1.length + " m");
        System.out.println("DIAMETER : " + rod1.diameter + " cm");
        System.out.println("WEIGHT : " + rod1.weight + " kg");
        System.out.println("PRICE : " + rod1.price);

        Rod rod2 = new Rod();
        rod2.material = "Iron";
        rod2.type = "Square";
        rod2.length = 4.5f;
        rod2.diameter = 4.0f;
        rod2.weight = 15.0f;
        rod2.price = 3200.75f;
        System.out.println("MATERIAL : " + rod2.material);
        System.out.println("TYPE : " + rod2.type);
        System.out.println("LENGTH : " + rod2.length + " m");
        System.out.println("DIAMETER : " + rod2.diameter + " cm");
        System.out.println("WEIGHT : " + rod2.weight + " kg");
        System.out.println("PRICE : " + rod2.price);

        Rod rod3 = new Rod();
        rod3.material = "Aluminium";
        rod3.type = "Round";
        rod3.length = 2.5f;
        rod3.diameter = 3.0f;
        rod3.weight = 4.0f;
        rod3.price = 1800.00f;
        System.out.println("MATERIAL : " + rod3.material);
        System.out.println("TYPE : " + rod3.type);
        System.out.println("LENGTH : " + rod3.length + " m");
        System.out.println("DIAMETER : " + rod3.diameter + " cm");
        System.out.println("WEIGHT : " + rod3.weight + " kg");
        System.out.println("PRICE : " + rod3.price);

        Rod rod4 = new Rod();
        rod4.material = "Copper";
        rod4.type = "Round";
        rod4.length = 1.8f;
        rod4.diameter = 2.0f;
        rod4.weight = 5.5f;
        rod4.price = 4500.00f;
        System.out.println("MATERIAL : " + rod4.material);
        System.out.println("TYPE : " + rod4.type);
        System.out.println("LENGTH : " + rod4.length + " m");
        System.out.println("DIAMETER : " + rod4.diameter + " cm");
        System.out.println("WEIGHT : " + rod4.weight + " kg");
        System.out.println("PRICE : " + rod4.price);

        Rod rod5 = new Rod();
        rod5.material = "Brass";
        rod5.type = "Hexagonal";
        rod5.length = 2.0f;
        rod5.diameter = 4.0f;
        rod5.weight = 7.0f;
        rod5.price = 5100.50f;
        System.out.println("MATERIAL : " + rod5.material);
        System.out.println("TYPE : " + rod5.type);
        System.out.println("LENGTH : " + rod5.length + " m");
        System.out.println("DIAMETER : " + rod5.diameter + " cm");
        System.out.println("WEIGHT : " + rod5.weight + " kg");
        System.out.println("PRICE : " + rod5.price);

        Rod rod6 = new Rod();
        rod6.material = "Carbon Fiber";
        rod6.type = "Round";
        rod6.length = 1.5f;
        rod6.diameter = 2.5f;
        rod6.weight = 1.2f;
        rod6.price = 8000.00f;
        System.out.println("MATERIAL : " + rod6.material);
        System.out.println("TYPE : " + rod6.type);
        System.out.println("LENGTH : " + rod6.length + " m");
        System.out.println("DIAMETER : " + rod6.diameter + " cm");
        System.out.println("WEIGHT : " + rod6.weight + " kg");
        System.out.println("PRICE : " + rod6.price);

        Rod rod7 = new Rod();
        rod7.material = "PVC";
        rod7.type = "Hollow";
        rod7.length = 2.5f;
        rod7.diameter = 6.0f;
        rod7.weight = 2.5f;
        rod7.price = 1200.00f;
        System.out.println("MATERIAL : " + rod7.material);
        System.out.println("TYPE : " + rod7.type);
        System.out.println("LENGTH : " + rod7.length + " m");
        System.out.println("DIAMETER : " + rod7.diameter + " cm");
        System.out.println("WEIGHT : " + rod7.weight + " kg");
        System.out.println("PRICE : " + rod7.price);

        Rod rod8 = new Rod();
        rod8.material = "Glass Fiber";
        rod8.type = "Round";
        rod8.length = 2.2f;
        rod8.diameter = 4.0f;
        rod8.weight = 3.5f;
        rod8.price = 3500.00f;
        System.out.println("MATERIAL : " + rod8.material);
        System.out.println("TYPE : " + rod8.type);
        System.out.println("LENGTH : " + rod8.length + " m");
        System.out.println("DIAMETER : " + rod8.diameter + " cm");
        System.out.println("WEIGHT : " + rod8.weight + " kg");
        System.out.println("PRICE : " + rod8.price);

        Rod rod9 = new Rod();
        rod9.material = "Titanium";
        rod9.type = "Round";
        rod9.length = 2.0f;
        rod9.diameter = 3.0f;
        rod9.weight = 4.8f;
        rod9.price = 12000.00f;
        System.out.println("MATERIAL : " + rod9.material);
        System.out.println("TYPE : " + rod9.type);
        System.out.println("LENGTH : " + rod9.length + " m");
        System.out.println("DIAMETER : " + rod9.diameter + " cm");
        System.out.println("WEIGHT : " + rod9.weight + " kg");
        System.out.println("PRICE : " + rod9.price);

        Rod rod10 = new Rod();
        rod10.material = "Stainless Steel";
        rod10.type = "Flat";
        rod10.length = 3.5f;
        rod10.diameter = 2.0f;
        rod10.weight = 8.5f;
        rod10.price = 4700.00f;
        System.out.println("MATERIAL : " + rod10.material);
        System.out.println("TYPE : " + rod10.type);
        System.out.println("LENGTH : " + rod10.length + " m");
        System.out.println("DIAMETER : " + rod10.diameter + " cm");
        System.out.println("WEIGHT : " + rod10.weight + " kg");
        System.out.println("PRICE : " + rod10.price);

        Rod rod11 = new Rod();
        rod11.material = "Bamboo";
        rod11.type = "Fishing Rod";
        rod11.length = 4.0f;
        rod11.diameter = 1.5f;
        rod11.weight = 1.8f;
        rod11.price = 900.00f;
        System.out.println("MATERIAL : " + rod11.material);
        System.out.println("TYPE : " + rod11.type);
        System.out.println("LENGTH : " + rod11.length + " m");
        System.out.println("DIAMETER : " + rod11.diameter + " cm");
        System.out.println("WEIGHT : " + rod11.weight + " kg");
        System.out.println("PRICE : " + rod11.price);

        Rod rod12 = new Rod();
        rod12.material = "Mild Steel";
        rod12.type = "Round";
        rod12.length = 3.0f;
        rod12.diameter = 6.0f;
        rod12.weight = 10.5f;
        rod12.price = 2600.00f;
        System.out.println("MATERIAL : " + rod12.material);
        System.out.println("TYPE : " + rod12.type);
        System.out.println("LENGTH : " + rod12.length + " m");
        System.out.println("DIAMETER : " + rod12.diameter + " cm");
        System.out.println("WEIGHT : " + rod12.weight + " kg");
        System.out.println("PRICE : " + rod12.price);

        Rod rod13 = new Rod();
        rod13.material = "Iron";
        rod13.type = "Hollow";
        rod13.length = 4.0f;
        rod13.diameter = 5.0f;
        rod13.weight = 11.0f;
        rod13.price = 3000.00f;
        System.out.println("MATERIAL : " + rod13.material);
        System.out.println("TYPE : " + rod13.type);
        System.out.println("LENGTH : " + rod13.length + " m");
        System.out.println("DIAMETER : " + rod13.diameter + " cm");
        System.out.println("WEIGHT : " + rod13.weight + " kg");
        System.out.println("PRICE : " + rod13.price);

        Rod rod14 = new Rod();
        rod14.material = "Cast Iron";
        rod14.type = "Square";
        rod14.length = 2.8f;
        rod14.diameter = 4.5f;
        rod14.weight = 9.5f;
        rod14.price = 2700.00f;
        System.out.println("MATERIAL : " + rod14.material);
        System.out.println("TYPE : " + rod14.type);
        System.out.println("LENGTH : " + rod14.length + " m");
        System.out.println("DIAMETER : " + rod14.diameter + " cm");
        System.out.println("WEIGHT : " + rod14.weight + " kg");
        System.out.println("PRICE : " + rod14.price);

        Rod rod15 = new Rod();
        rod15.material = "Copper";
        rod15.type = "Flat";
        rod15.length = 2.5f;
        rod15.diameter = 3.0f;
        rod15.weight = 6.5f;
        rod15.price = 5500.00f;
        System.out.println("MATERIAL : " + rod15.material);
        System.out.println("TYPE : " + rod15.type);
        System.out.println("LENGTH : " + rod15.length + " m");
        System.out.println("DIAMETER : " + rod15.diameter + " cm");
        System.out.println("WEIGHT : " + rod15.weight + " kg");
        System.out.println("PRICE : " + rod15.price);

        Rod rod16 = new Rod();
        rod16.material = "Brass";
        rod16.type = "Round";
        rod16.length = 2.3f;
        rod16.diameter = 3.5f;
        rod16.weight = 7.5f;
        rod16.price = 5800.00f;
        System.out.println("MATERIAL : " + rod16.material);
        System.out.println("TYPE : " + rod16.type);
        System.out.println("LENGTH : " + rod16.length + " m");
        System.out.println("DIAMETER : " + rod16.diameter + " cm");
        System.out.println("WEIGHT : " + rod16.weight + " kg");
        System.out.println("PRICE : " + rod16.price);

        Rod rod17 = new Rod();
        rod17.material = "Carbon Steel";
        rod17.type = "Square";
        rod17.length = 3.2f;
        rod17.diameter = 4.0f;
        rod17.weight = 9.0f;
        rod17.price = 4200.00f;
        System.out.println("MATERIAL : " + rod17.material);
        System.out.println("TYPE : " + rod17.type);
        System.out.println("LENGTH : " + rod17.length + " m");
        System.out.println("DIAMETER : " + rod17.diameter + " cm");
        System.out.println("WEIGHT : " + rod17.weight + " kg");
        System.out.println("PRICE : " + rod17.price);

        Rod rod18 = new Rod();
        rod18.material = "Fiberglass";
        rod18.type = "Round";
        rod18.length = 2.6f;
        rod18.diameter = 3.5f;
        rod18.weight = 2.8f;
        rod18.price = 3700.00f;
        System.out.println("MATERIAL : " + rod18.material);
        System.out.println("TYPE : " + rod18.type);
        System.out.println("LENGTH : " + rod18.length + " m");
        System.out.println("DIAMETER : " + rod18.diameter + " cm");
        System.out.println("WEIGHT : " + rod18.weight + " kg");
        System.out.println("PRICE : " + rod18.price);

        Rod rod19 = new Rod();
        rod19.material = "PVC";
        rod19.type = "Round";
        rod19.length = 2.8f;
        rod19.diameter = 5.0f;
        rod19.weight = 2.2f;
        rod19.price = 1000.00f;
        System.out.println("MATERIAL : " + rod19.material);
        System.out.println("TYPE : " + rod19.type);
        System.out.println("LENGTH : " + rod19.length + " m");
        System.out.println("DIAMETER : " + rod19.diameter + " cm");
        System.out.println("WEIGHT : " + rod19.weight + " kg");
        System.out.println("PRICE : " + rod19.price);

        Rod rod20 = new Rod();
        rod20.material = "Alloy Steel";
        rod20.type = "Round";
        rod20.length = 3.0f;
        rod20.diameter = 4.5f;
        rod20.weight = 8.8f;
        rod20.price = 4600.00f;
        System.out.println("MATERIAL : " + rod20.material);
        System.out.println("TYPE : " + rod20.type);
        System.out.println("LENGTH : " + rod20.length + " m");
        System.out.println("DIAMETER : " + rod20.diameter + " cm");
        System.out.println("WEIGHT : " + rod20.weight + " kg");
        System.out.println("PRICE : " + rod20.price);

        System.out.println("MAIN ENDED");
    }
}
