class WeaponRunner {

    public static void main(String args[]) {
        System.out.println("MAIN STARTED");

        Weapon weapon1 = new Weapon();
        weapon1.name = "Katana";
        weapon1.type = "Melee";
        weapon1.material = "Steel";
        weapon1.weight = 1.2f;
        weapon1.price = 15000.0f;
        weapon1.origin = "Japan";
        System.out.println("NAME : " + weapon1.name);
        System.out.println("TYPE : " + weapon1.type);
        System.out.println("MATERIAL : " + weapon1.material);
        System.out.println("WEIGHT : " + weapon1.weight);
        System.out.println("PRICE : " + weapon1.price);
        System.out.println("ORIGIN : " + weapon1.origin);

        Weapon weapon2 = new Weapon();
        weapon2.name = "Longsword";
        weapon2.type = "Melee";
        weapon2.material = "High Carbon Steel";
        weapon2.weight = 1.5f;
        weapon2.price = 12000.0f;
        weapon2.origin = "Europe";
        System.out.println("NAME : " + weapon2.name);
        System.out.println("TYPE : " + weapon2.type);
        System.out.println("MATERIAL : " + weapon2.material);
        System.out.println("WEIGHT : " + weapon2.weight);
        System.out.println("PRICE : " + weapon2.price);
        System.out.println("ORIGIN : " + weapon2.origin);

        Weapon weapon3 = new Weapon();
        weapon3.name = "Crossbow";
        weapon3.type = "Ranged";
        weapon3.material = "Wood & Steel";
        weapon3.weight = 2.8f;
        weapon3.price = 9000.0f;
        weapon3.origin = "China";
        System.out.println("NAME : " + weapon3.name);
        System.out.println("TYPE : " + weapon3.type);
        System.out.println("MATERIAL : " + weapon3.material);
        System.out.println("WEIGHT : " + weapon3.weight);
        System.out.println("PRICE : " + weapon3.price);
        System.out.println("ORIGIN : " + weapon3.origin);

        Weapon weapon4 = new Weapon();
        weapon4.name = "Dagger";
        weapon4.type = "Melee";
        weapon4.material = "Stainless Steel";
        weapon4.weight = 0.5f;
        weapon4.price = 2500.0f;
        weapon4.origin = "Italy";
        System.out.println("NAME : " + weapon4.name);
        System.out.println("TYPE : " + weapon4.type);
        System.out.println("MATERIAL : " + weapon4.material);
        System.out.println("WEIGHT : " + weapon4.weight);
        System.out.println("PRICE : " + weapon4.price);
        System.out.println("ORIGIN : " + weapon4.origin);

        Weapon weapon5 = new Weapon();
        weapon5.name = "Axe";
        weapon5.type = "Melee";
        weapon5.material = "Iron & Wood";
        weapon5.weight = 3.0f;
        weapon5.price = 5000.0f;
        weapon5.origin = "Viking";
        System.out.println("NAME : " + weapon5.name);
        System.out.println("TYPE : " + weapon5.type);
        System.out.println("MATERIAL : " + weapon5.material);
        System.out.println("WEIGHT : " + weapon5.weight);
        System.out.println("PRICE : " + weapon5.price);
        System.out.println("ORIGIN : " + weapon5.origin);

        Weapon weapon6 = new Weapon();
        weapon6.name = "Spear";
        weapon6.type = "Melee";
        weapon6.material = "Steel Tip & Bamboo";
        weapon6.weight = 2.2f;
        weapon6.price = 3500.0f;
        weapon6.origin = "Greece";
        System.out.println("NAME : " + weapon6.name);
        System.out.println("TYPE : " + weapon6.type);
        System.out.println("MATERIAL : " + weapon6.material);
        System.out.println("WEIGHT : " + weapon6.weight);
        System.out.println("PRICE : " + weapon6.price);
        System.out.println("ORIGIN : " + weapon6.origin);

        Weapon weapon7 = new Weapon();
        weapon7.name = "Halberd";
        weapon7.type = "Melee";
        weapon7.material = "Iron";
        weapon7.weight = 3.8f;
        weapon7.price = 11000.0f;
        weapon7.origin = "Switzerland";
        System.out.println("NAME : " + weapon7.name);
        System.out.println("TYPE : " + weapon7.type);
        System.out.println("MATERIAL : " + weapon7.material);
        System.out.println("WEIGHT : " + weapon7.weight);
        System.out.println("PRICE : " + weapon7.price);
        System.out.println("ORIGIN : " + weapon7.origin);

        Weapon weapon8 = new Weapon();
        weapon8.name = "War Hammer";
        weapon8.type = "Melee";
        weapon8.material = "Steel Head & Oak Handle";
        weapon8.weight = 4.5f;
        weapon8.price = 13000.0f;
        weapon8.origin = "England";
        System.out.println("NAME : " + weapon8.name);
        System.out.println("TYPE : " + weapon8.type);
        System.out.println("MATERIAL : " + weapon8.material);
        System.out.println("WEIGHT : " + weapon8.weight);
        System.out.println("PRICE : " + weapon8.price);
        System.out.println("ORIGIN : " + weapon8.origin);

        Weapon weapon9 = new Weapon();
        weapon9.name = "Bow";
        weapon9.type = "Ranged";
        weapon9.material = "Bamboo & String";
        weapon9.weight = 1.0f;
        weapon9.price = 4000.0f;
        weapon9.origin = "India";
        System.out.println("NAME : " + weapon9.name);
        System.out.println("TYPE : " + weapon9.type);
        System.out.println("MATERIAL : " + weapon9.material);
        System.out.println("WEIGHT : " + weapon9.weight);
        System.out.println("PRICE : " + weapon9.price);
        System.out.println("ORIGIN : " + weapon9.origin);

        Weapon weapon10 = new Weapon();
        weapon10.name = "Mace";
        weapon10.type = "Melee";
        weapon10.material = "Bronze";
        weapon10.weight = 2.7f;
        weapon10.price = 8000.0f;
        weapon10.origin = "Mesopotamia";
        System.out.println("NAME : " + weapon10.name);
        System.out.println("TYPE : " + weapon10.type);
        System.out.println("MATERIAL : " + weapon10.material);
        System.out.println("WEIGHT : " + weapon10.weight);
        System.out.println("PRICE : " + weapon10.price);
        System.out.println("ORIGIN : " + weapon10.origin);

        Weapon weapon11 = new Weapon();
        weapon11.name = "Rapier";
        weapon11.type = "Melee";
        weapon11.material = "Steel";
        weapon11.weight = 1.1f;
        weapon11.price = 12500.0f;
        weapon11.origin = "Spain";
        System.out.println("NAME : " + weapon11.name);
        System.out.println("TYPE : " + weapon11.type);
        System.out.println("MATERIAL : " + weapon11.material);
        System.out.println("WEIGHT : " + weapon11.weight);
        System.out.println("PRICE : " + weapon11.price);
        System.out.println("ORIGIN : " + weapon11.origin);

        Weapon weapon12 = new Weapon();
        weapon12.name = "Scimitar";
        weapon12.type = "Melee";
        weapon12.material = "Damascus Steel";
        weapon12.weight = 1.4f;
        weapon12.price = 14000.0f;
        weapon12.origin = "Middle East";
        System.out.println("NAME : " + weapon12.name);
        System.out.println("TYPE : " + weapon12.type);
        System.out.println("MATERIAL : " + weapon12.material);
        System.out.println("WEIGHT : " + weapon12.weight);
        System.out.println("PRICE : " + weapon12.price);
        System.out.println("ORIGIN : " + weapon12.origin);

        Weapon weapon13 = new Weapon();
        weapon13.name = "Chakram";
        weapon13.type = "Ranged";
        weapon13.material = "Steel";
        weapon13.weight = 0.7f;
        weapon13.price = 3000.0f;
        weapon13.origin = "India";
        System.out.println("NAME : " + weapon13.name);
        System.out.println("TYPE : " + weapon13.type);
        System.out.println("MATERIAL : " + weapon13.material);
        System.out.println("WEIGHT : " + weapon13.weight);
        System.out.println("PRICE : " + weapon13.price);
        System.out.println("ORIGIN : " + weapon13.origin);

        Weapon weapon14 = new Weapon();
        weapon14.name = "Naginata";
        weapon14.type = "Melee";
        weapon14.material = "Steel & Wood";
        weapon14.weight = 2.5f;
        weapon14.price = 10000.0f;
        weapon14.origin = "Japan";
        System.out.println("NAME : " + weapon14.name);
        System.out.println("TYPE : " + weapon14.type);
        System.out.println("MATERIAL : " + weapon14.material);
        System.out.println("WEIGHT : " + weapon14.weight);
        System.out.println("PRICE : " + weapon14.price);
        System.out.println("ORIGIN : " + weapon14.origin);

        Weapon weapon15 = new Weapon();
        weapon15.name = "Sai";
        weapon15.type = "Melee";
        weapon15.material = "Steel";
        weapon15.weight = 0.9f;
        weapon15.price = 4500.0f;
        weapon15.origin = "Okinawa";
        System.out.println("NAME : " + weapon15.name);
        System.out.println("TYPE : " + weapon15.type);
        System.out.println("MATERIAL : " + weapon15.material);
        System.out.println("WEIGHT : " + weapon15.weight);
        System.out.println("PRICE : " + weapon15.price);
        System.out.println("ORIGIN : " + weapon15.origin);

        Weapon weapon16 = new Weapon();
        weapon16.name = "Kukri";
        weapon16.type = "Melee";
        weapon16.material = "Steel";
        weapon16.weight = 0.8f;
        weapon16.price = 5500.0f;
        weapon16.origin = "Nepal";
        System.out.println("NAME : " + weapon16.name);
        System.out.println("TYPE : " + weapon16.type);
        System.out.println("MATERIAL : " + weapon16.material);
        System.out.println("WEIGHT : " + weapon16.weight);
        System.out.println("PRICE : " + weapon16.price);
        System.out.println("ORIGIN : " + weapon16.origin);

        Weapon weapon17 = new Weapon();
        weapon17.name = "Morning Star";
        weapon17.type = "Melee";
        weapon17.material = "Iron & Chain";
        weapon17.weight = 3.3f;
        weapon17.price = 13500.0f;
        weapon17.origin = "Germany";
        System.out.println("NAME : " + weapon17.name);
        System.out.println("TYPE : " + weapon17.type);
        System.out.println("MATERIAL : " + weapon17.material);
        System.out.println("WEIGHT : " + weapon17.weight);
        System.out.println("PRICE : " + weapon17.price);
        System.out.println("ORIGIN : " + weapon17.origin);

        Weapon weapon18 = new Weapon();
        weapon18.name = "Throwing Knife";
        weapon18.type = "Ranged";
        weapon18.material = "Stainless Steel";
        weapon18.weight = 0.4f;
        weapon18.price = 2000.0f;
        weapon18.origin = "France";
        System.out.println("NAME : " + weapon18.name);
        System.out.println("TYPE : " + weapon18.type);
        System.out.println("MATERIAL : " + weapon18.material);
        System.out.println("WEIGHT : " + weapon18.weight);
        System.out.println("PRICE : " + weapon18.price);
        System.out.println("ORIGIN : " + weapon18.origin);

        Weapon weapon19 = new Weapon();
        weapon19.name = "Tomahawk";
        weapon19.type = "Melee";
        weapon19.material = "Steel Head & Wooden Handle";
        weapon19.weight = 1.6f;
        weapon19.price = 7000.0f;
        weapon19.origin = "Native America";
        System.out.println("NAME : " + weapon19.name);
        System.out.println("TYPE : " + weapon19.type);
        System.out.println("MATERIAL : " + weapon19.material);
        System.out.println("WEIGHT : " + weapon19.weight);
        System.out.println("PRICE : " + weapon19.price);
        System.out.println("ORIGIN : " + weapon19.origin);

        Weapon weapon20 = new Weapon();
        weapon20.name = "Flamethrower";
        weapon20.type = "Ranged";
        weapon20.material = "Steel & Alloy";
        weapon20.weight = 8.0f;
        weapon20.price = 45000.0f;
        weapon20.origin = "Germany";
        System.out.println("NAME : " + weapon20.name);
        System.out.println("TYPE : " + weapon20.type);
        System.out.println("MATERIAL : " + weapon20.material);
        System.out.println("WEIGHT : " + weapon20.weight);
        System.out.println("PRICE : " + weapon20.price);
        System.out.println("ORIGIN : " + weapon20.origin);

        System.out.println("MAIN ENDED");
    }
}
